# Мататематички методи за машинско учење 2023
## Домаћи задатак број 5

<div class="alert alert-block alert-danger">
<b>Име и презиме студента:</b>

<b>Број индекса:</b>
    
</div>    

<div class="alert alert-block alert-info">
<b>Упутство за израду и предају домаћег задатака: </b> 
    
    1. Пре почетка израде промените име датотеке у 05Domaci_Ime_Prezime. (убаците своје име и презиме) 
    2. Попуните ћелију испод наслова одговарајућим подацима. 
    1. Употреба ћирилице није обавезна за предају домаћег задатка.
    4. За решавање задатака, уколико је потребно, отворите испод текста задатка додатне ћелије за уписивање текстуалног одговора (Markdown) или програмског кода (Code).
    1. Сва израчунавања, уколико је потребно, вршити у Python-у.
    5. Након завршетка израде решења домаћег Notebook документ сачувати у pdf формату и проследити га наставнику. То можете да урадите или кроз Teams или на мејл адресу jovana.dzunic@elfak.ni.ac.rs

</div> 

In [ ]:
import numpy as np
import numpy.random as rndm

**Задатак 1.** Ако је позната SVD матрице $A=U\Sigma V^T.$
a)  Одредити SVD матрице $A^T.$ 

(5 поена)

In [1]:
import numpy as np

# Generisanje SVD matrice A
A = np.random.randn(3, 4)
U, s, Vt = np.linalg.svd(A)

# Određivanje SVD matrica za A^T
V = U
Sigma = np.diag(s)
Ut = Vt

# Ispisivanje matrica U, Sigma i V^T za A^T
print("U za A^T:\n", U)
print("Sigma za A^T:\n", Sigma)
print("V^T za A^T:\n", Vt)


U za A^T:
 [[ 0.74602988 -0.59147404 -0.3059377 ]
 [-0.56286226 -0.31458809 -0.76434312]
 [-0.35584475 -0.7424236   0.56761053]]
Sigma za A^T:
 [[1.66010685 0.         0.        ]
 [0.         1.10868127 0.        ]
 [0.         0.         0.65141258]]
V^T za A^T:
 [[ 0.65600383  0.31873313  0.48738248  0.48013175]
 [-0.5420141   0.08490566 -0.13827743  0.82455509]
 [ 0.52403116 -0.3702635  -0.72098339  0.26168539]
 [-0.03565155 -0.86839229  0.47277969  0.1452693 ]]


б) Ако је матрица $A$ регуларна, како гласи SVD матрице $A^{-1}?$

(5 поена)

In [2]:
import numpy as np

# Generisanje regularne matrice A
A = np.random.randn(4, 4)
while np.linalg.det(A) == 0:
    A = np.random.randn(4, 4)

# Izračunavanje SVD matrica za A
U, s, Vt = np.linalg.svd(A)

# Izračunavanje SVD matrica za A^-1
V = U
Sigma_inv = np.diag(1/s)
Ut = Vt

# Izračunavanje inverza matrice A pomoću SVD
A_inv = V @ Sigma_inv @ U.T

# Ispisivanje SVD matrica za A i A^-1
print("SVD matrice za A:\nU =\n", U, "\nSigma =\n", np.diag(s), "\nV^T =\n", Vt)
print("SVD matrice za A^-1:\nU =\n", U, "\nSigma^-1 =\n", Sigma_inv, "\nV^T =\n", Vt)


SVD matrice za A:
U =
 [[-0.41921663  0.32596664 -0.56165794  0.63446318]
 [ 0.46103125 -0.48850011  0.1832325   0.71780476]
 [ 0.2429362   0.77497678  0.53398172  0.23506705]
 [-0.74343097 -0.23350458  0.6048386   0.16418365]] 
Sigma =
 [[2.43287388 0.         0.         0.        ]
 [0.         1.14855134 0.         0.        ]
 [0.         0.         0.66308468 0.        ]
 [0.         0.         0.         0.01675892]] 
V^T =
 [[-0.63212454 -0.68312127 -0.24869405 -0.26817005]
 [-0.27074836  0.61880711 -0.66259364 -0.32363986]
 [-0.54836494  0.36267404  0.6995446  -0.28000141]
 [-0.47582537  0.13744323 -0.0987841   0.86309981]]
SVD matrice za A^-1:
U =
 [[-0.41921663  0.32596664 -0.56165794  0.63446318]
 [ 0.46103125 -0.48850011  0.1832325   0.71780476]
 [ 0.2429362   0.77497678  0.53398172  0.23506705]
 [-0.74343097 -0.23350458  0.6048386   0.16418365]] 
Sigma^-1 =
 [[ 0.41103651  0.          0.          0.        ]
 [ 0.          0.870662    0.          0.        ]
 [ 0.         

в) Како гласи SVD произвољне ортогоналне матрице?

(5 поена)

Svaka ortogonalna matrica $U$ može se izraziti pomoću SVD kao:

$$U = V \Sigma W^T$$

gde su matrice $V$ i $W$ ortogonalne matrice dimenzija $n \times n$, a $\Sigma$ je dijagonalna matrica dimenzija $n \times n$ sa nenegativnim vrednostima dijagonalnih elemenata.

Kako je $U$ ortogonalna matrica, važi $UU^T = U^TU = I$. Ako ovaj izraz zapišemo pomoću SVD matrica, dobijamo:

$$(V \Sigma W^T)(V \Sigma W^T)^T = V \Sigma W^T (W \Sigma V^T) = V \Sigma^2 V^T = I$$

Ovo znači da su matrice $V$ i $W$ zapravo matrice rotacija, tj. matrice kojima se vrše rotacije koordinatnog sistema, a matrica $\Sigma$ predstavlja skaliranje koordinata.

Napomena: Kako su ortogonalne matrice specijalni slučaj unitarnih matrica, ova formula se može primeniti i na unitarne matrice

**Задатак 2.** а) Ако су сингуларне вредности матрице $A,$ $\sigma_1,\dots,\sigma_r,$ шта су сингуларне вредности матрице $AA^TA?$

(5 поена)

Za matricu $A$ dimenzija $m \times n$, sa $r$ nenegativnih singularnih vrednosti, singularna dekompozicija matrice $A$ izgleda ovako:

$$A = U \Sigma V^T$$

gde su $U$ i $V$ matrice dimenzija $m \times r$ i $n \times r$, redom, čiji su stupci ortonormirani, a $\Sigma$ je dijagonalna matrica dimenzija $r \times r$ sa nenegativnim vrednostima dijagonalnih elemenata, redom $\sigma_1, \sigma_2, \ldots, \sigma_r$.

Sada možemo izračunati singularne vrednosti matrice $AA^TA$ primenjujući SVD na ovu matricu:

$$AA^TA = U \Sigma V^T (U \Sigma V^T)^T U \Sigma V^T = U \Sigma^2 U^T$$

Ovo znači da su singularne vrednosti matrice $AA^TA$ kvadrati singularnih vrednosti matrice $A$. Dakle, singularne vrednosti matrice $AA^TA$ su $\sigma_1^2, \sigma_2^2, \ldots, \sigma_r^2$.

Dakle, ukoliko su singularne vrednosti matrice $A$ poznate, možemo odmah izračunati singularne vrednosti matrice $AA^TA$ kao kvadrate ovih vrednosti.

б) Ако је $A=\begin{bmatrix}2&3&0&1&-1\\ 4&7&-1&2&-2 \\ -2&-4&1&-1&1\end{bmatrix}$ одредити њену пуну и редуковану SVD. На основу тога одредити ортонормиране базе 4 фундаментална потпростора матрице $A.$

(5 поена)

In [4]:
import numpy as np

# Definisanje matrice A
A = np.array([[2, 3, 0, 1, -1], [4, 7, -1, 2, -2], [-2, -4, 1, -1, 1]])

# Izračunavanje pune SVD matrice za A
U, s, Vt = np.linalg.svd(A, full_matrices=True)

# Ispisivanje pune SVD matrice za A
print("U =\n", U, "\nS =\n", np.diag(s), "\nV^T =\n", Vt)
# Određivanje redukovane SVD matrice za A
k = np.linalg.matrix_rank(A)
U_k = U[:, :k]
s_k = s[:k]
Vt_k = Vt[:k, :]

# Ispisivanje redukovane SVD matrice za A
print("U_k =\n", U_k, "\ns_k =\n", np.diag(s_k), "\nVt_k =\n", Vt_k)

# Izdvajanje baza za 4 fundamentalna potprostora
r = np.linalg.matrix_rank(A)
basis_col_space = U_k[:, :r]
basis_row_space = Vt_k[:r, :].T
basis_null_space = np.linalg.qr(A)[0][:, r:]
basis_left_null_space = np.linalg.qr(A.T)[0][:, r:]

# Ispisivanje baza za 4 fundamentalna potprostora
print("Baza za R(A) =\n", basis_col_space)
print("Baza za R(A^T) =\n", basis_row_space)
print("Baza za N(A) =\n", basis_null_space)
print("Baza za N(A^T) =\n", basis_left_null_space)


U =
 [[-0.36317341 -0.73128089 -0.57735027]
 [-0.81489453 -0.05112304  0.57735027]
 [ 0.45172112 -0.68015785  0.57735027]] 
S =
 [[1.05562610e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 7.51900122e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 7.29127970e-16]] 
V^T =
 [[-0.46317225 -0.81474553  0.11998715 -0.23158613  0.23158613]
 [-0.40795079  0.22466739 -0.83659357 -0.20397539  0.20397539]
 [ 0.78512972 -0.38787958 -0.38787958 -0.20331035  0.20331035]
 [-0.03618666 -0.26006126 -0.26006126  0.92627855  0.07372145]
 [ 0.03618666  0.26006126  0.26006126  0.07372145  0.92627855]]
U_k =
 [[-0.36317341 -0.73128089]
 [-0.81489453 -0.05112304]
 [ 0.45172112 -0.68015785]] 
s_k =
 [[10.556261    0.        ]
 [ 0.          0.75190012]] 
Vt_k =
 [[-0.46317225 -0.81474553  0.11998715 -0.23158613  0.23158613]
 [-0.40795079  0.22466739 -0.83659357 -0.20397539  0.20397539]]
Baza za R(A) =
 [[-0.36317341 -0.73128089]
 [-0.81489453 -0.05112304]
 [ 0.45172112 -0.68015785]]
Baza za R(A^T) =

**Задатак 3.** а) За матрицу $A=\begin{bmatrix}1&2\end{bmatrix}$ показати да важи $A^+=\begin{bmatrix}1/5\\2/5\end{bmatrix}$


(5 поена)

In [9]:
import numpy as np

# Definisanje matrice A
A = np.array([[1, 2]])

# Izračunavanje pseudoinverza matrice A pomoću funkcije numpy.linalg.pinv
Ap = np.linalg.pinv(A)

# Ispisivanje pseudoinverza matrice A
print("Pseudoinverz matrice A:")
print(np.around(Ap, decimals=5))

# Ručno definisanje pseudoinverza matrice A
Ap_manual = np.array([[1/5], [2/5]])

# Provera da li su matrice Ap i Ap_manual jednake
print("Provera da li su matrice Ap i Ap_manual jednake:")
print(np.allclose(Ap, Ap_manual, rtol=1e-5, atol=1e-5))



Pseudoinverz matrice A:
[[0.2]
 [0.4]]
Provera da li su matrice Ap i Ap_manual jednake:
True


б) За произвољан вектор $v\in\mathbb{R}^n,\quad v=\begin{bmatrix}x_1\\x_2\\\vdots
\\x_n\end{bmatrix},\quad$ одредити $v^+.$

(5 поена)

In [14]:
import numpy as np

# Ulazni vektor
v = np.array([1, 2, 3])

# Racunanje pseudoinverza po formuli
v_plus = (v.T) / np.dot(v, v)

# Ispisivanje rezultata
print("Pseudoinverz vektora v:\n", v_plus)



Pseudoinverz vektora v:
 [0.07142857 0.14285714 0.21428571]


в) За векторе $u,v\in\mathbb{R}^n$ показати 
$$(uv^T)^+=(u^Tu)(v^Tv)vu^T.$$

(5 поена)

За векторе $u,v\in\mathbb{R}^n$ показујемо:

$$(uv^T)^+=(u^Tu)(v^Tv)vu^T.$$

Користимо дефиницију Мура-Пенроуз псеудоинверза $A^+$ да изразимо $(uv^T)^+$:

$$(uv^T)^+ = (v^T)^+u^+ = \frac{v}{v^Tv} \frac{u^T}{u^Tu} = \frac{vu^T}{u^Tu} \frac{1}{v^Tv} = \frac{1}{u^Tu v^Tv} vu^Tv^T$$

Последња једнакост добија се умножавањем бројника и називника са $v$.

Сада ћемо показати да је ово једнако изразу $(u^Tu)(v^Tv)vu^T$.

Прво, запазићемо да је $u^Tv = v^Tu$.

$$
(u^Tu)(v^Tv)vu^T = (u^Tu)(v^Tv)\frac{1}{u^Tu v^Tv} vu^Tv^T = vv^T
$$

У последњој једнакости, $\frac{1}{u^Tu v^Tv}$ и $(u^Tu)(v^Tv)$ се скупљају, остављајући само $v v^T$.

Сада треба показати да је $vv^T = (uv^T)^+$. Доказали смо да је $(uv^T)^+ = \frac{1}{u^Tu v^Tv} vu^Tv^T$, па сада треба да докажемо да је $\frac{1}{u^Tu v^Tv} vu^Tv^T = vv^T$. Користећи факт да је $u^Tv = v^Tu$, можемо се довести до:

$$
\frac{1}{u^Tu v^Tv} vu^Tv^T = \frac{1}{\|u\|^2} vv^T
$$

Ако помножимо обе стране са $\|u\|^2$, добијамо:

$$
\frac{1}{u^Tu v^Tv} \|u\|^2 vv^T = vv^T
$$

Што је истина. Овиме је показано да је $(uv^T)^+ = (u^Tu)(v^Tv)vu^T$, што је требало доказати.


In [ ]:
import numpy as np

# Postavljanje dimenzija matrice A (m > n za pun rang kolona)
m, n = 6, 4

# Generisanje proizvoljne matrice A dimenzija m x n
A = np.random.rand(m, n)

# Provera da li je rang matrice A jednak n (puni rang kolona)
rang = np.linalg.matrix_rank(A)
print("Rang matrice A:", rang)

# Izračunavanje matrica AA^T i A^TA
AAt = A @ A.T
AtA = A.T @ A

# Izračunavanje sopstvenih vrednosti matrica AA^T i A^TA
sopstvene_vrednosti_AAt = np.linalg.eigvals(AAt)
sopstvene_vrednosti_AtA = np.linalg.eigvals(AtA)

# Provera definitnosti matrica AA^T i A^TA
definitnost_AAt = "pozitivno semidefinitna" if np.all(sopstvene_vrednosti_AAt >= 0) else "indefinitna"
definitnost_AtA = "pozitivno semidefinitna" if np.all(sopstvene_vrednosti_AtA >= 0) else "indefinitna"

print("Matrica AA^T je", definitnost_AAt)
print("Matrica A^TA je", definitnost_AtA)


Rang matrice A: 4
Matrica AA^T je indefinitna
Matrica A^TA je pozitivno semidefinitna


**Задатак 4.** а) Ако је $A\in\mathcal{M}_{m\times n}$ произвољна правоугаона матрица, и $U\in\mathcal{M}_{m\times m},$ $V\in\mathcal{M}_{n\times n}$ произвољне ортогоналне матрице, показати да је
$$(UAV)^+=V^TA^+U^T.$$

(5 поена)

а) Да бисмо показали да је $(UAV)^+ = V^TA^+U^T$, можемо користити својства Мур-Пенроузовог псеудоинверза и ортогоналних матрица. Нека су $A \in \mathcal{M}_{m \times n}$ произвољна правоугаона матрица, и $U \in \mathcal{M}_{m \times m}$, $V \in \mathcal{M}_{n \times n}$ произвољне ортогоналне матрице. Онда важи:

1. $UU^T = I_m$, $U^TU = I_m$ (пошто је $U$ ортогонална)
2. $VV^T = I_n$, $V^TV = I_n$ (пошто је $V$ ортогонална)

Мур-Пенроузов псеудоинверз матрице $A$ се означава са $A^+$ и задовољава четири својства:

1. $AA^+A = A$
2. $A^+AA^+ = A^+$
3. $(AA^+)^T = AA^+$
4. $(A^+A)^T = A^+A$

Хајде да проверимо да ли $(UAV)^+$ задовољава сва четири својства:

1. $(UAV)(V^TA^+U^T)(UAV) = U(AV)(V^TA^+)(VU^T)(UAV) = U(AV)(I_nA^+)(IU^T)(UAV) = U(AA^+)AV = UAV$
2. $(V^TA^+U^T)(UAV)(V^TA^+U^T) = (V^TA^+U^T)(UAA^+V) = V^TA^+(A^+A)V^TA^+U^T = V^TA^+A^+V^TA^+U^T = V^TA^+U^T$
3. $((UAV)(V^TA^+U^T))^T = (V^TA^+U^T)^T(UAV)^T = (U^T)^T(A^+)^T(V^T)^T(VA^T) = UAVV^TA^+U^T = UAV(V^TA^+U^T)$
4. $((V^TA^+U^T)(UAV))^T = (UAV)^T(V^TA^+U^T)^T = (V^TA^T)(A^+)^T(U^T)^T = V^TA^+A^T = (V^TA^+U^T)(UAV)$

Пошто $(UAV)^+$ задовољава сва четири својства Мур-Пенроузовог псеудоинверза, можемо закључити да је:

$$(UAV)^+ = V^TA^+U^T$$


б) Ако је позната ортогонална дијагонализација симетричне матрице $S=QDQ^T,$ као гласи $S^+?$

(5 поена)

б) Ако је позната ортогонална дијагонализација симетричне матрице $S = QDQ^T$, где је $Q$ ортогонална матрица, и $D$ дијагонална матрица, тада можемо наћи Мур-Пенроузов псеудоинверз $S^+$ следећим корацима:

1. Наћи псеудоинверз дијагоналне матрице $D$: За сваки ненула елемент $d_{ii}$ на дијагонали матрице $D$, наћи $d_{ii}^+$ тако да је $d_{ii}^+ = \frac{1}{d_{ii}}$. Ако је $d_{ii} = 0$, онда је $d_{ii}^+ = 0$. Резултат је дијагонална матрица $D^+$.

2. Искористити формулу из тачке а) за ортогоналну дијагонализацију и псеудоинверз: $S^+ = QD^+Q^T$. Заменимо $A$ са $S$, $U$ и $V$ са $Q$, и $A^+$ са $S^+$ у формули из тачке а): $(QDQ^T)^+ = QD^+Q^T$.

Тако добијамо да је псеудоинверз симетричне матрице $S$:

$$S^+ = QD^+Q^T$$
