# Мататематички методи за машинско учење 2023
## Домаћи задатак број 2

<div class="alert alert-block alert-danger">
<b>Име и презиме студента:</b> Никола Петровић

<b>Број индекса:</b> 1466
    
</div>    

<div class="alert alert-block alert-info">
<b>Упутство за израду и предају домаћег задатака: </b> 
    
    1. Пре почетка израде промените име датотеке у 02Domaci_Ime_Prezime. (убаците своје име и презиме) 
    2. Попуните ћелију испод наслова одговарајућим подацима. 
    1. Употреба ћирилице није обавезна за предају домаћег задатка.
    4. За решавање задатака, уколико је потребно, отворите испод текста задатка додатне ћелије за уписивање текстуалног одговора (Markdown) или програмског кода (Code).
    1. Сва израчунавања, уколико је потребно, вршити у Python-у.
    5. Након завршетка израде решења домаћег Notebook документ сачувати у pdf формату и проследити га наставнику. То можете да урадите или кроз Teams или на мејл адресу jovana.dzunic@elfak.ni.ac.rs

</div> 

In [2]:
import numpy as np
import numpy.random as rndm
import matplotlib as mplb
import matplotlib.pyplot as plt

**Задатак 1.** Проверити ортогоналност матрице $A=\begin{bmatrix} I_n&O_{n\times m}\\O_{m\times n}&Q\end{bmatrix},$ где је $Q\in\mathcal{M}_{m\times m}$ ортогонална матрица, $I_n\in\mathcal{M}_{n\times n}$ јединична матрица и $O$ нула-матрице одговарајућих димензија.

(5 поена)

In [2]:
# matrica je ortogonalna ako je njena inverzna matrica jednaka transponovanoj matrici, proizvod matrice i njene transponovane matrice mora biti jedinicnna matrica.
def is_orthogonal(matrix):
    product = np.dot(matrix, matrix.T)
    identity = np.identity(matrix.shape[0])
    return np.allclose(product, identity)

# Definisanje dimenzija
n = 3
m = 2

# Kreiranje matrica I_n, O_nxm, O_mxn, i Q
I_n = np.identity(n)
O_nxm = np.zeros((n, m))
O_mxn = np.zeros((m, n))
Q_orthogonal = np.array([[1, 0], [0, -1]])  # Primer ortogonalne matrice 2x2
Q_not_orthogonal = np.array([[2, 1], [1, 2]])  # Primer matrice koja nije ortogonalna

# Kreiranje matrice A koristeći blok-matricu sa ortogonalnom matricom Q
A_orthogonal = np.block([[I_n, O_nxm], [O_mxn, Q_orthogonal]])

# Kreiranje matrice A koristeći blok-matricu sa matricom Q koja nije ortogonalna
A_not_orthogonal = np.block([[I_n, O_nxm], [O_mxn, Q_not_orthogonal]])

# Provera ortogonalnosti
orthogonal = is_orthogonal(A_orthogonal)
print(f"Matrica A_orthogonal {'je' if orthogonal else 'nije'} ortogonalna.")

orthogonal = is_orthogonal(A_not_orthogonal)
print(f"Matrica A_not_orthogonal {'je' if orthogonal else 'nije'} ortogonalna.")

Matrica A_orthogonal je ortogonalna.
Matrica A_not_orthogonal nije ortogonalna.


<div class="alert alert-block alert-info">
<b> Тачно. Недостаје теоријска анализа у општем случају.
    
2/5 поена </b> 

<b><span style="font-size: 44px; color: purple;">Ispravak</span></b><b>
 додата теоријска анализа у наставку: </b>

Да бисмо проверили ортогоналност матрице A, треба да израчунамо производ $A A^T$. Уколико је овај производ јединична матрица, матрица A је ортогонална.

$A A^T = \begin{bmatrix} I_n&O_{n\times m}\\O_{m\times n}&Q\end{bmatrix} \begin{bmatrix} I_n&O_{n\times m}\\O_{m\times n}&Q^T\end{bmatrix}$

Користећи својства блок матрица, добијамо:

$A A^T = \begin{bmatrix} I_n & O_{n\times m} Q^T \\ Q O_{n\times m} & Q Q^T\end{bmatrix}$

Заменимо нула-матрице и својства јединичне матрице:

$A A^T = \begin{bmatrix} I_n & O_{n\times m} \\ O_{m\times n} & I_m\end{bmatrix}$

Ова матрица је јединична матрица димензија $(n + m) \times (n + m)$, што значи да је матрица A ортогонална у општем случају када је Q ортогонална.

<div class="alert alert-block alert-info">
<b> Тачно. 
    
5/5 поена </b> 

**Задатак 2.** Дописати недостајуће елементе матрица $A,B$ и $C$  тако да је матрица $A$ симетрична, $B$ косо-симетрична и $C$ ортогонална.
	$$A=\begin{bmatrix} 5&3&-1\\&0&\\&2&1\end{bmatrix},\qquad
	B=\begin{bmatrix} &&1\\-1&&\\&1&\end{bmatrix},\qquad
	C=\dfrac{1}{\sqrt2}\begin{bmatrix}1&1\\1& \end{bmatrix}.$$

(5 поена)

<b> Ispravka</b>

In [37]:
# Matrica je simetricna ako je jednaka svojoj transponovanoj matrici
# Matrica je kososimetricna ako je njen negativ jednak njenoj transponovanoj matrici, elementi su simetricni u odnosu na glavnu dijagonalu sa suprotnim znakovima i glavna dijagonala kososimetricne matrice mora biti nula
# Matrica je ortogonalna ako je matrica koja joj je inverzna jednaka transponovanoj matrici, proizvod matrice i njene transponovane matrice mora biti jedinicna matrica

# Inicijalne matrice
A = np.array([[5, 3, -1],
              [np.nan, 0, np.nan],
              [np.nan, 2, 1]])

B = np.array([[np.nan, np.nan, 1],
              [-1, np.nan, np.nan],
              [np.nan, 1, np.nan]])

C = np.array([[1 / np.sqrt(2),1 / np.sqrt(2)],
               [1 / np.sqrt(2), np.nan]],
                 dtype=float)

# Dopunjavanje simetrične matrice A
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        if np.isnan(A[i, j]):
            A[i, j] = A[j, i]

# Dopunjavanje koso-simetrične matrice B
for i in range(B.shape[0]):
    for j in range(B.shape[1]):
        if np.isnan(B[i, j]):
            if i == j:
                B[i, j] = 0
            else:
                B[i, j] = -B[j, i]

# Popunjavanje nedostajućih elemenata za ortogonalnu matricu C
# Potrebno je izračunati vrednost elementa C[1, 1] tako da proizvod C*C.T bude jedinična matrica. 
# Da bismo to postigli, možemo koristiti činjenicu da su kolone ortogonalne matrice međusobno ortogonalne.
C[1, 1] = -C[0, 1]

# Ispis matrica A, B i C
print("A:")
print(A)
# Provera da li je matrica simetricna
if np.allclose(A, A.T):
    print("Matrica A je simetricna.")
else:
    print("Matrica A nije simetricna.")
print("\nB:")
print(B)
if np.allclose(B, -B.T):
    print("Matrica B je kososimetricna.")
else:
    print("Matrica B nije kososimetricna.")

print("\nMatrica C:")
print(C)

# Provera ortogonalnosti matrice C
if np.allclose(C.T @ C, np.identity(C.shape[1])):
    print("Matrica C je ortogonalna.")
else:
    print("Matrica C nije ortogonalna.")


A:
[[ 5.  3. -1.]
 [ 3.  0.  2.]
 [-1.  2.  1.]]
Matrica A je simetricna.

B:
[[ 0.  1.  1.]
 [-1.  0. -1.]
 [-1.  1.  0.]]
Matrica B je kososimetricna.

Matrica C:
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
Matrica C je ortogonalna.


<div class="alert alert-block alert-info">
<b> Скоро тачно. 
    
3/5 поена </b> 
Допуна до матрице ортогоналних колона није добра. То што не могу колоне да се нормирају је други проблем, моја грешка у куцању. Променила сам фактор испред матрице $C$ за тачну поставку.</div> 

<div class="alert alert-block alert-info">
<b> Тачно. 
    
5/5 поена </b> 

**Задатак 3.** Написати програмски код којим се реализује Штрасенов алгоритам множења две матрице. Нека је $n=2^p$ и $A,B\in\mathcal{M}_{n\times n}.$ Уколико је $n_{\min}=2^d,\ d\leq p,$ онда алгоритам израчунава производ $C=AB$ по следећем правилу:
```
    def C=strass(A,B,n,n_min):
        if n<=n_min
            C=AB na klasičan način
        else
            m=n/2
            M1=strass(A[:m,:m]+A[m:,m:],B[:m,:m]+B[m:,m:])
            M2=strass(A[m:,:m]+A[m:,m:],B[:m,:m])
            M3=strass(A[:m,:m],B[:m,m:]-B[m:,m:])
            M4=strass(A[m:,m:],B[m:,:m]-B[:m,:m])
            M5=strass(A[:m,:m]+A[:m,m:],B[m:,m:])
            M6=strass(A[m:,:m]-A[:m,:m],B[:m,:m]+B[:m,m:])
            M7=strass(A[:m,m:]-A[m:,m:],B[m:,:m]+B[m:,m:])
            C[:m,:m]=M1+M4-M5+M7
            C[:m,m:]=M3+M5
            C[m:,:m]=M2+M4
            C[m:,m:]=M1-M2+M3+M6
```

(10 поена)

In [5]:
import time

In [6]:
def strass(A, B, n, n_min):
    if n <= n_min:
        return A @ B  # Klasično množenje matrica
    else:
        m = n // 2
        
        # Podela matrica A i B na četvrtine
        A11, A12, A21, A22 = A[:m, :m], A[:m, m:], A[m:, :m], A[m:, m:]
        B11, B12, B21, B22 = B[:m, :m], B[:m, m:], B[m:, :m], B[m:, m:]

        M1 = strass(A11 + A22, B11 + B22, m, n_min)
        M2 = strass(A21 + A22, B11, m, n_min)
        M3 = strass(A11, B12 - B22, m, n_min)
        M4 = strass(A22, B21 - B11, m, n_min)
        M5 = strass(A11 + A12, B22, m, n_min)
        M6 = strass(A21 - A11, B11 + B12, m, n_min)
        M7 = strass(A12 - A22, B21 + B22, m, n_min)

        C = np.empty((n, n), dtype=A.dtype)
        C[:m, :m] = M1 + M4 - M5 + M7
        C[:m, m:] = M3 + M5
        C[m:, :m] = M2 + M4
        C[m:, m:] = M1 - M2 + M3 + M6

        return C

In [11]:
# Klasično množenje matrica
A = np.random.rand(2048, 2048)
B = np.random.rand(2048, 2048)

# Štrassenov algoritam
n = A.shape[0]
n_min = 64  # Podešavanje granice za prelazak na klasično množenje matrica

start_time = time.time()
C_strass = strass(A, B, n, n_min)
strassen_time = time.time() - start_time
print(f"Vreme izvršavanja za Štrassenov algoritam: {strassen_time:.6f} sekundi\n")

Vreme izvršavanja za Štrassenov algoritam: 1.497885 sekundi



In [12]:
# NumPy @ množenje
start_time = time.time()
C_numpy = A @ B
numpy_time = time.time() - start_time
print(f"Vreme izvršavanja za NumPy množenje (@ operator): {numpy_time:.6f} sekundi\n")

# Poređenje vremena izvršavanja
print(f"Razlika u vremenu izvršavanja (Štrassenov algoritam - NumPy množenje): {strassen_time - numpy_time:.6f} sekundi")
# Matrice ne štampam zbog velicine
np.any(np.round(C_strass-C_numpy,2))

Vreme izvršavanja za NumPy množenje (@ operator): 0.116247 sekundi

Razlika u vremenu izvršavanja (Štrassenov algoritam - NumPy množenje): 1.381638 sekundi


False

<div class="alert alert-block alert-info">
<b> Тачно.
    
10/10 поена </b> 
Проблем са Штрасеновим алгоритмом је рекурзија која направи експлозију у потребној меморији. </div>

**Задатак 4.** Прилагодити претходни алгоритам тако да може да се користи за множење две квадратне матрице произвољног реда. То значи, уколико су матрице непарне димензије допунити их нула врстом и колоном до парне димензије.

(10 поена)

In [13]:
# Potrebno je dopuniti matricu do najblizeg broja stepena dvojke
def dopuni_matricu(A):
    n = A.shape[0]
    dopunjena_velicina = 2 ** int(np.ceil(np.log2(n)))
    if n == dopunjena_velicina:
        return A
    else:
        dopunjena_A = np.zeros((dopunjena_velicina, dopunjena_velicina), dtype=A.dtype)
        dopunjena_A[:n, :n] = A
        return dopunjena_A

def strassen(A, B, n, n_min):
    if n <= n_min:
        return A @ B
    else:
        m = n // 2

        A11, A12, A21, A22 = A[:m, :m], A[:m, m:], A[m:, :m], A[m:, m:]
        B11, B12, B21, B22 = B[:m, :m], B[:m, m:], B[m:, :m], B[m:, m:]

        M1 = strassen(A11 + A22, B11 + B22, m, n_min)
        M2 = strassen(A21 + A22, B11, m, n_min)
        M3 = strassen(A11, B12 - B22, m, n_min)
        M4 = strassen(A22, B21 - B11, m, n_min)
        M5 = strassen(A11 + A12, B22, m, n_min)
        M6 = strassen(A21 - A11, B11 + B12, m, n_min)
        M7 = strassen(A12 - A22, B21 + B22, m, n_min)

        C = np.empty((n, n), dtype=A.dtype)
        C[:m, :m] = M1 + M4 - M5 + M7
        C[:m, m:] = M3 + M5
        C[m:, :m] = M2 + M4
        C[m:, m:] = M1 - M2 + M3 + M6

        return C

# Generiši slučajne matrice
A = np.random.rand(2049, 2049)
B = np.random.rand(2049, 2049)

# Dopuni matrice nulama
dopunjena_A = dopuni_matricu(A)
dopunjena_B = dopuni_matricu(B)

# Strassenov algoritam
n = dopunjena_A.shape[0]
n_min = 64

start_time = time.time()
dopunjena_C_strass = strassen(dopunjena_A, dopunjena_B, n, n_min)
strassen_vreme = time.time() - start_time
print(f"Vreme izvršavanja za Strassenov algoritam: {strassen_vreme:.6f} sekundi\n")

# Ukloni dopunu
C_strass = dopunjena_C_strass[:A.shape[0], :A.shape[1]]

# NumPy @ množenje
start_time = time.time()
C_numpy = A @ B
numpy_vreme = time.time() - start_time
print(f"Vreme izvršavanja za NumPy množenje (@ operator): {numpy_vreme:.6f} sekundi\n")

# Uporedi vremena izvršavanja
print(f"Razlika u vremenu izvršavanja (Štrassenov algoritam - NumPy množenje): {strassen_vreme - numpy_vreme:.6f} sekundi")
# Matrice ne štampam zbog velicine

Vreme izvršavanja za Strassenov algoritam: 10.745615 sekundi

Vreme izvršavanja za NumPy množenje (@ operator): 0.125196 sekundi

Razlika u vremenu izvršavanja (Štrassenov algoritam - NumPy množenje): 10.620418 sekundi


<div class="alert alert-block alert-info">
<b> Тачно.
    
10/10 поена </b> </div>

**Задатак 5.** За примере 2.7.3 и 2.7.4 из књиге, на конкретним примерима матрица и вектора малих димезија проверити формуле о сечењима одговарајућих тензорских производа.

(10 поена)

<b> Ispravak </b>

In [28]:
# definisanje matrice A dimenzije 2x2
A_matrica = np.array([[1, 2], [3, 4]])

# definisanje vektora vektor dimenzije 2x1
vektor = np.array([5, 6])

# definisanje matrice B dimenzije 2x3
B_matrica = np.array([[7, 8, 9], [10, 11, 12]])

# izračunavanje tenzorskog proizvoda A x vektor
Avektor_tenzor = np.tensordot(A_matrica, vektor, axes=0)
print("Tenzorski proizvod A x vektor:")
print(Avektor_tenzor)
print("\nDimenzije tenzorskog proizvoda A x vektor:")
print(Avektor_tenzor.shape)

print("\nHorizontalno sečenje tenzorskog proizvoda A x vektor:")
print(Avektor_tenzor[1,:,0])

print("\nVertikalno sečenje tenzorskog proizvoda A x vektor:")
print(Avektor_tenzor[:,1,0])

print("\nBočno sečenje tenzorskog proizvoda A x vektor:")
print(Avektor_tenzor[0,1,:])  


Tenzorski proizvod A x vektor:
[[[ 5  6]
  [10 12]]

 [[15 18]
  [20 24]]]

Dimenzije tenzorskog proizvoda A x vektor:
(2, 2, 2)

Horizontalno sečenje tenzorskog proizvoda A x vektor:
[15 20]

Vertikalno sečenje tenzorskog proizvoda A x vektor:
[10 20]

Bočno sečenje tenzorskog proizvoda A x vektor:
[10 12]


In [29]:
# izračunavanje tenzorskog proizvoda vektor x A
vektorA_tenzor = np.tensordot(vektor, A_matrica, axes=0)
print("\nTenzorski proizvod vektor x A:")
print(vektorA_tenzor)
print("\nDimenzije tenzorskog proizvoda vektor x A:")
print(vektorA_tenzor.shape)

print("\nHorizontalno sečenje tenzorskog proizvoda vektor x A:")
print(vektorA_tenzor[0,:,0])  # prvi elementi po dimenzijama 0 i 2

print("\nVertikalno sečenje tenzorskog proizvoda vektor x A:")
print(vektorA_tenzor[:,0,0])  # prvi elementi po dimenzijama 0 i 1

print("\nBocno sečenje tenzorskog proizvoda vektor x A:")
print(vektorA_tenzor[0,0,:])  # prvi elementi po dimenzijama 0 i 1


Tenzorski proizvod vektor x A:
[[[ 5 10]
  [15 20]]

 [[ 6 12]
  [18 24]]]

Dimenzije tenzorskog proizvoda vektor x A:
(2, 2, 2)

Horizontalno sečenje tenzorskog proizvoda vektor x A:
[ 5 15]

Vertikalno sečenje tenzorskog proizvoda vektor x A:
[5 6]

Bocno sečenje tenzorskog proizvoda vektor x A:
[ 5 10]


In [30]:
# izračunavanje tenzorskog proizvoda A x B
AB_tenzor = np.tensordot(A_matrica, B_matrica, axes=0)
print("\nTenzorski proizvod A x B:")
print(AB_tenzor)
print("\nDimenzije tenzorskog proizvoda A x B:")
print(AB_tenzor.shape)

print("\nHorizontalno sečenje tenzorskog proizvoda A x B:")
print(AB_tenzor[0,:,1]) 

print("\nVertikalno sečenje tenzorskog proizvoda A x B:")
print(AB_tenzor[:,1,1]) 

print("\nBocno sečenje tenzorskog proizvoda A x B:")
print(AB_tenzor[0,1,:]) 


Tenzorski proizvod A x B:
[[[[ 7  8  9]
   [10 11 12]]

  [[14 16 18]
   [20 22 24]]]


 [[[21 24 27]
   [30 33 36]]

  [[28 32 36]
   [40 44 48]]]]

Dimenzije tenzorskog proizvoda A x B:
(2, 2, 2, 3)

Horizontalno sečenje tenzorskog proizvoda A x B:
[[10 11 12]
 [20 22 24]]

Vertikalno sečenje tenzorskog proizvoda A x B:
[[20 22 24]
 [40 44 48]]

Bocno sečenje tenzorskog proizvoda A x B:
[[14 16 18]
 [20 22 24]]


<div class="alert alert-block alert-info">
<b> Требало је да проверите сечења резултата ових тензорских производа.
    
3/10 поена </b> 
</div>

<div class="alert alert-block alert-info">
<b> Тачно. 
    
10/10 поена </b> 

<div class="alert alert-block alert-info">
<b> Укупно
    
40/40 поена </b> 
</div>