# Мататематички методи за машинско учење 2023
## Домаћи задатак број 4

<div class="alert alert-block alert-danger">
<b>Име и презиме студента:</b> Никола Петровић

<b>Број индекса:</b> 1466
    
</div>    

<div class="alert alert-block alert-info">
<b>Упутство за израду и предају домаћег задатака: </b> 
    
    1. Пре почетка израде промените име датотеке у 04Domaci_Ime_Prezime. (убаците своје име и презиме) 
    2. Попуните ћелију испод наслова одговарајућим подацима. 
    1. Употреба ћирилице није обавезна за предају домаћег задатка.
    4. За решавање задатака, уколико је потребно, отворите испод текста задатка додатне ћелије за уписивање текстуалног одговора (Markdown) или програмског кода (Code).
    1. Сва израчунавања, уколико је потребно, вршити у Python-у.
    5. Након завршетка израде решења домаћег Notebook документ сачувати у pdf формату и проследити га наставнику. То можете да урадите или кроз Teams или на мејл адресу jovana.dzunic@elfak.ni.ac.rs

</div> 

In [15]:
import numpy as np
import numpy.random as rndm
import matplotlib as mplb
import matplotlib.pyplot as plt

**Задатак 1.** а) Неким од критеријума за позитивну дефинитност проверити да ли је матрица $A$ позитивно дефинитна.

(5 поена)

In [3]:
# Definisanje matrice A
A = rndm.uniform(-2, 3, (50, 50))
A = np.tril(A) + (np.tril(A)).T

# Izračunavanje sopstvenih vrednosti matrice A
sopstvene_vrednosti = np.linalg.eigvalsh<div class="alert alert-block alert-info">

# Provera da li su sve sopstvene vrednosti strogo pozitivne
pozitivno_definitna = np.all(sopstvene_vrednosti > 0)

print("Matrica A je pozitivno definitna:", pozitivno_definitna)

Matrica A je pozitivno definitna: False


<div class="alert alert-block alert-info">
<b> Тачно 
    
5/5 поена</b> </div>

б) Какве су дефинитности матрице $AA^T$ и $A^TA$ ако је $A\in\mathcal{M}_{m\times n}$ произвољна матрица пуног ранга колона?

(5 поена)

In [5]:
# Postavljanje dimenzija matrice A (m > n za pun rang kolona)
m, n = 6, 4

# Generisanje proizvoljne matrice A dimenzija m x n
A = np.random.rand(m, n)

# Provera da li je rang matrice A jednak n (puni rang kolona)
rang = np.linalg.matrix_rank(A)
print("Rang matrice A:", rang)

# Izračunavanje matrica AA^T i A^TA
AAt = A @ A.T
AtA = A.T @ A

# Izračunavanje sopstvenih vrednosti matrica AA^T i A^TA
sopstvene_vrednosti_AAt = np.linalg.eigvals(AAt)
sopstvene_vrednosti_AtA = np.linalg.eigvals(AtA)

# Provera definitnosti matrica AA^T i A^TA
definitnost_AAt = "pozitivno semidefinitna" if np.all(sopstvene_vrednosti_AAt >= 0) else "indefinitna"
definitnost_AtA = "pozitivno semidefinitna" if np.all(sopstvene_vrednosti_AtA >= 0) else "indefinitna"

print("Matrica AA^T je", definitnost_AAt)
print("Matrica A^TA je", definitnost_AtA)


Rang matrice A: 4
Matrica AA^T je pozitivno semidefinitna
Matrica A^TA je pozitivno semidefinitna


<div class="alert alert-block alert-info">
<b> Није добро. Погледајте поново дефиниције позитивне дефинитности и позитивне семи дефинитности. Грамове матрице не могу да буду индефинитне.
    
2/5 поена</b> </div>

<b><span style="font-size: 44px; color: purple;">Ispravak</span></b>

Према теореми 2. и примеру 3. из радне свеске, можемо закључити следеће:

Задатак нам каже да је $A$ произвољна матрица пуног ранга колона, дакле, ранг матрице $A$ је $n$.

Прво, размотримо матрицу $A^TA$. Знамо да је ова матрица Грамова матрица, што значи да је она симетрична и има искључиво реалне сопствене вредности. Пошто је $A$ матрица пуног ранга колона, $A^TA$ је регуларна, тј. инвертибилна, и не може имати $0$ у свом спектру. Ова Грамова матрица има све позитивне сопствене вредности, што значи да је она <b>позитивно дефинитна</b>.

Сада, размотримо матрицу $AA^T$. Ова матрица је такође симетрична, пошто је $(AA^T)^T = A^{TT}A^T = AA^T$. Да бисмо испитали дефинитност $AA^T$, размотримо произвољни вектор $x \in \mathbb{R}^m$ и израз $x^T(AA^T)x$. Можемо га преписати као $(x^TAA^T)x = (A^Tx)^T(A^Tx) = |A^Tx|^2$. Знамо да је $A$ матрица пуног ранга колона, тако да је $A^Tx \neq 0$ за све $x \neq 0$. То значи да је $|A^Tx|^2 > 0$ за све $x \neq 0$. Према томе, матрица $AA^T$ је <b>позитивно дефинитна</b>.

У закључку, матрице $AA^T$ и $A^TA$ су обе позитивно дефинитне када је $A$ матрица пуног ранга колона.

<div class="alert alert-block alert-info">
<b> Није добро. $A\in\mathcal{M}_{m\times n}$ је пуног ранга колона, због тога је $m\geq n.$ Матрица $AA^T$ је ранга $n$ $m\times m.$ Не може увек да буде дефинитна јер би то значило да је увек регуларна, чак и у случају $m> n.$
    
3/5 поена</b> </div>

**Задатак 2.** а) Која од следећих матрица је косо-симетрична?
$$A=\begin{bmatrix}1&-3&2\\3&-5&4\\-2&-4&2\end{bmatrix},\qquad 
B=\begin{bmatrix}0&-3&2\\3&0&4\\-2&-4&0\end{bmatrix}.$$

(5 поена)

In [6]:
A = np.array([[1, -3, 2],
              [3, -5, 4],
              [-2, -4, 2]])

B = np.array([[0, -3, 2],
              [3, 0, 4],
              [-2, -4, 0]])

# Provera da li je matrica A kososimetrična
kososimetrična_A = np.all(A.T == -A)
print("Matrica A je kososimetrična:" , kososimetrična_A)

# Provera da li je matrica B kososimetrična
kososimetrična_B = np.all(B.T == -B)
print("Matrica B je kososimetrična:" , kososimetrična_B)

Matrica A je kososimetrična: False
Matrica B je kososimetrična: True


<div class="alert alert-block alert-info">
<b> Тачно 
    
5/5 поена</b> </div>

б) Ако је $A$ косо-симетрична матрица чему је једнако $A^TA^{-1}?$

(5 поена)

<b><span style="font-size: 44px; color: purple;">Ispravak 4.2.б.</span></b>


За косо-симетричну матрицу $A$, важи следећа веза: $A = -A^T$. Желимо да установимо чему је једнако $A^TA^{-1}$, али пре тога треба да утврдимо када инверз постоји.

Косо-симетричне матрице квадратне су матрице чији су елементи такви да је $a_{ij} = -a_{ji}$. То значи да су дијагонални елементи нуле, јер $a_{ii} = -a_{ii} \Rightarrow a_{ii} = 0$.

Сада, треба да размотримо два случаја:

1. Ако је $n$, димензија матрице, паран:
У овом случају, косо-симетрична матрица може да буде регуларна (има инверз). На пример, за димензију $2\times 2$:

$$
A = \begin{bmatrix}
0 & a \\
-a & 0
\end{bmatrix}
$$

Детерминанта матрице $A$ је:

$$
\det(A) = (0)(0) - (a)(-a) = a^2
$$

Када $a \neq 0$, детерминанта је различит од нуле и инверз постоји.

2. Ако је $n$, димензија матрице, непаран:
У овом случају, косо-симетрична матрица не може да буде регуларна. Ово је зато што детерминанта матрице увек износи нулу за непарне димензије.

Сада, када знамо када инверз постоји, можемо да израчунамо $A^TA^{-1}$:

$$
A^TA^{-1} = (-A)A^{-1} = -AA^{-1} = -I
$$

Тако да је $A^TA^{-1} = -I$, где је $I$ јединична матрица, али ово важи само када је димензија матрице $A$ парна и инверз постоји. У случају непарних димензија, инверз не постоји и производ $A^TA^{-1}$ није дефинисан.


<div class="alert alert-block alert-info">
<b> Косо-симетричне матрице некада јесу регуларне, некада нису. То зависи и од њихове димензије. Питање је када инверз постоји шта се дешава са производом $A^TA^{-1}?$ 
    
0/5 поена</b> Видите наредни пример.</div>

<div class="alert alert-block alert-info">
<b> Тачно
    
5/5 поена</b> </div>

In [11]:
pom=rndm.rand(6,6)
L=np.tril(pom)
Aks=L-L.T
np.round(Aks,2)
np.round(Aks.T@np.linalg.inv(Aks),2)

array([[ 0.  , -0.3 , -0.27, -0.3 , -0.4 , -0.15],
       [ 0.3 ,  0.  , -0.45, -0.59, -0.51, -0.28],
       [ 0.27,  0.45,  0.  , -0.55, -0.8 , -0.19],
       [ 0.3 ,  0.59,  0.55,  0.  , -0.69, -0.3 ],
       [ 0.4 ,  0.51,  0.8 ,  0.69,  0.  , -0.11],
       [ 0.15,  0.28,  0.19,  0.3 ,  0.11,  0.  ]])

In [12]:
np.round(Aks.T@np.linalg.inv(Aks),2)

array([[-1., -0., -0.,  0., -0.,  0.],
       [-0., -1.,  0., -0.,  0.,  0.],
       [-0.,  0., -1., -0.,  0., -0.],
       [-0., -0.,  0., -1.,  0., -0.],
       [-0.,  0.,  0., -0., -1., -0.],
       [-0., -0.,  0., -0.,  0., -1.]])

<div class="alert alert-block alert-info"> Ово треба показати у општем случају. </div>

**Задатак 3.** а) Показати да се свака матрица може представити као збир једне симетричне и једне косо-симетричне матрице.


(5 поена)

а) Да бисмо показали да се свака матрица може представити као збир једне симетричне и једне косо-симетричне матрице, можемо користити следећи разломак матрице:

Симетрична матрица: $S = \frac{1}{2}(A + A^T)$
Косо-симетрична матрица: $K = \frac{1}{2}(A - A^T)$

Тако да је збир ове две матрице:

$$A = S + K = \frac{1}{2}(A + A^T) + \frac{1}{2}(A - A^T) = \frac{1}{2}(A + A) = A$$

Дакле, свака матрица може да се представи као збор једне симетричне и једне косо-симетричне матрице.

Следећи код демонстрира ово тврђење:

<div class="alert alert-block alert-info">
<b> Тачно 
    
5/5 поена</b> </div>

In [13]:
def decompose_matrix(A):
    A_T = A.T
    S = 0.5 * (A + A_T)
    K = 0.5 * (A - A_T)
    return S, K

# Primer matrice
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Dekompozicija matrice
S, K = decompose_matrix(A)

print("Simetrična matrica S:\n", S)
print("Koso-simetrična matrica K:\n", K)
print("A = S + K:\n", S + K)


Simetrična matrica S:
 [[1. 3. 5.]
 [3. 5. 7.]
 [5. 7. 9.]]
Koso-simetrična matrica K:
 [[ 0. -1. -2.]
 [ 1.  0. -1.]
 [ 2.  1.  0.]]
A = S + K:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


б) Проверити позитивну дефинитност несиметричне квадратне матрице $A$ неким од критеријума.

(5 поена)

<b><span style="font-size: 44px; color: purple;">Ispravak</span></b>

In [7]:
import numpy as np

def cholesky_decomposition(A):
    try:
        L = np.linalg.cholesky(A)
        return True
    except np.linalg.LinAlgError:
        return False

A = np.random.uniform(-2, 3, size=(50, 50))

# Formiranje simetricne matrice A^TA
A_sym = A.T @ A

# Provera pozitivne definitnosti koristeci coleski dekompoziciju
# Ako je dekompozicija uspesna, matrica je opozitivno definitna, u suprotnom nije pozitivno definitna
if cholesky_decomposition(A_sym):
    print("Matrica A je pozitivno definitna.")
else:
    print("Matrica A nije pozitivno definitna.")


Matrica A je pozitivno definitna.


<div class="alert alert-block alert-info">
<b> Није добро. Матрица A_sym није добро изабрана да дели дефинитност матрице A.
    
0/5 поена</b> </div>

**Задатак 4.** За матрицу $A=B^TB$ одредити матрицу пројекције на $\mathcal{R}(A)$ у односу на скаларни производ $\langle\cdot,\cdot\rangle_C.$

(10 поена)

In [16]:
# Generisanje matrice B
B=rndm.normal(-1,2,(25,5))
B=B@np.array([[1,0,1,-1,2],[0,1,1,1,-1],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0]])

# Izračunavanje matrice A
A = B.T @ B
print("Matrica A:\n", A)

# Rang matrice A
rank_A = np.linalg.matrix_rank(A)
print("Rang matrice A:", rank_A)

# Generisanje matrice C
C = rndm.rand(5, 5)
C = np.tril(C) + (np.tril(C)).T + 5 * np.eye(5, 5)
print("Matrica C:\n", C)

# Rang matrice C
rank_C = np.linalg.matrix_rank(C)
print("Rang matrice C:", rank_C)

# Izračunavanje matrice projekcije P
CA_inv = np.linalg.inv(C @ A)  # Inverz matrice (C * A)
C_inv = np.linalg.inv(C)       # Inverz matrice C

P = A @ CA_inv @ C_inv          # Matrica projekcije P
print("Matrica projekcije P:\n", P)


Matrica A:
 [[ 128.05317817   84.2143075   212.26748567  -43.83887068  171.89204885]
 [  84.2143075   115.65569733  199.87000482   31.44138983   52.77291766]
 [ 212.26748567  199.87000482  412.13749049  -12.39748084  224.66496651]
 [ -43.83887068   31.44138983  -12.39748084   75.28026051 -119.11913119]
 [ 171.89204885   52.77291766  224.66496651 -119.11913119  291.01118004]]
Rang matrice A: 2
Matrica C:
 [[5.86020939 0.58698423 0.93656483 0.76946829 0.7616133 ]
 [0.58698423 6.4061262  0.56706125 0.51117943 0.4421157 ]
 [0.93656483 0.56706125 5.82959252 0.79047302 0.0149325 ]
 [0.76946829 0.51117943 0.79047302 5.77651563 0.14816868]
 [0.7616133  0.4421157  0.0149325  0.14816868 6.06575063]]
Rang matrice C: 5


LinAlgError: Singular matrix

<div class="alert alert-block alert-info">
<b> Није добро. Исти проблем око матрице пројекције као и у претходном домаћем. Сада још морате да рачунате пројекцију у односу на уопштени скаларни производ, тј. да пронађете базу $C-$ортонормираних вектора.
    
0/10 поена</b> </div>

<b><span style="font-size: 44px; color: purple;">Ispravak</span></b>

$P = C (C^T A C)^{-1} C^T$

In [18]:
import numpy as np
import numpy.random as rndm

# Generisanje matrice B
B = rndm.normal(-1, 2, (25, 5))
B = B @ np.array([[1, 0, 1, -1, 2], [0, 1, 1, 1, -1], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]])

# Izračunavanje matrice A
A = B.T @ B
print("Matrica A:\n", A)

# Rang matrice A
rank_A = np.linalg.matrix_rank(A)
print("Rang matrice A:", rank_A)

# Generisanje matrice C i njeno ortogonalizovanje
C = rndm.rand(5, 5)
C = np.tril(C) + (np.tril(C)).T + 5 * np.eye(5, 5)
Q, R = np.linalg.qr(C)   # QR faktorizacija matrice C
C_ortho = Q             # Nova matrica sa ortonormiranim kolonama
print("Baza ortonormiranih vektora C_ortho:\n", C_ortho)

# Izračunavanje matrice projekcije P
CA_inv = np.linalg.inv(C_ortho @ A @ C_ortho.T)  # Inverz matrice C*A*C^T
C_inv = np.linalg.inv(C_ortho)                 # Inverz matrice C

P = C_ortho @ CA_inv @ C_inv          # Matrica projekcije P
print("Matrica projekcije P:\n", P)


Matrica A:
 [[ 114.69898616   35.55123884  150.250225    -79.14774733  193.84673349]
 [  35.55123884  142.82442336  178.3756622   107.27318452  -71.72194568]
 [ 150.250225    178.3756622   328.6258872    28.12543719  122.12478781]
 [ -79.14774733  107.27318452   28.12543719  186.42093185 -265.56867917]
 [ 193.84673349  -71.72194568  122.12478781 -265.56867917  459.41541266]]
Rang matrice A: 2
Baza ortonormiranih vektora C_ortho:
 [[-0.98670147  0.04602924  0.15033086  0.04014824  0.00950143]
 [-0.03332213 -0.98626472  0.0830988   0.03257181 -0.13492663]
 [-0.14583217 -0.05726674 -0.9710901   0.14351448 -0.10881682]
 [-0.06207843 -0.03588784 -0.12999865 -0.98807057 -0.04092953]
 [-0.0137513  -0.14351232 -0.1028571  -0.02115027  0.98396555]]
Matrica projekcije P:
 [[-3.00353912e+13  2.54517860e+13 -1.68180454e+13  2.98643870e+12
   2.36950995e+13]
 [ 3.56701427e+12  9.54592229e+12 -1.72167196e+13  1.88159566e+13
   1.66036572e+13]
 [ 2.82939712e+12 -2.23565162e+13  1.53312182e+13 -5.7659

<div class="alert alert-block alert-info">
<b> Није добро. Матрица CA_inv не постоји јер је А ранга 2. То што пајтон рачуна нешто је само резултат нагомилавања грешака заокруживања.
    
0/10 поена</b> </div>

**Задатак 5.** Прилагодити метод коњугованих градијената за решење матричне једначине $AX=B.$


(10 поена)

In [8]:
# Kod je ispravljen u nastavku
def konjugovani_gradijenti(A, b, x0, tolerancija=1e-10, maks_iteracija=None):
    m, n = A.shape
    
    # Inicijalizacija rešenja (vrednosti x)
    x = np.array(x0)
    
    # Izračunavanje reziduala
    r = b - A @ x
    
    # Kvadrat norme reziduala
    nr2 = np.inner(r, r)
    
    # Postavljanje vektora pretrage na rezidual
    v = np.copy(r)
    
    k = 0# Brojač iteracija

    # Glavna iteracija metode konjugovanih gradijenata
    while (k < n) and not(np.array_equal(v, 0)) and (nr2 > tolerancija):
        Av = A @ v
        t = nr2 / np.inner(v, Av)
        x = x + t * v
        r = r - t * Av
        c = nr2
        nr2 = np.inner(r, r)
        if nr2 > tolerancija:
            s = nr2 / c
            v = r + s * v
        k += 1
    
    return x

def resi_AX_B(A, B, x0, tolerancija=1e-10, maks_iteracija=None):
    # Inicijalizacija matrice rešenja X
    X = np.zeros_like(B)

    # Primena metode konjugovanih gradijenata na svaku kolonu matrice B
    for i in range(B.shape[1]):
        X[:, i] = konjugovani_gradijenti(A, B[:, i], x0, tolerancija, maks_iteracija)

    return X

# Testiranje funkcije resi_AX_B
A = np.array([[10., 1, 2, 3, 4],
              [1, 9, -1, 2, -3],
              [2, -1, 7, 3, -5],
              [3, 2, 3, 12, -1],
              [4, -3, -5, -1, 15]])

B = np.array([[12., -27, 14, -17, 12],
              [15, 30, -9, 20, -13],
              [8, 15, 25, 33, -5],
              [23, 12, -3, 12, -1],
              [14, -3, -5, -1, 15]])

n, _ = A.shape
x0 = np.zeros(n)

X = resi_AX_B(A, B, x0)
print("Rešenje X:")
print(X)


print("Provera: A @ X =")
print(A @ X)
print("B =")
print(B)

print(np.linalg.solve(A,B))

Rešenje X:
[[-1.62448284 -8.62217084  0.35349233 -8.75529326  2.10391823]
 [ 3.20807982  8.10890728  0.25809199  8.13494768 -2.24701874]
 [ 4.06424921 11.24853979  5.01916525 15.26886104 -2.2955707 ]
 [ 1.058165   -0.38768557 -1.53662692 -1.24239474  0.27597956]
 [ 3.43343879  7.44469457  1.19463373  8.90186177 -0.7572402 ]]
Provera: A @ X =
[[ 12. -27.  14. -17.  12.]
 [ 15.  30.  -9.  20. -13.]
 [  8.  15.  25.  33.  -5.]
 [ 23.  12.  -3.  12.  -1.]
 [ 14.  -3.  -5.  -1.  15.]]
B =
[[ 12. -27.  14. -17.  12.]
 [ 15.  30.  -9.  20. -13.]
 [  8.  15.  25.  33.  -5.]
 [ 23.  12.  -3.  12.  -1.]
 [ 14.  -3.  -5.  -1.  15.]]
[[-1.62448284 -8.62217084  0.35349233 -8.75529326  2.10391823]
 [ 3.20807982  8.10890728  0.25809199  8.13494768 -2.24701874]
 [ 4.06424921 11.24853979  5.01916525 15.26886104 -2.2955707 ]
 [ 1.058165   -0.38768557 -1.53662692 -1.24239474  0.27597956]
 [ 3.43343879  7.44469457  1.19463373  8.90186177 -0.7572402 ]]


<div class="alert alert-block alert-info">
<b> Не решава све системе одједном већ секвенцијално један по један. 
    
5/10 поена</b> Да би све операције радиле како очекујемо увек убаците једну децималну тачку у неки елемент матрице којом радите. У супротном Python хоће да бродкастује резултате тако да буду поново целобројног типа.
    </div>

<b><span style="font-size: 44px; color: purple;">Ispravak</span></b>

In [12]:
def konjugovani_gradijenti(A, B, x0, tolerancija=1e-10, maks_iteracija=None):
    # Inicijalizacija rešenja (vrednosti x)
    x = np.array(x0)
    
    # Izračunavanje reziduala
    R = B - A @ x
    
    # Kvadrat norme reziduala
    NR2 = np.sum(R ** 2)#--------izmena

    # Postavljanje vektora pretrage na rezidual
    V = np.copy(R)
    
    k = 0  # Brojač iteracija

    # Glavna iteracija metode konjugovanih gradijenata
    while (k < A.shape[0]) and not np.allclose(V, 0) and (NR2 > tolerancija):#----------izmena
        AV = A @ V
        T = NR2 / np.sum(V * AV)
        x = x + T * V
        R = R - T * AV
        C = NR2
        NR2 = np.sum(R ** 2)
        if NR2 > tolerancija:
            S = NR2 / C
            V = R + S * V
        k += 1
    
    return x

def resi_AX_B(A, B, x0, tolerancija=1e-10, maks_iteracija=None):
    # Primena metode konjugovanih gradijenata na matricu A i matricu B
    X = konjugovani_gradijenti(A, B, x0, tolerancija, maks_iteracija)# jedan poziv
    return X

# Testiranje funkcije resi_AX_B
A = np.array([[10., 1, 2, 3, 4],
              [1, 9, -1, 2, -3],
              [2, -1, 7, 3, -5],
              [3, 2, 3, 12, -1],
              [4, -3, -5, -1, 15]])

B = np.array([[12., -27, 14, -17, 12],
              [15, 30, -9, 20, -13],
              [8, 15, 25, 33, -5],
              [23, 12, -3, 12, -1],
              [14, -3, -5, -1, 15]])

n, _ = A.shape
x0 = np.zeros(n)

X = resi_AX_B(A, B, x0)
print("Rešenje X:")
print(X)

print("Provera: A @ X =")
print(A @ X)
print("B =")
print(B)

print(np.linalg.solve(A,B))


Rešenje X:
[[-1.62448284 -8.62217084  0.35349233 -8.75529326  2.10391823]
 [ 3.20807982  8.10890728  0.25809199  8.13494768 -2.24701874]
 [ 4.06424921 11.24853979  5.01916525 15.26886104 -2.2955707 ]
 [ 1.058165   -0.38768557 -1.53662692 -1.24239474  0.27597956]
 [ 3.43343879  7.44469457  1.19463373  8.90186177 -0.7572402 ]]
Provera: A @ X =
[[ 12. -27.  14. -17.  12.]
 [ 15.  30.  -9.  20. -13.]
 [  8.  15.  25.  33.  -5.]
 [ 23.  12.  -3.  12.  -1.]
 [ 14.  -3.  -5.  -1.  15.]]
B =
[[ 12. -27.  14. -17.  12.]
 [ 15.  30.  -9.  20. -13.]
 [  8.  15.  25.  33.  -5.]
 [ 23.  12.  -3.  12.  -1.]
 [ 14.  -3.  -5.  -1.  15.]]
[[-1.62448284 -8.62217084  0.35349233 -8.75529326  2.10391823]
 [ 3.20807982  8.10890728  0.25809199  8.13494768 -2.24701874]
 [ 4.06424921 11.24853979  5.01916525 15.26886104 -2.2955707 ]
 [ 1.058165   -0.38768557 -1.53662692 -1.24239474  0.27597956]
 [ 3.43343879  7.44469457  1.19463373  8.90186177 -0.7572402 ]]


<div class="alert alert-block alert-info">
<b> Тачно 
    
10/10 поена</b> Треба предвидети да матрица $B$ не мора да буде квадратна, али то није кључно.
    </div>

<div class="alert alert-block alert-info">
<b> Укупно 40/50 поена</b> </div> 