# Блок матрице

Садржај:
1. [Операције са блок матрицама](#Операције-са-блок-матрицама)
1. [Кронекеров производ матрица](#Кронекеров-производ-матрица)
1. [Кронекерова сума матрица](#Кронекерова-сума-матрица)
1. [Катри-Рао производ матрица](#Катри-Рао-производ-матрица)

In [1]:
import numpy as np

Једна од најзначајнијих операција у алгебри матрица је могућност растављања матрице на мање делове и да се притом задржи облик израза за стандардне операције. Саставни делови матрице представљају њене подматрице и зовемо их блокови, а поступак растављања на подматрице је разбијање на блокове.

На почетку матрице - правоугаоне шеме бројева смо посматрали као скупове погодно изабраних вектора: вектора-колона и вектора-врста. Тиме смо направили увод у груписање података унутар матрица. Веома често груписање података по другачијем критеријуму погодује разумевању и решавању реалних проблема. У том контексту матрице можемо посматрати као колекције погодно изабраних матрица.

Матрица $M$ је разбијена на блокове ако су њени елементи једном линијом или мрежом хоризонталних линија и вертикалних линија подељени на правоугаоне подматрице. 
За матрицу $M\in\mathcal{M}_{m\times n}$ када је подељена у блокове дељењем редова у $\mu$ непразних подскупова и дељењем њених колона у $\nu$ непразних подскупова, онда се она може записати на следећи начин:
$$
M = \left[\begin{array}{ccc|ccc|c|ccc}
a_{11}&\dots&a_{1n_1}&a_{1\,n_1+1}&\dots&a_{1n_2}&\dots&a_{1\,n_{\nu-1}+1}&\dots&a_{1n_{\nu}}\\
\vdots& &\vdots&\vdots& &\vdots& &\vdots& &\vdots\\
a_{m_11}&\dots&a_{m_1n_1}&a_{m_1\,n_1+1}&\dots&a_{m_1n_2}&\dots&a_{m_1\,n_{\nu-1}+1}&\dots&a_{m_1n_{\nu}}\\\hline
a_{m_1+1\,1}&\dots&a_{m_1+1\,n_1}&a_{m_1+1\,\,n_1+1}&\dots&a_{m_1+1\,n_2}&\dots&a_{m_1+1\,\,n_{\nu-1}+1}&\dots&a_{m_1+1\,n_{\nu}}\\
\vdots& &\vdots&\vdots& &\vdots& &\vdots& &\vdots\\
a_{m_21}&\dots&a_{m_2n_1}&a_{m_2\,n_1+1}&\dots&a_{m_2n_2}&\dots&a_{m_2\,n_{\nu-1}+1}&\dots&a_{m_2n_{\nu}}\\\hline
\vdots& &\vdots&\vdots& &\vdots& &\vdots& &\vdots\\\hline
a_{m_{\mu-1}+1\,1}&\dots&a_{m_{\mu-1}+1\,n_1}&a_{m_{\mu-1}+1\,n_1+1}&\dots&a_{m_{\mu-1}+1\,n_2}&\dots&a_{m_{\mu-1}+1\,\,n_{\nu-1}+1}&\dots&a_{m_{\mu-1}+1\,n_{\nu}}\\
\vdots& &\vdots&\vdots& &\vdots& &\vdots& &\vdots\\
a_{m_{\mu}1}&\dots&a_{m_{\mu}n_1}&a_{m_{\mu}\,n_1+1}&\dots&a_{m_{\mu}n_2}&\dots&a_{m_{\mu}\,n_{\nu-1}+1}&\dots&a_{m_{\mu}n_{\nu}}
\end{array}\right]
=\begin{bmatrix}
A_{11} & A_{12} & \dots &A_{1\nu}\\
A_{21} & A_{22} & \dots &A_{2\nu}\\
\vdots & \vdots & \ddots & \vdots\\
A_{\mu1} & A_{\mu2} & \dots &A_{\mu \nu}
\end{bmatrix},
$$
где су $A_{ij},$ $i \in\{1,2,\dots, \mu\}$, $j \in\{1,2,\dots, \nu\}$ блокови матрице $A.$ Добијена блок матрица је блоковске димензије $\mu \times \nu$  чији су елементи блокови $A_{ij}$ појединачних димензија $m_i\times n_j$ и важи $m_1+m_2+\dots+m_{\mu}=m,$ $n_1+n_2+\dots+n_{\nu}=n.$ Подматрице дуж једне блоковске колоне имају међусобно једнак број колона. Такође, подматрице дуж исте блоковске врсте имају једнак број врста. 

Подматрице $A_{ii},$ где је $1\leq i \leq\min\{ \mu,\nu\},$ представљају дијагоналне блокове.

Блоковима називамо добијене подматрице полазне матрице $M.$ За означавање блокова можемо да користимо два индекса. Тако у блоку $A_{ij}$ је $i$ индекс блоковске врсте, а $j$ индекс блоковске колоне. Број блоковских врста $\mu$ и број блоковских колона $\nu$ одређује димензију блоковске матрице $\mu\times\nu.$

**Primer 1.** Neka je data matrica 
$$ 	A=
	\begin{bmatrix}
	1 & 2 & 3 & 4 \\
	5 & 6 & 7 & 8 \\
	9 & 10 & 11 & 12 \\
	13 & 14 & 15 & 16
	\end{bmatrix}.
	$$
Primer razbijanja matrice $A$ na blokove dat je na sledeći način:
$$
	A=
	\left[\begin{array}{@{}c|cc|c@{}}
	1 & 2 & 3 & 4 \\\hline
	5 & 6 & 7 & 8 \\
	9 & 10 & 11 & 12 \\
	13 & 14 & 15 & 16
	\end{array}\right].
$$
Blokovi matrice $A$ su podmatrice:
$$
	A_{11}=  \begin{bmatrix}    1  \end{bmatrix}, \quad
	A_{12} =\begin{bmatrix}   2 & 3  \end{bmatrix}, \quad
	A_{13} =\begin{bmatrix}    4  \end{bmatrix},  
$$    
$$
	A_{21}=\begin{bmatrix}    5\\    9\\    13  \end{bmatrix}, \quad
	A_{22}=\begin{bmatrix}	6 & 7\\	10 & 11\\	14 & 15	\end{bmatrix}, \quad
	A_{23} =  \begin{bmatrix}     8 \\    12 \\    16  \end{bmatrix}.
$$
Koristeći dobijene blokove matricu $A$ zapisujemo na sledeći način u blok formi:
$$	A=
	\begin{bmatrix}
	A_{11} & A_{12} & A_{13} \\
	A_{21} & A_{22} & A_{23}
	\end{bmatrix}.
$$
Ovaj zapis predstavlja blok matricu $A,$ njeni elementi su matrice $ A_{ij},$ a ne brojevi. Blokovska matrica $A$ je blok-dimenzije $2\times3,$ dok je polazna (skalarna) matrica $A$ dimenzije $4\times 4.$

**Primer 2.** Na matrici $A=\begin{bmatrix}1&0&1&0\\0&1&0&1\end{bmatrix}$ uočavamo delove koje možemo kraće da obeležavamo uobičajenom notacijom za jedinične matrice. Tako je blok zapis matrice $A$ blok-dimenzije $1\times2:$
	$$A=\left[\begin{array}{cc|cc}
	1&0&1&0\\0&1&0&1
	\end{array}\right]=\begin{bmatrix} I&|&I\end{bmatrix}.$$	

**Primer 3.** Sistemi linearnih jednačina se za implementaciju i efikasno rešavanje zapisuju u matričnom obliku $$Ax=b.$$ Za predstavljanje sistema u algoritmima za nalaženje rešenja koristimo blok zapis proširene matrice sistema blok dimenzije $1\times2$ koju nazivamo proširena matrica sistema:
	$$\begin{bmatrix} A&b\end{bmatrix}\quad\mbox{ili}\quad\begin{bmatrix} A&|&b\end{bmatrix}.$$ 
Postupci koriste niz transformacija kojima se polazna blok forma dovodi na oblik
$$\begin{bmatrix} A&|&b\end{bmatrix}\quad\mapsto\quad\begin{bmatrix} I&|&v\end{bmatrix},$$
gde je $v$ vektor koji sadrži rešenja polaznog sistema. Algoritam koji se koristi je Gausov.

Simultano rešavanje više sistema linearnih jednačina sa istom matricom sistema, tj. rešavanje matričnih jednačina $AX=B$ koristi istu notaciju $\begin{bmatrix} A&|&B\end{bmatrix}.$ Gaus-Jordanov metod predstavlja niz transformacija sa rezultatom
$$\begin{bmatrix} A&|&B\end{bmatrix}\quad\mapsto\quad\begin{bmatrix} I&|&V\end{bmatrix},$$
gde je $V$ matrica rešenje polazne matrične jednačine. Ovim postupkom se izračunava i inverzna matrica regularne matrice.
$$\begin{bmatrix} A&|&I\end{bmatrix}\quad\mapsto\quad\begin{bmatrix} I&|&A^{-1}\end{bmatrix}.$$

## Операције са блок-матрицама

U slučaju blokovske podele $2\times2,$  matricu $A$ tipa $m\times n$ jednom pravom paralelnom vrstama i jednom pravom paralelnom kolonama razbijamo na četiri podmatrice, 
$$A=\begin{bmatrix} A_{11}& A_{12}\\ A_{21}& A_{22}\end{bmatrix}.$$

Notacija blok matrica podržava osnovnu algebru matrica. Operacije nad blok matricama su prirodno produženje operacija nad skalarnim matricama. Mogućnost sprovođenja operacija nad pojedinačnim blokovima uslovljena je slaganjem dimenzija tih blokova. Uslov izvršivosti svake od operacija svodi se na uobičajene uslove jednakosti dimenzija. 	 

Ako je $\lambda\in\mathbb{C}$ data konstanta tada je:
$$
\lambda A = \begin{bmatrix}
\lambda A_{11} & \lambda A_{12}\\
\lambda A_{21} & \lambda A_{22}\end{bmatrix} \quad\mbox{i}\quad
A^T=\begin{bmatrix} A_{11}^T & A_{21}^T\\
A_{12}^T & A_{22}^T \end{bmatrix}.
$$

Zbir blok matrica u blok formi je moguć jedino ako su odgovarajući blokovi  matrice istog tipa. Blokovska podela koja omogućava takvu primenu operacije naziva se **konformna podela** matrica za sabiranje. U tom slučaju važi jednakost:
$$
A+B =\begin{bmatrix} A_{11}& A_{12}\\ A_{21}& A_{22}\end{bmatrix}+
\begin{bmatrix} B_{11}& B_{12}\\ B_{21}& B_{22}\end{bmatrix}= 
\begin{bmatrix} A_{11}+B_{11}& A_{12}+B_{12}\\ A_{21}+B_{21}& A_{22}+B_{22}\end{bmatrix}.
$$

Proizvod blok matrica $2\times2$ je takođe blok matrica istog blokovskog tipa. Izraz za prozvod dat je sa:
$$
A B =\begin{bmatrix} A_{11}& A_{12}\\ A_{21}& A_{22}\end{bmatrix} 
\begin{bmatrix} B_{11}& B_{12}\\ B_{21}& B_{22}\end{bmatrix}= 
\begin{bmatrix} A_{11}B_{11}+A_{12}B_{21} & A_{11}B_{12}+A_{12}B_{22}\\ A_{21}B_{11}+A_{22}B_{21} & A_{21}B_{12}+A_{22}B_{22}\end{bmatrix}.
$$
Blokovsko množenje  je moguće izvesti jedino ako je definisan svaki od proizvoda u izrazu.
Da bi množenje matrica $A$ i $B$ moglo da se sprovede u blok formi neophodno je da se podela u blokove po kolonama matrice $A$ slaže sa podelom u blokove po vrstama matrice $B$ - pravilo unutrašnjeg indeksa za svako blokovsko množenje.  Ukoliko su ispunjeni svi ovi uslovi, kažemo da su matrice $A$ i $B$ konformno podeljene u blokove za operaciju množenja. U praksi se najčešće koristi konformna podela u kojoj su odgovarajući dijagonalni blokovi kvadratne matrice istog tipa. Time se postiže konformnost za sve aritmetičke operacije.

Množenje matrica u blok formi i pojam konformne podele matrica se lako uopštava na veće blokovske dimenzije. Ona omogućava množenje matrica po istim pravilima koja važe za množenje običnih skalarnih matrica. Kako za množenje matrica ne važi komutativnost, potrebno je strogo voditi računa o redosledu činilaca prilikom blokovskog množenja. 

**Primer 4.** Dovršićemo konformno razbijanje matrica $A$ i $B$ na blok matrice reda 2, tj. napravićemo razbijanje tako da blokovsko množenje u proizvodu $AB$ bude moguće. Neophodno je obezbediti poklapanje unutrašnjih indeksa blokova u blokovskom proizvodu. 
$$A=\left[\begin{array}{c|cc}
	1&2&3\\ \hline 		4&5&6\\7&8&9
	\end{array}\right]=
\begin{bmatrix} A_{11}&A_{12}\\A_{21}&A_{22}\end{bmatrix},\quad 	
B=\left[\begin{array}{cccc}
	1&2&3&4\\5&6&7&8\\9&10&11&12
	\end{array}\right]
	.$$

Konformno razbijanje matrice $B$ u blok matricu reda 2, $B=\begin{bmatrix} B_{11}&B_{12}\\B_{21}&B_{22}\end{bmatrix},$ moguće je izvesti na nekoliko načina. Da bismo lakše sagledali odnos indeksa blokova koristićemo predstavljanje proizvoda matrica preko spoljašnjeg proizvoda vektora:
$$AB=\begin{bmatrix} A_{11}&A_{12}\\A_{21}&A_{22}\end{bmatrix}
\begin{bmatrix} B_{11}&B_{12}\\B_{21}&B_{22}\end{bmatrix}=
\begin{bmatrix} A_{11}\\ A_{21}\end{bmatrix}
\begin{bmatrix} B_{11}&B_{12}\end{bmatrix}+
\begin{bmatrix} A_{12}\\ A_{22}\end{bmatrix}
\begin{bmatrix} B_{21}&B_{22}\end{bmatrix}.$$

Prva blokovska kolona $\begin{bmatrix} A_{11}\\ A_{21}\end{bmatrix}=\left[\begin{array}{c}1\\ \hline 4\\7\end{array}\right]$ matrice $A$ sadrži jednu skalarnu kolonu, pa i prva blokovska vrsta $\begin{bmatrix} B_{11}&B_{12}\end{bmatrix}$ matrice $B$ mora da sadrži jednu skalarnu vrstu da bi se obezbedila jednakost unutrašnjih indeksa. Slično, druga blokovska kolona $\begin{bmatrix} A_{12}\\ A_{22}\end{bmatrix}=\left[\begin{array}{cc}2&3\\ \hline 5&6\\8&9\end{array}\right]$ sadrži dve skalarne kolone. Toliko skalarnih vrsta mora sadržati druga blokovska vrsta $\begin{bmatrix} B_{21}&B_{22}\end{bmatrix}$ matrice $B.$
Tako dolazimo do mogućih konformnih razbijanja matrice $B:$
$$B=\left[\begin{array}{c|ccc}
	1&2&3&4\\ \hline 5&6&7&8\\9&10&11&12
	\end{array}\right],\quad
	B=\left[\begin{array}{cc|cc}
	1&2&3&4\\ \hline 5&6&7&8\\9&10&11&12
	\end{array}\right],\quad
	B=\left[\begin{array}{ccc|c}
	1&2&3&4\\ \hline 5&6&7&8\\9&10&11&12
	\end{array}\right].$$

Izračunavanjem u Pythonu možemo da proverimo ove rezultate.

In [2]:
A=np.arange(1,10).reshape(3,3)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
B=np.arange(1,13).reshape(3,4)
B

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
C=A@B
C

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128],
       [128, 152, 176, 200]])

Proverićemo blokovsko množenje prema formuli
$$
A B =\begin{bmatrix} A_{11}& A_{12}\\ A_{21}& A_{22}\end{bmatrix} 
\begin{bmatrix} B_{11}& B_{12}\\ B_{21}& B_{22}\end{bmatrix}= 
\begin{bmatrix} A_{11}B_{11}+A_{12}B_{21} & A_{11}B_{12}+A_{12}B_{22}\\ A_{21}B_{11}+A_{22}B_{21} & A_{21}B_{12}+A_{22}B_{22}\end{bmatrix}
$$
za različite konformne podele matrice $B.$

Prva podela: $A=\left[\begin{array}{c|cc}
	1&2&3\\ \hline 		4&5&6\\7&8&9
	\end{array}\right]$ i $B=\left[\begin{array}{c|ccc}
	1&2&3&4\\ \hline 5&6&7&8\\9&10&11&12
	\end{array}\right].$

In [5]:
C11=A[:1,:1]@B[:1,:1]+A[:1,1:]@B[1:,:1]
C12=A[:1,:1]@B[:1,1:]+A[:1,1:]@B[1:,1:]
C21=A[1:,:1]@B[:1,:1]+A[1:,1:]@B[1:,:1]
C22=A[1:,:1]@B[:1,1:]+A[1:,1:]@B[1:,1:]
np.concatenate((np.concatenate((C11,C12),axis=1),np.concatenate((C21,C22),axis=1)))

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128],
       [128, 152, 176, 200]])

Druga podela $A=\left[\begin{array}{c|cc}
	1&2&3\\ \hline 		4&5&6\\7&8&9
	\end{array}\right]$ i $
	B=\left[\begin{array}{cc|cc}
	1&2&3&4\\ \hline 5&6&7&8\\9&10&11&12
	\end{array}\right].$

In [6]:
C11=A[:1,:1]@B[:1,:2]+A[:1,1:]@B[1:,:2]
C12=A[:1,:1]@B[:1,2:]+A[:1,1:]@B[1:,2:]
C21=A[1:,:1]@B[:1,:2]+A[1:,1:]@B[1:,:2]
C22=A[1:,:1]@B[:1,2:]+A[1:,1:]@B[1:,2:]
np.concatenate((np.concatenate((C11,C12),axis=1),np.concatenate((C21,C22),axis=1)))

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128],
       [128, 152, 176, 200]])

Treća podela $A=\left[\begin{array}{c|cc}
	1&2&3\\ \hline 		4&5&6\\7&8&9
	\end{array}\right]$ i $
	B=\left[\begin{array}{ccc|c}
	1&2&3&4\\ \hline 5&6&7&8\\9&10&11&12
	\end{array}\right].$

In [7]:
C11=A[:1,:1]@B[:1,:3]+A[:1,1:]@B[1:,:3]
C12=A[:1,:1]@B[:1,3:]+A[:1,1:]@B[1:,3:]
C21=A[1:,:1]@B[:1,:3]+A[1:,1:]@B[1:,:3]
C22=A[1:,:1]@B[:1,3:]+A[1:,1:]@B[1:,3:]
np.concatenate((np.concatenate((C11,C12),axis=1),np.concatenate((C21,C22),axis=1)))

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128],
       [128, 152, 176, 200]])

**Primer 5.** U slučaju blok podele matrica-vektor $\begin{bmatrix} A&v\end{bmatrix}$ koristimo i notaciju $\begin{bmatrix} A&|& v\end{bmatrix},$ gde je $A$ matrica i $v$ vektor. Tada je proizvod
	$$\begin{bmatrix} A&v\end{bmatrix}^T
    \begin{bmatrix} A&v\end{bmatrix}
    =\begin{bmatrix} A^T\\ v^T\end{bmatrix}
    \begin{bmatrix} A&v\end{bmatrix}=
    \begin{bmatrix} A^TA&A^Tv\\v^TA&v^Tv\end{bmatrix}.$$

Izračunavanjem u Pythonu možemo da proverimo ove rezultate. Koristićemo ulazne podatke o matrici $B$ iz prethodnog primera, samo ćemo elemente tumačiti u svojstvu blok podele iz ovog primera.
$$B=[A|v]=\left[\begin{array}{ccc|c}
	1&2&3&4\\ 5&6&7&8\\9&10&11&12
	\end{array}\right].$$

In [8]:
B.T@B

array([[107, 122, 137, 152],
       [122, 140, 158, 176],
       [137, 158, 179, 200],
       [152, 176, 200, 224]])

In [9]:
C=np.empty((4,4))
C[:-1,:-1]=(B[:,:-1]).T@B[:,:-1]   #blok A^TA
C[:-1,-1]=(B[:,:-1]).T@B[:,-1]     #blok A^Tv
C[-1,:-1]=B[:,-1]@B[:,:-1]         #blok v^TA
C[-1,-1]=np.dot(B[:,-1],B[:,-1])   #blok v^Tv
print(C)

[[107. 122. 137. 152.]
 [122. 140. 158. 176.]
 [137. 158. 179. 200.]
 [152. 176. 200. 224.]]


**Primer 6.** Neka su matrice $A$ i $B$ date u blok formi gde indeksi u blokovima označavaju odgovarajuće dimenzije:
$$A=\begin{bmatrix}A_{m\times r}&| &A_{m\times s}\end{bmatrix},\qquad
B=\begin{bmatrix}\underline{\phantom{W}B_{r\times n}\phantom{W}}\\ {\phantom{W}B_{s\times n}\phantom{W}}\end{bmatrix}.
$$

Ovakva blokovska podela pogoduje opisivanju uopštenja spoljašnjeg proizvoda vektora:
$$AB=\begin{bmatrix}A_{m\times r}&| &A_{m\times s}\end{bmatrix}
\begin{bmatrix}\underline{\phantom{W}B_{r\times n}\phantom{W}}\\\phantom{W}B_{s\times n}\phantom{W}\end{bmatrix}
=A_{m\times r}B_{r\times n}+A_{m\times s}B_{s\times n}.
$$

Izračunavanjem u Pythonu možemo da proverimo ove rezultate. Iskoristićemo postojeće matrice $A$ i $B$ i naznačenu blokovsku podelu,
$$A=\left[\begin{array}{cc|c}
	1&2&3\\ 4&5&6\\7&8&9
	\end{array}\right]\qquad\mbox{ i }\qquad
	B=\left[\begin{array}{cccc}
	1&2&3&4\\ 5&6&7&8\\ \hline 9&10&11&12
	\end{array}\right].$$

In [10]:
print(A)
print(B)
print(A@B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 38  44  50  56]
 [ 83  98 113 128]
 [128 152 176 200]]


In [11]:
AmrBrn=A[:,:-1]@B[:-1]
AmsBsn=np.outer(A[:,-1],B[-1])
print(AmrBrn+AmsBsn)

[[ 38  44  50  56]
 [ 83  98 113 128]
 [128 152 176 200]]


**Primer 7.**   Ukoliko su vektori $v$ i $u$ zadati kao blok-vektori čiji su odgovarajući blokovi istih dimenzija
$$v=\left[\begin{array}{c}v_1\\ \hline v_2\\ \hline\vdots\\ \hline v_d\end{array}\right]
    \qquad,\qquad
    u=\left[\begin{array}{c}u_1\\ \hline u_2\\ \hline\vdots\\ \hline u_d\end{array}\right],
$$    
tada je
$$v\cdot u=v^Tu=v_1^Tu_1+v_2^Tu_2+\dots+v_d^Tu_d=v_1\cdot u_1+v_2\cdot u_2+\dots+v_d\cdot u_d.$$
Drugim rečima, skalarni proizvod blok-vektora jednak je zbiru skalarnih proizvoda njihovih blokova.

Izračunavanjem u Pythonu možemo da proverimo ove rezultate. Preporuka je da studenti sami dizajniraju numerički eksperiment.

**Задатак 1.** Користећи блок матрице, израчунати $M^2$ ако је 
		$$M=\begin{bmatrix} 1&0&0&0&0&0&0&0&0&1\\0&1&0&0&0&0&0&0&1&0\\
		0&0&1&0&0&0&0&1&0&0\\0&0&0&1&0&0&1&0&0&0\\0&0&0&0&1&1&0&0&0&0\\
		0&0&0&0&0&2&0&0&0&0\\0&0&0&0&0&0&2&0&0&0\\0&0&0&0&0&0&0&3&0&0\\
		0&0&0&0&0&0&0&0&3&0\\0&0&0&0&0&0&0&0&0&3\end{bmatrix}.$$

**Решење :**

Уведимо ознаке блокова матрице $M:$ $I=\begin{bmatrix} 1&0&0&0&0\\0&1&0&0&0\\0&0&1&0&0\\0&0&0&1&0\\0&0&0&0&1\end{bmatrix},$
$S=\begin{bmatrix} 0&0&0&0&1\\0&0&0&1&0\\0&0&1&0&0\\0&1&0&0&0\\1&0&0&0&0\end{bmatrix}$ $A={\rm diag}(2,2,3,3,3),$ и $O$ је нула-матрица. Тада је
\begin{align}
&M=\begin{bmatrix}I&S\\O&A\end{bmatrix}\quad\Longrightarrow\quad
M^2=\begin{bmatrix}I&S\\O&A\end{bmatrix}\begin{bmatrix}I&S\\O&A\end{bmatrix}=
\begin{bmatrix}I&S\\O&A^2\end{bmatrix},\ A^2={\rm diag}(2,2,3,3,3)^2={\rm diag}(2^2,2^2,3^2,3^2,3^2),\\
&M^2=\begin{bmatrix} 1&0&0&0&0&0&0&0&0&1\\0&1&0&0&0&0&0&0&1&0\\
		0&0&1&0&0&0&0&1&0&0\\0&0&0&1&0&0&1&0&0&0\\0&0&0&0&1&1&0&0&0&0\\
		0&0&0&0&0&4&0&0&0&0\\0&0&0&0&0&0&4&0&0&0\\0&0&0&0&0&0&0&9&0&0\\
		0&0&0&0&0&0&0&0&9&0\\0&0&0&0&0&0&0&0&0&9\end{bmatrix}.
\end{align}

In [12]:
I=np.eye(5)
S=I[::-1]
A=np.diag([2,2,3,3,3])
O=np.zeros((5,5))

In [13]:
M=np.concatenate(
(np.concatenate((I,S),axis=1),
np.concatenate((O,A),axis=1) )   
)
M

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 2., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 3.]])

In [14]:
M@M

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [0., 1., 0., 0., 0., 0., 0., 0., 4., 0.],
       [0., 0., 1., 0., 0., 0., 0., 4., 0., 0.],
       [0., 0., 0., 1., 0., 0., 3., 0., 0., 0.],
       [0., 0., 0., 0., 1., 3., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 4., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 4., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 9., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 9., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 9.]])

**Задатак 2.** Нека је $M$ квадратна матрица дата у блок форми $M=\begin{bmatrix} A&B\\O&O\end{bmatrix},$ са квадратним водећим блоком $A.$ Са $O$ су означене нула-матрице не обавезно истих димензија. 
Доказати да је $$M^n=\begin{bmatrix} A^n&A^{n-1}B\\O&O\end{bmatrix},\ \forall n\in\mathbb{N}.$$

**Решење :**

Доказ изводимо индукцијом по степену $n$ матрице $M.$
- $n=2:\quad M^2=\begin{bmatrix} A&B\\O&O\end{bmatrix}\begin{bmatrix} A&B\\O&O\end{bmatrix}=\begin{bmatrix} A^2&AB\\O&O\end{bmatrix}$
- индукцијска хипотеза: $M^n=\begin{bmatrix} A^n&A^{n-1}B\\O&O\end{bmatrix}$ за $n\geq1.$
- $n+1:\quad M^{n+1}=MM^n=\begin{bmatrix} A&B\\O&O\end{bmatrix}\begin{bmatrix} A^n&A^{n-1}B\\O&O\end{bmatrix}=\begin{bmatrix} A^{n+1}&A^{n}B\\O&O\end{bmatrix}.$

**Задатак 3.** Дата је матрица
$$M=\begin{bmatrix}A&B\\O&I\end{bmatrix}, $$
која је разбијена на четири блока $A,B,O,I\in\mathcal{M}_{n\times n}.$
Испитати да ли да ли је тачна једнакост		
$$M^k=\begin{bmatrix}A^k&(A^{k-1}+A^{k-2}+\dots+A+I)B\\O&I\end{bmatrix}.$$

**Решење :**

Доказ изводимо индукцијом по степену $n$ матрице $M.$
- $k=2:\quad M^2=\begin{bmatrix} A&B\\O&I\end{bmatrix}\begin{bmatrix} A&B\\O&I\end{bmatrix}=\begin{bmatrix} A^2&(A+I)B\\O&I\end{bmatrix}$
- индукцијска хипотеза: $M^k=\begin{bmatrix} A^k&(A^{k-1}+A^{k-2}+\dots+A+I)B\\O&I\end{bmatrix}$ за $k\geq1.$
- $k+1:\quad M^{k+1}=MM^k=\begin{bmatrix} A&B\\O&I\end{bmatrix}\begin{bmatrix} A^k&(A^{k-1}+A^{k-2}+\dots+A+I)B\\O&I\end{bmatrix}=\begin{bmatrix} A^{k+1}&(A^{k}+A^{k-1}+\dots+A+I)B\\O&I\end{bmatrix}.$

**Задатак 4.** a) Нека је $M=\begin{bmatrix} A&O\\O&B\end{bmatrix}$ блок дијагонална матрица са регуларним дијагоналним блоковима. Доказати да је тада $M^{-1}=\begin{bmatrix} A^{-1}&O\\O&B^{-1}\end{bmatrix}.$
		
б) Наћи инверзе следећих матрица.
	$$U=\begin{bmatrix}1&2&0\\2&1&0\\0&0&3\end{bmatrix},\qquad 
    V=\begin{bmatrix}1&-1&0&0\\2&-1&0&0\\0&0&1&3\\0&0&2&5\end{bmatrix}.$$

**Решење :**

а) $\begin{bmatrix} A&O\\O&B\end{bmatrix}\begin{bmatrix} A^{-1}&O\\O&B^{-1}\end{bmatrix}=\begin{bmatrix} I&O\\O&I\end{bmatrix}=
\begin{bmatrix} A^{-1}&O\\O&B^{-1}\end{bmatrix}\begin{bmatrix} A&O\\O&B\end{bmatrix}.$

б) $U=\begin{bmatrix}1&2&0\\2&1&0\\0&0&3\end{bmatrix}=\left[\begin{array}{cc|c}1&2&0\\2&1&0\\\hline0&0&3\end{array}\right]=\begin{bmatrix}A&O\\O&B\end{bmatrix}\quad\Longrightarrow\quad
U^{-1}=\begin{bmatrix} A^{-1}&O\\O&B^{-1}\end{bmatrix}=\left[\begin{array}{cc|c}-1/3&2/3&0\\2/3&-1/3&0\\\hline0&0&1/3\end{array}\right].$

In [15]:
U=np.array([[1,2,0],[2,1,0],[0,0,3]])
np.linalg.inv(U)

array([[-0.33333333,  0.66666667,  0.        ],
       [ 0.66666667, -0.33333333,  0.        ],
       [ 0.        ,  0.        ,  0.33333333]])

$V=\begin{bmatrix}1&-1&0&0\\2&-1&0&0\\0&0&1&3\\0&0&2&5\end{bmatrix}=\left[\begin{array}{cc|cc}1&-1&0&0\\2&-1&0&0\\\hline0&0&1&3\\0&0&2&5\end{array}\right]\begin{bmatrix}A&O\\O&B\end{bmatrix}
\quad\Longrightarrow\quad
U^{-1}=\begin{bmatrix} A^{-1}&O\\O&B^{-1}\end{bmatrix}=\left[\begin{array}{cc|cc}-1&1&0&0\\-2&1&0&0\\\hline0&0&-5&3\\0&0&2&-1\end{array}\right].$

In [16]:
V=np.array([[1,-1,0,0],[2,-1,0,0],[0,0,1,3],[0,0,2,5]])
np.linalg.inv(V)

array([[-1.,  1.,  0.,  0.],
       [-2.,  1., -0., -0.],
       [ 0.,  0., -5.,  3.],
       [ 0.,  0.,  2., -1.]])

**Primer 8.** Kao što je već poznato, proizvod $AB,$
 kavdratnih matrica reda $n,$ 	troši $n^3$ operacija množenja i $n^2(n-1)$ operacija sabiranja, tj. ukupno $\mathcal{O}(2n^3).$ Svaka od osnovnih aritmetičkih operacija $(+,-,\cdot,/)$ podrazumeva neko vreme izvršenja na računaru, koje je za pojedinačne operacije izuzetno kratko. Međutim, za velike dimenzije matrica $A$ i $B$ vreme izvršenja celokupnog postupka može da bude i duže. Glavno vremensko opterećenje zapravo leži u broju komunikacija $CPU$ jedinice sa memorijom računara. 
	 
	
Različite blokovske podele matrica mogu predstavljati različite strategije smeštaja delova matrica u brzu memoriju računara. Cilj je obezbediti što bolju lokalnost podataka za operacije koje treba izvršiti i time smanjiti broj komunikacija između primarne i sekundarne memorije računara. Opisaćemo algoritam za množenje dve blok matrice blokovskih dimenzija $2\times2,$ koji je predložio [Štrasen](https://stanford.edu/~rezab/classes/cme323/S16/notes/Lecture03/cme323_lec3.pdf) u radu: V. Štrasen. Gaussian elimination is not optimal. Numer. Math., 13:354–356, 1969.

Neka su date dve blok matrice reda $2n$
	$$A=\begin{bmatrix} A_{11}&A_{12}\\ A_{21}&A_{22}\end{bmatrix}\quad\mbox{i}\quad
	B=\begin{bmatrix} B_{11}&B_{12}\\ B_{21}&B_{22}\end{bmatrix},$$
 gde su svi blokovi $A_{ij}$ i $B_{ij}$ kvadratne matrice reda $n.$ Njihov proizvod je blok matrica istog tipa 
$$C=AB=\begin{bmatrix} C_{11}&C_{12}\\ C_{21}&C_{22}\end{bmatrix}= 
\begin{bmatrix} A_{11}B_{11}+A_{12}B_{21} & A_{11}B_{12}+A_{12}B_{22}\\ A_{21}B_{11}+A_{22}B_{21} & A_{21}B_{12}+A_{22}B_{22}\end{bmatrix}.$$
Prema ovoj formuli izračunavanje matrice $C$ koristi $8$ proizvoda blokova $n\times n.$ Izračunavanje proizvoda matrica je skuplja operacija od sabiranja matrica, jer ovo drugo troši $n^2$ sabiranja. Broj množenja blok matrica može se smanjiti na $7$ uz povećan broj sabiranja blokova. 
	Na taj način broj operacija trećeg nivoa se smanjuje, a povećava broj operacija drugog nivoa.	

Štrasenov postupak predviđa uvođenje sledećih međurezultata, tj. koraka:
\begin{align}
	    M_1&=(A_{11}+A_{22})(B_{11}+B_{22}),\\
	    M_2&=(A_{21}+A_{22})B_{11},\\
	    M_3&=A_{11}(B_{12}-B_{22}),\\
	    M_4&=A_{22}(B_{21}-B_{11}),\\
	    M_5&=(A_{11}+A_{12})B_{22},\\
	    M_6&=(A_{21}-A_{11})(B_{11}+B_{12}),\\
	    M_7&=(A_{12}-A_{22})(B_{21}+B_{22}).
\end{align}
Tada se matrica $C$ dobija sa
$$C=\begin{bmatrix} M_1+M_4-M_5+M_7 & M_3+M_5\\
M_2+M_4 & M_1-M_2+M_3+M_6
\end{bmatrix}.$$
U klasičnom postupku množenja za izračunavanje matrice $C\in\mathcal{M}_{2n\times2n}$ bilo bi upotrebljeno $(2n)^3$ operacija množenja i  $(2n)^3-(2n)^2$ operacija sabiranja, ukupno $16n^3-4n^2$. U Štrasenovom algoritmu potrebne operacije su: $7n^3$ množenja  i $7n^3+8n^2$ sabiranja, ukupno $14n^3+8n^2$. Grafičkim poređenjem dva polinoma vidimo da manja operacijska složenost Štrasenovog algoritma nastupa već za male vrednosti $n\in\mathbb{N}.$

Prikazan Štrasenov algoritam je nešto bolji od klasičnog množenja matrica. Naime, pokazano je da se rekurzivnom podelom blokova na $2\times2$ blok matrice za izračunavanje matrica $M_1,\dots,M_7$ ukupan broj aritmetičkih operacija svodi na $\mathcal{O}(n^{\log_2 7})\approx\mathcal{O}(n^{2.8})$ kod matrica dimenzije $n=2^k.$ Značaj ovog algoritma je što je pokrenuo istraživanja u smeru [efikasnijih algoritama](https://handwiki.org/wiki/Coppersmith%E2%80%93Winograd_algorithm) množenja matrica.

**Задатак 5.** Написати програмски код којим се реализује Штрасенов алгоритам множења две матрице. Нека је $n=2^p$ и $A,B\in\mathcal{M}_{n\times n}.$ Уколико је $n_{\min}=2^d,\ d\leq p,$ онда алгоритам израчунава производ $C=AB$ по следећем правилу:
```
    def C=strass(A,B,n,n_min):
        if n<=n_min
            C=AB na klasičan način
        else
            m=n/2
            M1=strass(A[:m,:m]+A[m:,m:],B[:m,:m]+B[m:,m:])
            M2=strass(A[m:,:m]+A[m:,m:],B[:m,:m])
            M3=strass(A[:m,:m],B[:m,m:]-B[m:,m:])
            M4=strass(A[m:,m:],B[m:,:m]-B[:m,:m])
            M5=strass(A[:m,:m]+A[:m,m:],B[m:,m:])
            M6=strass(A[m:,:m]-A[:m,:m],B[:m,:m]+B[:m,m:])
            M7=strass(A[:m,m:]-A[m:,m:],B[m:,:m]+B[m:,m:])
            C[:m,:m]=M1+M4-M5+M7
            C[:m,m:]=M3+M5
            C[m:,:m]=M2+M4
            C[m:,m:]=M1-M2+M3+M6
```

**Zadatak 6.** Prilagoditi prethodni algoritam kojim bi se množile dve kvadratne matrice proizvoljnog reda. To znači, ukoliko su matrice neparne dimenzije dopuniti ih nula vrstom i kolonom do parne dimenzije.

**Zadatak 7.** Prilagoditi prethodni algoritam tako da može da množi i pravougaone matrice.

## Кронекеров производ матрица

**Дефиниција 1.** За две матрице $A=[a_{ij}]\in\mathcal{M}_{m\times n}$ и $B=[b_{kl}]\in\mathcal{M}_{p\times q}$ Кронекеров производ матрица $\otimes$ је операција којом се добија матрица $C=A\otimes B\in\mathcal{M}_{mp\times nq},$ а чији је садржај описан следећом блок формом:
$$C=A\otimes B=\begin{bmatrix}a_{11}B&a_{12}B&\dots&a_{1n}B\\
a_{21}B&a_{22}B&\dots&a_{2n}B\\
\vdots&\vdots&&\vdots\\
a_{m1}B&a_{m2}B&\dots&a_{mn}B\end{bmatrix}.$$

Кронекеров производ као резултат има матрицу чији су блокови скалирана матрица $B$ где су коефицијенти скалирања садржани у матрици $A.$

**Пример 9.** Потражићемо Кронекеров производ две јединичне матрице $I_2,I_3.$
\begin{align}
I_2\otimes I_3&=\begin{bmatrix}1&0\\0&1\end{bmatrix}\otimes I_3
=\begin{bmatrix}1\cdot I_3&0\cdot I_3\\0\cdot I_3&1\cdot I_3\end{bmatrix}
=\begin{bmatrix}I_3&O_3\\O_3&I_3\end{bmatrix}\\
&=\left[\begin{array}{ccc|ccc}1&0&0&0&0&0\\
0&1&0&0&0&0\\0&0&1&0&0&0\\\hline
0&0&0&1&0&0\\0&0&0&0&1&0\\0&0&0&0&0&1
\end{array}\right]=I_6.
\end{align}

In [17]:
I2=np.eye(2)
I3=np.eye(3)
np.kron(I2,I3)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

Потражићемо Кронекеров производ матрица $I_2$ и $M=\begin{bmatrix}1&2&3\\-1&1&0\end{bmatrix}$ у оба смера.

In [18]:
M=np.array([[1,2,3],[-1,1,0]])
np.kron(I2,M)

array([[ 1.,  2.,  3.,  0.,  0.,  0.],
       [-1.,  1.,  0., -0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  2.,  3.],
       [-0.,  0.,  0., -1.,  1.,  0.]])

In [19]:
np.kron(M,I2)

array([[ 1.,  0.,  2.,  0.,  3.,  0.],
       [ 0.,  1.,  0.,  2.,  0.,  3.],
       [-1., -0.,  1.,  0.,  0.,  0.],
       [-0., -1.,  0.,  1.,  0.,  0.]])

Закључујемо да ова операција није комутативна.

**Пример 10.** Спољашњи производ два вектора се поклапа са њиховим Кронекеровим производом.
\begin{align}
\begin{bmatrix}a_1\\a_2\\\vdots\\a_m\end{bmatrix}
\begin{bmatrix}b_1&b_2&\dots&b_n\end{bmatrix}
&=\begin{bmatrix}
a_1b_1&a_1b_2&\dots&a_1b_n\\
a_2b_1&a_2b_2&\dots&a_2b_n\\
\vdots&\vdots&&\vdots\\
a_mb_1&a_mb_2&\dots&a_mb_n
\end{bmatrix}
=\begin{bmatrix}
a_1\begin{bmatrix}b_1&b_2&\dots&b_n\end{bmatrix}\\
a_2\begin{bmatrix}b_1&b_2&\dots&b_n\end{bmatrix}\\
\vdots\\
a_m\begin{bmatrix}b_1&b_2&\dots&b_n\end{bmatrix}
\end{bmatrix}\\
&=\begin{bmatrix}a_1\\a_2\\\vdots\\a_m\end{bmatrix}\otimes
\begin{bmatrix}b_1&b_2&\dots&b_n\end{bmatrix}.
\end{align}

Приметимо да уколико је матрица $A$ дата у блок форми $A=\begin{bmatrix}A_{11}&A_{12}\\A_{21}&A_{22}\end{bmatrix},$ тада се и израчунавање Кронекеровог производа може да искаже на сличан начин:
$$A\otimes B=\begin{bmatrix}A_{11}&A_{12}\\A_{21}&A_{22}\end{bmatrix}\otimes B=
\begin{bmatrix}A_{11}\otimes B&A_{12}\otimes B\\A_{21}\otimes B&A_{22}\otimes B\end{bmatrix}.$$

И у општијем случају, тј. за блок поделу
$A=\begin{bmatrix}
A_{11} & A_{12} & \dots &A_{1\nu}\\
A_{21} & A_{22} & \dots &A_{2\nu}\\
\vdots & \vdots & \ddots & \vdots\\
A_{\mu1} & A_{\mu2} & \dots &A_{\mu \nu}
\end{bmatrix}$
важи


$$A\otimes B=\begin{bmatrix}
A_{11} & A_{12} & \dots &A_{1\nu}\\
A_{21} & A_{22} & \dots &A_{2\nu}\\
\vdots & \vdots & \ddots & \vdots\\
A_{\mu1} & A_{\mu2} & \dots &A_{\mu \nu}\end{bmatrix}\otimes B=
\begin{bmatrix} A_{11}\otimes B & A_{12}\otimes B & \dots &A_{1\nu}\otimes B\\
A_{21}\otimes B & A_{22}\otimes B & \dots &A_{2\nu}\otimes B\\
\vdots & \vdots & \ddots & \vdots\\
A_{\mu1}\otimes B & A_{\mu2}\otimes B & \dots &A_{\mu \nu}\otimes B\end{bmatrix}.$$

Особине Кронекеровог производа матрица:

1. $(A\otimes B)^T=A^T\otimes B^T,$
1. $A\otimes(B+C)=A\otimes B+A\otimes C,$
1. $(A+B)\otimes C=A\otimes C+B\otimes C,$
1. $(A\otimes B)(C\otimes D)=(AC)\otimes(BD).$

У свим изразима подразумева се да су матрице димензија које омогућавају извршење наведених операција.

**ДОКАЗ:**

$1.$

\begin{align}
(A\otimes B)^T&=\begin{bmatrix}a_{11}B&a_{12}B\\
a_{21}B&a_{22}B\end{bmatrix}^T
=\begin{bmatrix}a_{11}B^T&a_{21}B^T\\
a_{12}B^T&a_{22}B^T\end{bmatrix}=\begin{bmatrix}a_{11}&a_{21}\\
a_{12}&a_{22}\end{bmatrix}\otimes B^T\\[8pt]
&=A^T\otimes B^T.
\end{align}

Иначе, у општем облику овај доказ такође директно следи.
\begin{align}
(A\otimes B)^T&=\begin{bmatrix}a_{11}B&a_{12}B&\dots&a_{1n}B\\
a_{21}B&a_{22}B&\dots&a_{2n}B\\
\vdots&\vdots&&\vdots\\
a_{m1}B&a_{m2}B&\dots&a_{mn}B\end{bmatrix}^T
=\begin{bmatrix}a_{11}B^T&a_{21}B^T&\dots&a_{m1}B^T\\
a_{12}B^T&a_{22}B^T&\dots&a_{m2}B^T\\
\vdots&\vdots&&\vdots\\
a_{1n}B^T&a_{2n}B^T&\dots&a_{mn}B^T\end{bmatrix}\\[8pt]
&=A^T\otimes B^T.
\end{align}

$2.$
\begin{align}
A\otimes(B+C)&=\begin{bmatrix}a_{11}(B+C)&a_{12}(B+C)\\
a_{21}(B+C)&a_{22}(B+C)\end{bmatrix}
=\begin{bmatrix}a_{11}B&a_{12}B&\\
a_{21}B&a_{22}B\end{bmatrix}+
\begin{bmatrix}a_{11}C&a_{12}C\\
a_{21}C&a_{22}C\end{bmatrix}\\[8pt]
&=A\otimes B+A\otimes C
\end{align}

или
\begin{align}
A\otimes(B+C)&=\begin{bmatrix}a_{11}(B+C)&a_{12}(B+C)&\dots&a_{1n}(B+C)\\
a_{21}(B+C)&a_{22}(B+C)&\dots&a_{2n}(B+C)\\
\vdots&\vdots&&\vdots\\
a_{m1}(B+C)&a_{m2}(B+C)&\dots&a_{mn}(B+C)\end{bmatrix}\\[8pt]
&=\begin{bmatrix}a_{11}B&a_{12}B&\dots&a_{1n}B\\
a_{21}B&a_{22}B&\dots&a_{2n}B\\
\vdots&\vdots&&\vdots\\
a_{m1}B&a_{m2}B&\dots&a_{mn}B\end{bmatrix}+
\begin{bmatrix}a_{11}C&a_{12}C&\dots&a_{1n}C\\
a_{21}C&a_{22}C&\dots&a_{2n}C\\
\vdots&\vdots&&\vdots\\
a_{m1}C&a_{m2}C&\dots&a_{mn}C\end{bmatrix}\\[8pt]
&=A\otimes B+A\otimes C
\end{align}

3.
\begin{align}
(A+B)\otimes C&=\begin{bmatrix}(a_{11}+b_{11})C&(a_{12}+b_{12})C\\
(a_{21}+b_{21})C&(a_{22}+b_{22})C\end{bmatrix}
=\begin{bmatrix}a_{11}C&a_{12}C\\
a_{21}C&a_{22}C\end{bmatrix}
+
\begin{bmatrix}b_{11}C&b_{12}C\\
b_{21}C&b_{22}C\end{bmatrix}
\\[8pt]
&=A\otimes C+B\otimes C
\end{align}

или
\begin{align}
(A+B)\otimes C&=\begin{bmatrix}(a_{11}+b_{11})C&(a_{12}+b_{12})C&\dots&(a_{1n}+b_{1n})C\\
(a_{21}+b_{21})C&(a_{22}+b_{22})C&\dots&(a_{2n}+b_{2n})C\\
\vdots&\vdots&&\vdots\\
(a_{m1}+b_{m1})C&(a_{m2}+b_{m2})C&\dots&(a_{mn}+b_{mn})C\end{bmatrix}\\[8pt]
&=\begin{bmatrix}a_{11}C&a_{12}C&\dots&a_{1n}C\\
a_{21}C&a_{22}C&\dots&a_{2n}C\\
\vdots&\vdots&&\vdots\\
a_{m1}C&a_{m2}C&\dots&a_{mn}C\end{bmatrix}
+
\begin{bmatrix}b_{11}C&b_{12}C&\dots&b_{1n}C\\
b_{21}C&b_{22}C&\dots&b_{2n}C\\
\vdots&\vdots&&\vdots\\
b_{m1}C&b_{m2}C&\dots&b_{mn}C\end{bmatrix}
\\[8pt]
&=A\otimes C+B\otimes C
\end{align}

4. Нека су матрице $A$ и $C$ типа $2\times2$  $A=\begin{bmatrix}a_{11}&a_{12}\\a_{21}&a_{22}\end{bmatrix}$ и 
$C=\begin{bmatrix}c_{11}&c_{12}\\c_{21}&c_{22}\end{bmatrix}.$ Тада је

\begin{align}
(A\otimes B)(C\otimes D)&=\begin{bmatrix}a_{11}B&a_{12} B\\a_{21} B&a_{22} B\end{bmatrix}
\begin{bmatrix}c_{11} D&c_{12} D\\c_{21} D&c_{22} D\end{bmatrix}\\[8pt]
&=\begin{bmatrix} a_{11}c_{11} BD+a_{12}c_{21}BD & a_{11}c_{12} BD+a_{12}c_{22}BD\\
a_{21}c_{11} BD+a_{22}c_{21}BD & a_{21}c_{12} BD+a_{22}c_{22}BD
\end{bmatrix}\\[8pt]
&=\begin{bmatrix} a_{11}c_{11} +a_{12}c_{21} & a_{11}c_{12} +a_{12}c_{22}\\
a_{21}c_{11} +a_{22}c_{21} & a_{21}c_{12} +a_{22}c_{22}
\end{bmatrix}BD\\[8pt]
&=(AC)\otimes(BD)
\end{align}

Претпоставимо да је ова особина тачна за матрице мањих димензија Нека су сада матрице $A$ и $C$ дате конформном блоковском поделом за множење $AC,$ а саме поделе су $2\times 2$ на матрице за које је тврђење тачно. Тада је

\begin{align}
(A\otimes B)(C\otimes D)&=\begin{bmatrix}A_{11}\otimes B&A_{12}\otimes  B\\A_{21}\otimes  B&A_{22}\otimes  B\end{bmatrix}
\begin{bmatrix}C_{11}\otimes  D&C_{12}\otimes  D\\C_{21}\otimes  D&C_{22}\otimes  D\end{bmatrix}\\[8pt]
&=\begin{bmatrix} 
(A_{11}\otimes  B)(C_{11}\otimes D)+(A_{12}\otimes  B)(C_{21}\otimes D) & 
(A_{11}\otimes  B)(C_{12}\otimes D)+(A_{12}\otimes  B)(C_{22}\otimes D)\\
(A_{21}\otimes  B)(C_{11}\otimes D)+(A_{22}\otimes  B)(C_{21}\otimes D) & 
(A_{21}\otimes  B)(C_{12}\otimes D)+(A_{22}\otimes  B)(C_{22}\otimes D)
\end{bmatrix}\\[8pt]
&=\begin{bmatrix} 
(A_{11}C_{11}+A_{12}C_{21})\otimes BD & (A_{11}C_{12}+A_{12}C_{22})\otimes BD\\
(A_{21}C_{11}+A_{22}C_{21})\otimes BD & (A_{11}C_{12}+A_{22}C_{22})\otimes BD
\end{bmatrix}\\[8pt]
&=\begin{bmatrix} 
A_{11}C_{11}+A_{12}C_{21} & A_{11}C_{12}+A_{12}C_{22}\\
A_{21}C_{11}+A_{22}C_{21} & A_{11}C_{12}+A_{22}C_{22}
\end{bmatrix}\otimes BD\\[8pt]
&=(AC)\otimes(BD)
\end{align}

На основу принципа математичке индукције закључујемо да ова особина Кронекеровог производа важи за све матрице $A,B,C,D$ чије димезије дозвољавају рачунање производа $AC$ и $BD.$

**Пример 11.** Последица четврте особине Кронекеровог производа је да у случају регуларних квадратних матрица $A\in\mathcal{M}_{n\times n}$ и $B\in\mathcal{M}_{m\times m}$ имамо
$$(A\otimes B)(A^{-1}\otimes B^{-1})=I_n\otimes I_m=I_{nm}.$$

**Задатак 8.** Нека су дате три квадратне матрице $A,B,C\in\mathcal{M}_{n\times n}$ и означимо са $B_{[1]}$  векторизацију матрице $B$ дуж колона. Показати једнакост
$$(ABC)_{[1]}=(C^T\otimes A)\,B_{[1]}.$$

**Решење :**

Уведимо ознаке колона матрица $B$ и $C,$
\begin{align}
B&=\left[\begin{array}{c|c|c|c}
b_{11}&b_{12}&\dots&b_{1n}\\
b_{21}&b_{22}&\dots&b_{2n}\\
\vdots&\vdots&&\vdots\\
b_{n1}&b_{n2}&\dots&b_{nn}
\end{array}\right]
=\left[\begin{array}{c|c|c|c}
\phantom{W}&\phantom{W}&\phantom{WW}&\phantom{W}\\
B_1&B_2&\dots&B_n\\
\phantom{W}&\phantom{W}&\phantom{WW}&\phantom{W}
\end{array}\right]
\quad\Longrightarrow\quad
B_{[1]}=\left[\begin{array}{c}
B_1\\\hline B_2\\\hline \vdots\\\hline B_n
\end{array}
\right]
,
\\
C&=\left[\begin{array}{c|c|c|c}
c_{11}&c_{12}&\dots&c_{1n}\\
c_{21}&c_{22}&\dots&c_{2n}\\
\vdots&\vdots&&\vdots\\
c_{n1}&c_{n2}&\dots&c_{nn}
\end{array}\right]
=\left[\begin{array}{c|c|c|c}
\phantom{W}&\phantom{W}&\phantom{WW}&\phantom{W}\\
C_1&C_2&\dots&C_n\\
\phantom{W}&\phantom{W}&\phantom{WW}&\phantom{W}
\end{array}\right]
\quad\Longrightarrow\quad
C^T=\left[\begin{array}{c}
\phantom{WW}C_1^T\phantom{WW}\\\hline
\phantom{WW}C_2^T\phantom{WW}\\\hline
\vdots\\\hline
\phantom{WW}C_n^T\phantom{WW}
\end{array}
\right],\\
C^T\otimes A&=\left[\begin{array}{c}
\phantom{W}C_1^T\otimes A\phantom{W}\\\hline
\phantom{W}C_2^T\otimes A\phantom{W}\\\hline
\vdots\\\hline
\phantom{W}C_n^T\otimes A\phantom{W}
\end{array}
\right]\quad\Longrightarrow\quad
(C^T\otimes A)\,B_{[1]}=\left[\begin{array}{c}
(C_1^T\otimes A)\,B_{[1]}\\\hline
(C_2^T\otimes A)\,B_{[1]}\\\hline
\vdots\\\hline
(C_n^T\otimes A)\,B_{[1]}
\end{array}
\right]
.
\end{align}


\begin{align}
(C_i\otimes A)\,B_{[1]}&=\begin{bmatrix}c_{1i}A&c_{2i}A&\dots&c_{ni}A\end{bmatrix}
\left[\begin{array}{c}
B_1\\\hline B_2\\\hline \vdots\\\hline B_n
\end{array}
\right]\\
&=c_{1i}\underbrace{AB_1}_{\mbox{прва колона матрице }AB}+c_{2i}\underbrace{AB_2}_{\mbox{друга колона матрице }AB}
+\dots+c_{ni}\underbrace{AB_n}_{n\mbox{-та колона матрице }AB}\\
&=\left[\begin{array}{c|c|c|c}
\phantom{W}&\phantom{W}&\phantom{WW}&\phantom{W}\\
AB_1&AB_2&\dots&AB_n\\
\phantom{W}&\phantom{W}&\phantom{WW}&\phantom{W}
\end{array}\right]
\begin{bmatrix}c_{1i}\\c_{2i}\\\vdots\\c_{ni}\end{bmatrix}=\underbrace{ABC_i}_{i\mbox{-та колона матрице }ABC}
\end{align}

Закључујемо да матрица $(C^T\otimes A)\,B_{[1]}$ садржи поређане колоне матрице $ABC.$ Тиме је доказано да је $(ABC)_{[1]}=(C^T\otimes A)\,B_{[1]}.$

Слично, за векторизацију дуж врста имамо:
$$(ABC)_{[0]}=(C^TB^TA^T)_{[1]}=(A\otimes C^T)\,B_{[1]}^T=(A\otimes C^T)\,B_{[0]}.$$

## Кронекерова сума матрица

**Дефиниција 2.** Нека су $A=[a_{ij}]\in\mathcal{M}_{m\times m}$ и $B=[b_{kl}]\in\mathcal{M}_{n\times n}$ две квадратне матрице. Кронекерова сума $\oplus$ матрица $A$ и $B$ је матрица димензије $mn\times mn$ дата изразом:
$$A\oplus B=A\otimes I_n+I_m\otimes B.$$

Израз Кронекеровог збира кроз елементе матрица гласи:
\begin{align}
A\oplus B&=A\otimes I_n+I_m\otimes B
=\begin{bmatrix}
a_{11}I_n&a_{12}I_n&\dots&a_{1m}I_n\\
a_{21}I_n&a_{22}I_n&\dots&a_{2m}I_n\\
\vdots&\vdots&&\vdots\\
a_{m1}I_n&a_{m2}I_n&\dots&a_{mm}I_n
\end{bmatrix}+
\begin{bmatrix}
B&O&\dots&O\\O&B&\dots&O\\
\vdots&\vdots&&\vdots\\
O&O&\dots&B
\end{bmatrix}\\[8pt]
&=\begin{bmatrix}
B+a_{11}I_n&a_{12}I_n&\dots&a_{1m}I_n\\
a_{21}I_n&B+a_{22}I_n&\dots&a_{2m}I_n\\
\vdots&\vdots&&\vdots\\
a_{m1}I_n&a_{m2}I_n&\dots&B+a_{mm}I_n
\end{bmatrix}
\end{align}

Специјално, нека је $A=[a_{ij}]\in\mathcal{M}_{n\times n}.$ Тада је
\begin{align}
A\oplus A&=A\otimes I_n+I_n\otimes A=\begin{bmatrix}
A+a_{11}I_n&a_{12}I_n&\dots&a_{1n}I_n\\
a_{21}I_n&A+a_{22}I_n&\dots&a_{2n}I_n\\
\vdots&\vdots&&\vdots\\
a_{n1}I_n&a_{n2}I_n&\dots&A+a_{nn}I_n
\end{bmatrix}
\end{align}

## Катри-Рао производ матрица

**Дефиниција 3.** Нека су две матрице $A$ и $B$ дате у блок форми исте блоковске димензије $\mu\times\nu.$ Катри-Рао производ $A\ast B$ је матрица блоковске димензије $\mu\times\nu$ чији су блокови једнаки Кронекеровом производу одговарајућих блокова матрица $A$ и $B.$

Нека су блок форме матрица $A=\begin{bmatrix}
A_{11} & A_{12} & \dots &A_{1\nu}\\
A_{21} & A_{22} & \dots &A_{2\nu}\\
\vdots & \vdots & \ddots & \vdots\\
A_{\mu1} & A_{\mu2} & \dots &A_{\mu \nu}
\end{bmatrix}$ и $B=\begin{bmatrix}
B_{11} & B_{12} & \dots &B_{1\nu}\\
B_{21} & B_{22} & \dots B_{2\nu}\\
\vdots & \vdots & \ddots & \vdots\\
B_{\mu1} & B_{\mu2} & \dots &B_{\mu \nu}
\end{bmatrix},$ тада је
$$A\star B=\begin{bmatrix}
A_{11}\otimes B_{11} & A_{12}\otimes B_{12} & \dots &A_{1\nu}\otimes B_{1\nu}\\
A_{21}\otimes B_{21} & A_{22}\otimes B_{22} & \dots &A_{2\nu}\otimes B_{2\nu}\\
\vdots & \vdots & \ddots & \vdots\\
A_{\mu1}\otimes B_{\mu1} & A_{\mu2}\otimes B_{\mu2} & \dots &A_{\mu \nu}\otimes B_{\mu \nu}
\end{bmatrix}$$

**Пример 12.** Матрице $A=\left[\begin{array}{c|cc}
	1&2&3\\ \hline 		4&5&6\\7&8&9
	\end{array}\right]=\begin{bmatrix}A_{11}&A_{12}\\A_{21}&A_{22}\end{bmatrix}$ и $
	B=\left[\begin{array}{cc|cc}
	1&2&3&4\\ \hline 5&6&7&8\\9&10&11&12
	\end{array}\right]=\begin{bmatrix}B_{11}&B_{12}\\B_{21}&B_{22}\end{bmatrix}$ дате су у блок форми $2\times2.$ Резултат Катри-Рао производа биће исте блок форме, али су блокови далеко већих димезија.
    $$A\star B=\begin{bmatrix}A_{11}\otimes B_{11}&A_{12}\otimes B_{12}\\
    A_{21}\otimes B_{21}&A_{22}\otimes B_{22}
    \end{bmatrix}.$$

In [20]:
A=np.arange(1,10).reshape(3,3)
B=np.arange(1,13).reshape(3,4)
C11=np.kron(A[:1,:1],B[:1,:2])
C11

array([[1, 2]])

In [21]:
C12=np.kron(A[:1,1:],B[0,2:])
C12

array([[ 6,  8,  9, 12]])

In [22]:
C21=np.kron(A[1:,:1],B[1:,:2])
C21

array([[20, 24],
       [36, 40],
       [35, 42],
       [63, 70]])

In [23]:
C22=np.kron(A[1:,1:],B[1:,2:])
C22

array([[ 35,  40,  42,  48],
       [ 55,  60,  66,  72],
       [ 56,  64,  63,  72],
       [ 88,  96,  99, 108]])

In [24]:
C=np.block([[C11,C12],[C21,C22]])
C

array([[  1,   2,   6,   8,   9,  12],
       [ 20,  24,  35,  40,  42,  48],
       [ 36,  40,  55,  60,  66,  72],
       [ 35,  42,  56,  64,  63,  72],
       [ 63,  70,  88,  96,  99, 108]])

**Дефиниција 4.** За две матрице $A=[a_{ij}]\in\mathcal{M}_{m\times n}$ и $B=[b_{kl}]\in\mathcal{M}_{p\times n},$ са истим бројем колона, њихов Катри-Рао производ дуж колона $\odot$ је операција којом се добија матрица $C=A\odot B\in\mathcal{M}_{mp\times n},$ а чији садржај чине Кронекерови производи парова колона две матрице. 

Ако уведемо ознаке колона
$$A=\left[\begin{array}{c|c|c|c}
\phantom{W}&\phantom{W}&
\phantom{WW}&\phantom{W}\\
A_1&A_2&\dots&A_n\\
\phantom{W}&\phantom{W}&
\phantom{W}&\phantom{W}
\end{array}\right],\qquad 
B=\left[\begin{array}{c|c|c|c}
\phantom{W}&\phantom{W}&
\phantom{W}&\phantom{W}\\
B_1&B_2&\dots&B_n\\
\phantom{W}&\phantom{W}&
\phantom{WW}&\phantom{W}
\end{array}\right],
$$
тада су колоне матрице $C=A\odot B$ дате са:
$$C=A\odot B=A=\left[\begin{array}{c|c|c|c}
\phantom{W}&\phantom{W}&
\phantom{WWW}&\phantom{W}\\
A_1\otimes B_1&A_2\otimes B_2&\dots&A_n\otimes B_n\\
\phantom{W}&\phantom{W}&
\phantom{W}&\phantom{W}
\end{array}\right],.$$

**Пример 13.** Матрице $A=\left[\begin{array}{c|c|c}
	1&2&3\\	4&5&6\\7&8&9
	\end{array}\right]$ и $
	B=\left[\begin{array}{c|c|c}
	1&5&9\\ 2&6&10\\3&7&11\\ 4&8&12
	\end{array}\right]$ имају једнак број колона. Резултат Катри-Рао производа дуж колона је матрица са истим бројем колона, али су оне далеко већих димезија.

In [25]:
B=B.T
C=np.empty((12,3))
for i in range(3):
    C[:,i]=np.kron(A[:,i],B[:,i])
C    

array([[  1.,  10.,  27.],
       [  2.,  12.,  30.],
       [  3.,  14.,  33.],
       [  4.,  16.,  36.],
       [  4.,  25.,  54.],
       [  8.,  30.,  60.],
       [ 12.,  35.,  66.],
       [ 16.,  40.,  72.],
       [  7.,  40.,  81.],
       [ 14.,  48.,  90.],
       [ 21.,  56.,  99.],
       [ 28.,  64., 108.]])