# Значајне класе матрица

Садржај:
1. [Троугаоне матрице](#Троугаоне-матрице)
1. [Симетричне и ортогоналне матрице](#Симетричне-и-ортогоналне-матрице)

In [1]:
import numpy as np

## Троугаоне матрице

<div class="alert alert-block alert-info">
<b>Напомена:</b> Због краћег означавања користићемо ознаку скупа $\{0,1,\dots,n-1\}=[n].$ Такође, то подразумева, за индексирање елемената вектора и матрица користимо Python начин индексирања.
    </div>

**Дефиниција 1.** а) Матрица $A=[a_{ij}]\in\mathcal{M}_{n\times m}$ је горње троугаона уколико су сви елементи испод главне дијагонале једнаки нули, тј. ако је $$\forall i\in[n],\ \forall j\in[m],\qquad i>j\Longrightarrow a_{ij}=0.$$

б) Матрица $A=[a_{ij}]\in\mathcal{M}_{n\times m}$ је доње троугаона уколико су сви елементи изнад главне дијагонале једнаки нули, тј. ако је $$\forall i\in[n],\ \forall j\in[m],\qquad  i<j\Longrightarrow a_{ij}=0.$$

в) Матрица је троугаона уколико је горње или доње троугаона матрица.

г) Матрица $A=[a_{ij}]\in\mathcal{M}_{n\times m}$ која је истовремено горње и доње троугаона је дијагонална матрица, 
$$\forall i\in[n],\ \forall j\in[m],\qquad  i\neq j\Longrightarrow a_{ij}=0.$$

**Дефиниција 2.** За троугаону матрицу кажемо да је унитроугаона уколико су сви елементи на главној дијагонали јединице.

**Пример 1.** Унитроугаоне матрице се следеће квадратне или правоугаоне матрице.
\begin{align}
&A=\begin{bmatrix}1&0&0\\2&1&0\\0&0&1\end{bmatrix},
&&B=\begin{bmatrix}1&0&0&0\\2&1&0&0\\0&0&1&0\end{bmatrix},\\
&A^T=\begin{bmatrix}1&2&0\\0&1&0\\0&0&1\end{bmatrix},
&&B^T=\begin{bmatrix}1&2&0\\0&1&0\\0&0&1\\0&0&0\end{bmatrix}.
\end{align}

**Последица 1.** Ако је матрица $A$ доње троугаона, тада је $A^T$ горње троугаона, и обрат.

**Задатак 1.** По угледу на дефиниције троугаоних матрица написати услов да је матрица

а) доње бидијагонална,

б) горње бидијагонална.

**Решење :**

а) Доње бидијагонална матрица је доње троугаона матрица која има ненула елементе само на главној дијагонали и на суседној дијагонали испод ње. То можемо да прикажемо наредном шемом
$$L_B=\begin{bmatrix}
l_{00}&0&0&0&\dots\\ 
l_{10}&l_{11}&0&0&\dots\\ 
0&l_{21}&l_{22}&0&\dots\\
\vdots&&\ddots&\ddots&
\end{bmatrix}\in\mathcal{M}_{m\times n}.$$

Пратећи промене индекса врста $i$ и колона $j,$ закључујемо да се нуле у доње бидијагонаној матрици, тј. $a_{ij}=0,$ налазе на позицијама
$$j>i\quad\text{ или }\quad i>j+1.$$

б) Горње бидијагонална матрица је
$$R_B=\begin{bmatrix}
r_{00}&r_{01}&0&0&\dots\\ 
0&r_{11}&r_{12}&0&\dots\\ 
0&0&r_{22}&r_{23}&\dots\\
\vdots&&&\ddots&\ddots
\end{bmatrix}\in\mathcal{M}_{m\times n}.$$
Слично претходној анализи, за индекс врсте $i$ и колоне $j,$ нуле у горње бидијагоналој матрици налазе се на позицијама
$$j<i\quad\text{ или }\quad i+1<j.$$

**Пример 2.** Веома важну класу квадратних троугаоних матрица чине Фробенијусове матрице. Размотрићемо једну подкласу Гаусове трансформације. То су доње троугаоне матрице са особинама:

- сви елементи на главној дијагонали су јединице (унитроугаона матрица),
- највише једна колона ове матрице може имати ненула елементе.


Дајемо неке конкретне примере Гаусове трансформације:
$$\begin{bmatrix} 1&0&0\\-1&1&0\\2&0&1\end{bmatrix},\qquad
\begin{bmatrix}  1&0&0&0\\0&1&0&0\\0&3&1&0\\0&2&0&1\end{bmatrix},\dots$$

Овако дефинисане Фробенијусове матрице добијају се ажурирањем једне колоне јединичне матрице, испод њене главне дијагонале. На примеру датих матрица то би значило:
\begin{align}
    \begin{bmatrix} 1&0&0\\-1&1&0\\2&0&1\end{bmatrix}&=
    \begin{bmatrix} 1&0&0\\0&1&0\\0&0&1\end{bmatrix}
    +\begin{bmatrix}0\\-1\\2\end{bmatrix}\begin{bmatrix}1&0&0\end{bmatrix},\\
\begin{bmatrix}  1&0&0&0\\0&1&0&0\\0&3&1&0\\0&2&0&1\end{bmatrix}
&=\begin{bmatrix}  1&0&0&0\\0&1&0&0\\0&0&1&0\\0&0&0&1\end{bmatrix}
+\begin{bmatrix}0\\0\\3\\2\end{bmatrix}\begin{bmatrix}0&1&0&0\end{bmatrix}.
\end{align}

In [2]:
I=np.eye(3)
v=np.array([0,-1,2])
I+np.outer(v,I[0])

array([[ 1.,  0.,  0.],
       [-1.,  1.,  0.],
       [ 2.,  0.,  1.]])

In [3]:
I=np.eye(4)
v=np.array([0,0,3,2])
I+np.outer(v,I[1])

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 3., 1., 0.],
       [0., 2., 0., 1.]])

Дакле, ако је Фробенијусова матрица $L_k\in\mathcal{M}_{n\times n}$ настала ажурирањем $k-$те колоне јединичне матрице $I$ тада је
$$L_k=I+ve_k^T,\qquad 
v=\begin{bmatrix}0\\\vdots\\0\\x_{k+1}\\x_{k+2}\\\vdots\\
x_n\end{bmatrix},\quad 
e_k=\begin{bmatrix}0\\\vdots\\1\\0\\0\\\vdots\\0\end{bmatrix}.$$

Јасно је да су Гаусове матрице регуларне. Приметимо да инверзне матрице горе наведених Фробенијусових матрица гласе
$$\begin{bmatrix} 1&0&0\\1&1&0\\-2&0&1\end{bmatrix},\qquad
\begin{bmatrix}  1&0&0&0\\0&1&0&0\\0&-3&1&0\\0&-2&0&1\end{bmatrix},$$
тј. добијају се променом знака вандијагоналних елемената полазне матрице.
Ово је опште правило које следи из вредности скаларног производа $v^Te_k=e_k^Tv=0:$
\begin{align}
    (I+ve_k^T)(I-ve_k^T)&=I+ve_k^T-ve_k^T-v(e_k^Tv)e_k^T\\
    &=I-0(ve_k^T)=I.
\end{align}

Такође, инверзна матрица Гаусове трансформације је и последица општије особине блок форме:
$$\begin{bmatrix}I_n&O\\A&I_m\end{bmatrix}\begin{bmatrix}I_n&O\\-A&I_m\end{bmatrix}=\begin{bmatrix}I_n&O\\O&I_m\end{bmatrix}.$$

Осим ажурирања колона, Фробенијусове матрице могу да се дефинишу и као доње троугаоне где се врши ажурирање јединичне матрице дуж једне врсте. Такође, Фробенијусове матрице могу да се дефинишу и као горње троугаоне матрице са ажурирањем $I$ дуж врсте или колоне. Својство инверзне матрице се у свим случајевима задржава.

**Пример 3.** Блок форма нам помаже и да покажемо индукцијом још неке особине троугаоних матрица:

а) Производ две доње троугаоне матрице је доње троугаона матрица.

б) Производ две горње троугаоне матрице је горње троугаона матрица.

в) Инверзна матрица доње троугаоне матрице је доње троугаона.

г) Инверзна матрица горње троугаоне матрице је горње троугаона.

а) Нека су $A,B\in\mathcal{M}_{2\times2}$ две доње троугаоне матрице.
\begin{align}
&A=\begin{bmatrix}a_{11}&0\\a_{21}&a_{22}\end{bmatrix},\qquad 
B=\begin{bmatrix}b_{11}&0\\b_{21}&b_{22}\end{bmatrix},\\
&AB=\begin{bmatrix}a_{11}b_{11}&0\\a_{21}b_{11}+a_{22}b_{21}&a_{22}b_{22}\end{bmatrix}.
\end{align}
Видимо да је њихов производ поново доње троугаона матрица. 

Претпоставимо да је тврђење тачно за све квадратне доње троугаоне матрице димензије $1\leq k\leq n.$ Тада за доње троугаоне матрице димезије $n+1$ користимо блок поделу:
$$A=\begin{bmatrix}A_{11}&O\\A_{21}&A_{22}\end{bmatrix},\qquad 
B=\begin{bmatrix}B_{11}&O\\B_{21}&B_{22}\end{bmatrix},$$
где су дијагонални блокови ових матрица квадаратне доње троугаоне матрице. Њихов производ гласи
$$AB=\begin{bmatrix}A_{11}B_{11}&O\\A_{21}B_{11}+A_{22}B_{21}&A_{22}B_{22}\end{bmatrix},$$
па су дијагонални блокови према индукцијској хипотези поново доње троугаоне матрице. Закључујемо да је $AB$ и сама доње троугаона матрица.

б) Последица показаног под а) и особине транспоновања $(AB)^T=B^TA^T.$

в) Приметимо прво да је троугаона матрица регуларна акко су сви дијагонални елементи различити од нуле.

Нека је $A=\begin{bmatrix}a_{11}&0\\a_{21}&a_{22}\end{bmatrix}$ регуларна матрица. Тада је одговарајућа инверзна матрица $A^{-1}=\dfrac{1}{a_{11}a_{22}}\begin{bmatrix}a_{22}&0\\-a_{21}&a_{11}\end{bmatrix}$ поново доње троугаона.

Претпоставимо да је тврђење тачно за сваку регуларну доње троугаону матрицу димензије $1\leq k\leq n.$ Тада за доње троугаоне матрице димензије $n+1$ користимо блок поделу:
$$A=\begin{bmatrix}A_{11}&O\\A_{21}&A_{22}\end{bmatrix},$$
где су дијагонални блокови регуларне доње троугаоне матрице. Покажимо да је $A^{-1}=\begin{bmatrix}A_{11}^{-1}&O\\-A_{22}^{-1}A_{21}A_{11}^{-1}&A_{22}^{-1}\end{bmatrix},$ што свакако представља поново доње троугаону матрицу према индукцијској хипотези.

$$\begin{bmatrix}A_{11}&O\\A_{21}&A_{22}\end{bmatrix}\begin{bmatrix}A_{11}^{-1}&O\\-A_{21}&A_{22}^{-1}\end{bmatrix}
=\begin{bmatrix}I&O\\A_{21}A_{11}^{-1}-A_{22}A_{22}^{-1}A_{21}A_{11}^{-1}&I\end{bmatrix}
=\begin{bmatrix}I&O\\O&I\end{bmatrix}
$$

г) Последица показаног под в) и особине транспоновања $(AB)^T=B^TA^T,\quad (A^{-1})^T=(A^T)^{-1}.$

**Задатак 2.** Означимо специјалну врсту доње троугаоних квадратних матрица $L_n(k)\in\mathcal{M}_{n\times n},\ k\geq0:$
\begin{align}
L=[l_{ij}]\in L_n(k)&\Longleftrightarrow\  \big(i-j<k\ \Longrightarrow\ l_{ij}=0\big)\\ 
&\Longleftrightarrow\  L=\begin{bmatrix} 0&0&\dots&0&0&0&\dots&0\\
\vdots&\vdots&&\vdots&\vdots&\vdots&&\vdots\\
	0&0&\dots&0&0&0&\dots&0\\
	l_{k0}&0&\dots&0&0&0&\dots&0\\
	l_{k+1\,0}&l_{k+1\,1}&\dots&0&0&0&\dots&0\\
	\vdots&\vdots&\ddots&\vdots&\vdots&\vdots&&\vdots\\
	l_{n-2\,0}&l_{n-2\,1}&\dots&l_{n-2\,n-k-2}&0&0&\dots&0\\
	l_{n-1\,0}&l_{n-1\,1}&\dots&l_{n-1\,n-k-2}&l_{n-1\,n-k-1}&0&\dots&0\end{bmatrix}
    =\left[\begin{array}{cc}O_{k\times(n-k)}&O_{k\times k}\\
    L_{(n-k)\times(n-k)}&O_{(n-k)\times k}\end{array}
    \right].
\end{align}
У блок форми $L_{(n-k)\times(n-k)}\in L_n(0)$ је доње троугаона матрица.

Показати: $A\in L_n(k),\ B\in L_n(s)\ \Longrightarrow\ 
	AB\in L_n(m),$ где је $m\geq\max\{k,s\}.$

Као пример користимо матрице овог типа са свим ненула елемнтима једнаким $1.$ Наредбом `tril` добијамо жељену форму. Кодом проверавамо резултате за различите вредности $k$ и $s.$

In [4]:
n=5
for k in range(n):
    for s in range(n):
        A=np.tril(np.ones((n,n)),-k)
        B=np.tril(np.ones((n,n)),-s)
        print("A=",A)
        print("B=",B)
        print("AB=",A@B)
        print("BA=",B@A)

A= [[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]
B= [[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]
AB= [[1. 0. 0. 0. 0.]
 [2. 1. 0. 0. 0.]
 [3. 2. 1. 0. 0.]
 [4. 3. 2. 1. 0.]
 [5. 4. 3. 2. 1.]]
BA= [[1. 0. 0. 0. 0.]
 [2. 1. 0. 0. 0.]
 [3. 2. 1. 0. 0.]
 [4. 3. 2. 1. 0.]
 [5. 4. 3. 2. 1.]]
A= [[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]
B= [[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]]
AB= [[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [2. 1. 0. 0. 0.]
 [3. 2. 1. 0. 0.]
 [4. 3. 2. 1. 0.]]
BA= [[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [2. 1. 0. 0. 0.]
 [3. 2. 1. 0. 0.]
 [4. 3. 2. 1. 0.]]
A= [[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]
B= [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]]
AB= [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.

**Решење :**

Покажимо прво да за матрицу $A=[a_{ij}]\in L_n(0)$ и $B=[b_{ij}]\in L_n(s),\ s\geq0$ важи 
$AB,\ BA\in L_n(s).$
За $s=0$ тврђење се своди на опис производа две троугаоне матрице, што је познато да већ представља доње троугаону матрицу.

Нека је сада $s>0$ и $B=\left[\begin{array}{cc}O_{s\times(n-s)}&O_{s\times s}\\
    B_{(n-s)\times(n-s)}&O_{(n-s)\times s}\end{array}
    \right]$ одговарајућа блок репрезентација. За матрицу $A$ направимо конформну блок поделу за множење,
$$A=\left[\begin{array}{cc}A_{s\times s}&O_{s\times(n-s)}\\
    A_{(n-s)\times s}&A_{(n-s)\times(n-s)}\end{array}
    \right]
    =\left[\begin{array}{cc}A_{(n-s)\times(n-s)}'&O_{(n-s)\times s}\\
    A_{s\times(n-s)}'&A_{s\times s}'\end{array}
    \right],$$ 
где су дијагонални блокови доње троугаоне матрице.  Тада је

\begin{align}
AB&=\left[\begin{array}{cc}A_{s\times s}&O_{s\times(n-s)}\\
    A_{(n-s)\times s}&A_{(n-s)\times(n-s)}\end{array}
    \right]
    \left[\begin{array}{cc}O_{s\times(n-s)}&O_{s\times s}\\
    B_{(n-s)\times(n-s)}&O_{(n-s)\times s}\end{array}
    \right]
    =\left[\begin{array}{cc}O_{s\times(n-s)}&O_{s\times s}\\
    A_{(n-s)\times(n-s)}B_{(n-s)\times(n-s)}&O_{(n-s)\times s}\end{array}
    \right],\\
    BA&=\left[\begin{array}{cc}O_{s\times(n-s)}&O_{s\times s}\\
    B_{(n-s)\times(n-s)}&O_{(n-s)\times s}\end{array}
    \right]
    \left[\begin{array}{cc}A_{(n-s)\times(n-s)}'&O_{(n-s)\times s}\\
    A_{s\times(n-s)}'&A_{s\times s}'\end{array}
    \right]
    =\left[\begin{array}{cc}O_{s\times(n-s)}&O_{s\times s}\\
    B_{(n-s)\times(n-s)}A_{(n-s)\times(n-s)}'&O_{(n-s)\times s}\end{array}
    \right].
\end{align}

Изрази $A_{(n-s)\times(n-s)}B_{(n-s)\times(n-s)}$ и $B_{(n-s)\times(n-s)}A_{(n-s)\times(n-s)}'$ представљају производ вде доње троугаоне матрице, па добијене блок форме потврђују $AB,\ BA\in L_n(s).$

Нека су сада $A=[a_{ij}]\in L_n(k)\subseteq\mathcal{M}_{n\times n},\ k>0$ и $B=[b_{ij}]\in L_n(s)\subseteq\mathcal{M}_{n\times n},\ s>0$ доње троугаоне матрице одговарајућег облика, дате својом блок формом
$$A=\left[\begin{array}{cc}O_{k\times(n-k)}&O_{k\times k}\\
    A_{(n-k)\times(n-k)}&O_{(n-k)\times k}\end{array}
    \right],\qquad
    B=\left[\begin{array}{cc}O_{s\times(n-s)}&O_{s\times s}\\
    B_{(n-s)\times(n-s)}&O_{(n-s)\times s}\end{array}
    \right].$$    

Уколико је $k\geq s,$ матрицу $B$ можемо да посматрамо у конформној блок форми 
$$B=\left[\begin{array}{cc}O_{s\times(n-s)}&O_{s\times s}\\
    B_{(n-s)\times(n-s)}&O_{(n-s)\times s}\end{array}
    \right]
    =\left[\begin{array}{cc}B_{(n-k)\times(n-k)}&O_{(n-k)\times k}\\
    B_{k\times(n-k)}&B_{k\times k}\end{array}
    \right],$$    
где су $B_{(n-k)\times(n-k)},B_{k\times k}$ доње троугаоне матрице или нула-матрице. Блок $O_{(n-k)\times k}$ знамо да је нула-матрица с обзиром да се дијагонала матрице $B$ простире дуж дијагонала блокова $B_{(n-k)\times(n-k)},B_{k\times k}.$ Тада је

\begin{align}
AB&=\left[\begin{array}{cc}O_{k\times(n-k)}&O_{k\times k}\\
    A_{(n-k)\times(n-k)}&O_{(n-k)\times k}\end{array}
    \right]
    \left[\begin{array}{cc}B_{(n-k)\times(n-k)}&O_{(n-k)\times k}\\
    B_{k\times(n-k)}&B_{k\times k}\end{array}
    \right]
    =\left[\begin{array}{cc}O_{k\times(n-k)}&O_{k\times k}\\
    A_{(n-k)\times(n-k)}B_{(n-k)\times(n-k)}&O_{(n-k)\times k}\end{array}
    \right] \in L_n(m), \mbox{ где је } m\geq k.
\end{align}

Слично, у случају $k<s$ матрицу $A$ представимо у конформној блок форми 
$$A=\left[\begin{array}{cc}O_{k\times(n-k)}&O_{k\times k}\\
    A_{(n-k)\times(n-k)}&O_{(n-k)\times k}\end{array}
    \right]
    =\left[\begin{array}{cc}A_{s\times s}&O_{s\times(n-s)}\\
    A_{(n-s)\times s}&A_{(n-s)\times(n-s)}\end{array}
    \right],$$    
где су $A_{(n-s)\times(n-s)},A_{s\times s}$ доње троугаоне матрице или нула-матрице. Тада је

\begin{align}
AB&=\left[\begin{array}{cc}A_{s\times s}&O_{s\times(n-s)}\\
    A_{(n-s)\times s}&A_{(n-s)\times(n-s)}\end{array}
    \right]
    \left[\begin{array}{cc}
    O_{s\times(n-s)}&O_{s\times s}\\
    B_{(n-s)\times(n-s)}&O_{(n-s)\times s}
    \end{array}    \right]
    =\left[\begin{array}{cc}
    O_{s\times(n-s)}&O_{s\times s}\\
    A_{(n-s)\times(n-s)}B_{(n-s)\times(n-s)}&O_{(n-s)\times s}
    \end{array}    \right] \in L_n(m), \mbox{ где је } m\geq s.
\end{align}

## Симетричне и ортогоналне матрице

**Дефиниција 3.** 	а) Када за матрицу $A$ важи $A^T=A,$ тада је $A$ симетрична матрица. 
		
Уколико је $A=-A^T,$ за матрицу $A$ кажемо да је косо-симетрична.
		
б) Ако за реалну матрицу $A$ важи $A^TA=AA^T=I,$ тада $A$ зовемо ортогонална матрица.

**Последица 2.** а)  Симетрична, косо-симетрична и  ортогонална матрица су квадратне матрице.

б) Уколико је матрица $A=[a_{ij}]$ косо-симетрична, дијагонални елементи $a_{ii}$ су једнаки нули.

в) Ортогонална матрица $A$ је регуларна матрица чије је инверз матрица $A^T.$

**Пример 4.** Матрица $A=\begin{bmatrix} 1&2&1\\2&5&-1\\1&-1&0\end{bmatrix}$ је симетрична.	

In [5]:
A=np.array([[1,2,1],[2,5,-1],[1,-1,0]])
A-A.T

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Матрица $B=\begin{bmatrix}0&1&2\\-1&0&-3\\-2&3&0\end{bmatrix}$ је косо-симетрична.

In [6]:
B=np.array([[0,1,2],[-1,0,-3],[-2,3,0]])
B+B.T

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Јединична матрица $I$ је симетрична и ортогонална.
$$I=I^T=I^2=II^T=I^TI.$$

**Пример 5.** Нека је $v\in\mathbb{R}^n$  вектор. Тада спољашњи производ $vv^T$ представља симетричну матрицу. Слично, за $A\in\mathcal{M}_{m\times n}$ важи да је $A^TA$ симетрична матрица.
\begin{align}
    \big(vv^T\big)^T&=\big(v^T\big)^Tv^T=vv^T,\\
    (A^TA)^T&=A^T(A^T)^T=A^TA.
\end{align}

In [7]:
print(v)
np.outer(v,v)

[0 0 3 2]


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 9, 6],
       [0, 0, 6, 4]])

In [8]:
A=np.arange(6).reshape(3,2)
A.T@A

array([[20, 26],
       [26, 35]])

In [9]:
A@A.T

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])

**Задатак 3.** Нека је $A\in\mathcal{M}_{n\times n}$ симетрична матрица и $B\in\mathcal{M}_{n\times m}$ произвољна матрица. Показати да су следеће матрице симетричне.
	$$B^TAB,\quad B^TB,\quad BB^T.$$

**Решење :**

\begin{align}
&(B^TAB)^T=B^TA^T(B^T)^T=B^TAB,\\
&(B^TB)^T=B^T(B^T)^T=B^TB,\\
&(BB^T)^T=(B^T)^TB^T=BB^T.
\end{align}

Добијене теоријске резултате описаћемо кроз пар рачунских примера.

In [10]:
B= np.array([[2,3,1], [0.3,4,-8], [4,2,0.8], [2,1,-4]])
B.T@B

array([[ 24.09,  17.2 ,  -5.2 ],
       [ 17.2 ,  30.  , -31.4 ],
       [ -5.2 , -31.4 ,  81.64]])

In [11]:
B@B.T

array([[14.  ,  4.6 , 14.8 ,  3.  ],
       [ 4.6 , 80.09,  2.8 , 36.6 ],
       [14.8 ,  2.8 , 20.64,  6.8 ],
       [ 3.  , 36.6 ,  6.8 , 21.  ]])

Симетричну матрицу креираћемо понављањем троугаоног дела око главне дијагонале.

In [12]:
M=np.tril(np.arange(9).reshape(3,3),-1)
A=np.eye(3)+M+M.T
print(A)
B@A@B.T

[[1. 3. 6.]
 [3. 1. 7.]
 [6. 7. 1.]]


array([[ 116.  , -202.9 ,  127.2 ,  -86.  ],
       [-202.9 , -389.51, -227.56, -209.7 ],
       [ 127.2 , -227.56,  129.44, -106.  ],
       [ -86.  , -209.7 , -106.  , -119.  ]])

**Задатак 4.** Нека је $A$ квадратна матрица, доказати да је 

а) $A+A^T$ симетрична матрица.

б) $A-A^T$ косо-симетрична матрица.

**Решење :**

а) $M=A+A^T\quad\Longrightarrow\quad M^T=(A+A^T)^T=A^T+A=A+A^T=M\quad\Longrightarrow\quad$ симетрична матрица.

б) $M=A-A^T\quad\Longrightarrow\quad M^T=(A-A^T)^T=A^T-A=-(A-A^T)=-M\quad\Longrightarrow\quad$ косо-симетрична матрица. 

Добијене теоријске резултате описаћемо кроз пар рачунских примера.

In [13]:
A=np.array([[-2,3,4], [3.3,-5,8], [3,7,0.8]])
A+A.T

array([[ -4. ,   6.3,   7. ],
       [  6.3, -10. ,  15. ],
       [  7. ,  15. ,   1.6]])

In [14]:
A-A.T

array([[ 0. , -0.3,  1. ],
       [ 0.3,  0. ,  1. ],
       [-1. , -1. ,  0. ]])

**Задатак 5.** Показати да се свака квадратна реална матрица $A$ може да напише у облику збира симетричне и косо-симетрична матрица.

**Решење :**

Уведимо ознаке $A_{s}=\dfrac{A+A^T}2$ и $A_{ks}=\dfrac{A-A^T}2\,.$ Тада је
\begin{align}
A_s^T&=\left(\dfrac{A+A^T}2\right)^T=\dfrac{A^T+(A^T)^T}2=\dfrac{A+A^T}2=A_s,\\
A_{ks}^T&=\left(\dfrac{A-A^T}2\right)^T=\dfrac{A^T-(A^T)^T}2=-\dfrac{A-A^T}2=-A_{ks},\\
A&=A_s+A_{ks}.
\end{align}

Добијене теоријске резултате описаћемо кроз рачунски пример.

In [15]:
print("A=",A)
As=(A+A.T)/2
Aks=(A-A.T)/2
print("As=",As)
print("Aks=",Aks)
print("A-(As+Aks)=",A-As-Aks)

A= [[-2.   3.   4. ]
 [ 3.3 -5.   8. ]
 [ 3.   7.   0.8]]
As= [[-2.    3.15  3.5 ]
 [ 3.15 -5.    7.5 ]
 [ 3.5   7.5   0.8 ]]
Aks= [[ 0.   -0.15  0.5 ]
 [ 0.15  0.    0.5 ]
 [-0.5  -0.5   0.  ]]
A-(As+Aks)= [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


**Дефиниција 4.**  Матрица пермутација или пермутациона матрица је квадратна бинарна матрица која има тачно по један елемент једнак $1$ у свакој врсти и колони, и нуле на преосталим позицијама.

**Пример 6.** Јединична матрица $I$ је матрица пермутације. Пермутацијом врста или колона јединичне матрице добијамо све остале пермутационе матрице. Уколико је $P$ пермутациона матрица тада је и $P^T$ пермутациона матрица.

In [16]:
I=np.eye(6)
I

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

Било којом пермутацијом скупа индекса $\{0,1,2,3,4,5\}$ можемо да формирамо нову пермутациону матрицу. 

In [17]:
permutacija=np.array([3,0,2,1,5,4])
P1=I[permutacija]
P1

array([[0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0.]])

Приметимо да је $P1^T$ матрица која се добија одговарајућом пермутацијом колона јединичне матрице.

In [18]:
P2=I[:,permutacija]
P1.T-P2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

Осим тога, индексирањем можемо да добијемо и инверзну пермутацију.
$$permutacija:\left(\begin{array}{cccccc} 0&1&2&3&4&5\\ 3&0&2&1&5&4\end{array}\right),\qquad
invperm:\left(\begin{array}{cccccc} 3&0&2&1&5&4\\ 0&1&2&3&4&5\end{array}\right)
.$$
$$permutacija\circ invperm=\left(\begin{array}{cccccc} 0&1&2&3&4&5\\ 0&1&2&3&4&5\end{array}\right),\qquad
invperm\circ permutacija=\left(\begin{array}{cccccc} 0&1&2&3&4&5\\ 0&1&2&3&4&5\end{array}\right).$$

In [19]:
invperm=np.empty(6,dtype=np.int)
invperm[permutacija]=np.arange(6)
invperm

array([1, 3, 2, 0, 5, 4])

In [20]:
permutacija[invperm]

array([0, 1, 2, 3, 4, 5])

In [21]:
invperm[permutacija]

array([0, 1, 2, 3, 4, 5])

Наредба којом можемо да генеришемо случајну пермутацију низа бројева `permutation(x)` садржи библиотека `random`.

In [22]:
import numpy.random as rndm

In [23]:
perm=rndm.permutation(6)
perm

array([3, 5, 1, 2, 0, 4])

In [24]:
inv_perm=np.empty(6,dtype=np.int)
inv_perm[perm]=np.arange(6)
inv_perm

array([4, 2, 3, 0, 5, 1])

In [25]:
perm[inv_perm]

array([0, 1, 2, 3, 4, 5])

In [26]:
inv_perm[perm]

array([0, 1, 2, 3, 4, 5])

Инверзна пермутација може се добити и као резултат наредбе `argsort`, али то представља мање ефикасан начин. Ова наредба враћа редослед индекса чланова низа којим би се добио сортиран низ вредности. 

In [27]:
np.argsort(perm)

array([4, 2, 3, 0, 5, 1], dtype=int32)

Опис сличних наредби за сортирање, претрагу и пребројавање чланова низа може се наћи у [документационом центру](https://numpy.org/doc/stable/reference/routines.sort.html).

Пермутацију коју пермутациона матрица $P\in\mathcal{M}_{n\times n}$ врши над врстама неке матрице $A\in\mathcal{M}_{n\times n}$ добија се формално у производу $PA.$ У пракси овај производ не користимо, већ само индексирање врста помоћу одговарајуће пермутације. Слично, за означавање аналогне пермутације колона матрице $A$ користимо $AP^T.$ Истовремена пермутација врста и колона матрице $A,$ тј. пермутација врста и колона истог типа постиже се производом $PAP^T.$
\begin{align}
    &A=\begin{bmatrix}11&12&13\\21&22&23\\31&32&33\end{bmatrix},\qquad 
    P=\begin{bmatrix}0&0&1\\0&1&0\\1&0&0\end{bmatrix},\\
    &PA=\begin{bmatrix}31&32&33\\21&22&23\\11&12&13\end{bmatrix},\qquad 
    AP^T=\begin{bmatrix}13&12&11\\23&22&21\\33&32&31\end{bmatrix},\qquad
    PAP^T=\begin{bmatrix}33&32&31\\23&22&21\\13&12&11\end{bmatrix}.
\end{align}	
Приказаћемо ово својство са претходно формираном матрицом $P1$ и матрицом $A\in\mathcal{M}_{6\times 6}.$

In [28]:
A=(np.arange(10,46)).reshape(6,6)
A

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45]])

In [29]:
P1@A

array([[28., 29., 30., 31., 32., 33.],
       [10., 11., 12., 13., 14., 15.],
       [22., 23., 24., 25., 26., 27.],
       [16., 17., 18., 19., 20., 21.],
       [40., 41., 42., 43., 44., 45.],
       [34., 35., 36., 37., 38., 39.]])

In [30]:
A[permutacija]

array([[28, 29, 30, 31, 32, 33],
       [10, 11, 12, 13, 14, 15],
       [22, 23, 24, 25, 26, 27],
       [16, 17, 18, 19, 20, 21],
       [40, 41, 42, 43, 44, 45],
       [34, 35, 36, 37, 38, 39]])

In [31]:
A@P1.T

array([[13., 10., 12., 11., 15., 14.],
       [19., 16., 18., 17., 21., 20.],
       [25., 22., 24., 23., 27., 26.],
       [31., 28., 30., 29., 33., 32.],
       [37., 34., 36., 35., 39., 38.],
       [43., 40., 42., 41., 45., 44.]])

In [32]:
A[:,permutacija]

array([[13, 10, 12, 11, 15, 14],
       [19, 16, 18, 17, 21, 20],
       [25, 22, 24, 23, 27, 26],
       [31, 28, 30, 29, 33, 32],
       [37, 34, 36, 35, 39, 38],
       [43, 40, 42, 41, 45, 44]])

In [33]:
P1@(A@P2)

array([[31., 28., 30., 29., 33., 32.],
       [13., 10., 12., 11., 15., 14.],
       [25., 22., 24., 23., 27., 26.],
       [19., 16., 18., 17., 21., 20.],
       [43., 40., 42., 41., 45., 44.],
       [37., 34., 36., 35., 39., 38.]])

In [34]:
A[permutacija][:,permutacija]

array([[31, 28, 30, 29, 33, 32],
       [13, 10, 12, 11, 15, 14],
       [25, 22, 24, 23, 27, 26],
       [19, 16, 18, 17, 21, 20],
       [43, 40, 42, 41, 45, 44],
       [37, 34, 36, 35, 39, 38]])

**Задатак 6.** Показати да за сваку пермутациону матрицу $P\in\mathcal{M}_{n\times n}$ важи $PP^T=P^TP=I.$

**Решење :**

Матрица $P\in\mathcal{M}_{n\times n}$ је пермутациона матрица уколико је добијена неком пермутацијом врста или колона јединичне матрице $I\in\mathcal{M}_{n\times n}.$ Представимо матрицу $P$ њеним колонама.
$$P=\begin{bmatrix}\begin{bmatrix}\\e_{i_1}\\ \phantom{w} \end{bmatrix}
\begin{bmatrix}\\e_{i_2}\\ \phantom{w}\end{bmatrix}\dots
\begin{bmatrix}\\e_{i_n}\\ \phantom{w}\end{bmatrix}\end{bmatrix},$$
где је $\{e_{i_1},e_{i_2},\dots,e_{i_n}\}$ пермутација вектора канонске базе. Тада је $P^TP$ матрица унутрашњих (скаларних) производа вектора ортонормиране базе, тј.
$$P^TP=\begin{bmatrix}\begin{bmatrix}&e_{i_1}^T& \phantom{i} \end{bmatrix}\\
\begin{bmatrix}&e_{i_2}^T& \phantom{i}\end{bmatrix}\\\vdots\\
\begin{bmatrix}&e_{i_n}^T& \phantom{i}\end{bmatrix}\end{bmatrix}\begin{bmatrix}\begin{bmatrix}\\e_{i_1}\\ \phantom{w} \end{bmatrix}
\begin{bmatrix}\\e_{i_2}\\ \phantom{w}\end{bmatrix}\dots
\begin{bmatrix}\\e_{i_n}\\ \phantom{w}\end{bmatrix}\end{bmatrix}=
\begin{bmatrix}e_{i_1}^Te_{i_1}&e_{i_1}^Te_{i_2}&\dots&e_{i_1}^Te_{i_n}\\
e_{i_2}^Te_{i_1}&e_{i_2}^Te_{i_2}&\dots&e_{i_2}^Te_{i_n}\\
\vdots&\vdots&\ddots&\vdots\\
e_{i_n}^Te_{i_1}&e_{i_n}^Te_{i_2}&\dots&e_{i_n}^Te_{i_n}\end{bmatrix}=I.$$
С обзиром да је $P$ регуларна матрица и да је њена инверзна матрица јединствена, закључујемо да је $P^T=P^{-1}$ за сваку пермутациону матрицу. Доказали смо да су све пермутационе матрице ортогоналне матрице.

Добијене теоријске резултате описаћемо кроз рачунски пример.

In [35]:
n=6
I=np.eye(n)
perm=rndm.permutation(n)
P=I[perm]
P@P.T

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [36]:
inv_perm[perm]=np.arange(n)
np.all(P.T==I[inv_perm])

True

**Задатак 7.** Показати да је производ пермутационих матрица поново пермутациона матрица.

**Решење :**

Нека су $P,Q\in\mathcal{M}_{n\times n}$ пермутационе матрице. Тада производ $PQ$ представља алгебарски запис замене места врста матрице $Q$ према правилу описаном унутар матрице $P.$ Због тога $PQ$ представља још једну пермутацију врста јединичне матрице $I_n,$ тј. пермутациону матрицу.

Добијене теоријске резултате описаћемо кроз рачунски пример.

In [37]:
n=6
I=np.eye(n)
perm1=rndm.permutation(n)
perm2=rndm.permutation(n)
P1=I[perm1]
P2=I[perm2]
Q=P1@P2
np.all(Q==I[perm2[perm1]])

True

In [38]:
Q=P2@P1
np.all(Q==I[perm1[perm2]])

True

**Задатак 8.** Ако је $I_{ij}$ матрица која се добија из јединичне матрице $I$ међусобном заменом њене $i-$те и $j-$те врсте, доказати да је
	$$I_{ij}^2=I,\qquad I_{ij}^T=I_{ij},\qquad I_{ik}I_{kj}I_{ji}=I_{kj}.$$

**Решење :**

Аналогно претходном задатку.

**Задатак 9.** Нека је $$S=\left[\begin{array}{ccccc}
	0&0&\dots&0&1\\0&0&\dots&1&0\\
	&&\dots&&\\0&1&\dots&0&0\\1&0&\dots&0&0\end{array}\right]$$ обрнута или контра-идентична матрица. Доказати да је $S^T=S$ и $S^2=I.$ Одредити $SAS$ за $A=[a_{ij}]\in\mathcal{M}_{n\times n}.$

**Решење :**

Матрица $S$ је симетрична $(S^T=S)$ с обзиром да једини ненула елементи се налазе на контра-дијагонали. Ова дијагонала садржи симетричне елементе у односу на главну дијагоналу. 

$S=\begin{bmatrix}\begin{bmatrix}\\e_{n}\\ \phantom{w} \end{bmatrix}
\begin{bmatrix}\\e_{n-1}\\ \phantom{w}\end{bmatrix}\dots
\begin{bmatrix}\\e_{1}\\ \phantom{w}\end{bmatrix}\end{bmatrix},$ па је
$$S^2=S^TS=\begin{bmatrix} \begin{bmatrix}\phantom{a}&e_{n}^T&\phantom{a}\end{bmatrix}\\[4pt]
\begin{bmatrix}\phantom{a}&e_{n-1}^T&\phantom{a}\end{bmatrix}\\
\vdots\\[3pt]
\begin{bmatrix}\phantom{a}&e_{1}^T&\phantom{a}\end{bmatrix}\end{bmatrix}
\begin{bmatrix}\begin{bmatrix}\\e_{n}\\ \phantom{w} \end{bmatrix}
\begin{bmatrix}\\e_{n-1}\\ \phantom{w}\end{bmatrix}\dots
\begin{bmatrix}\\e_{1}\\ \phantom{w}\end{bmatrix}\end{bmatrix}=I.$$
Трансформација $SAS$ врши истовремену инверзију врста и колона матрице $А:$
$$A=\begin{bmatrix} a_{11}&a_{12}&\dots&a_{1\,n-1}&a_{1n}\\a_{21}&a_{22}&\dots&a_{2\,n-1}&a_{2n}\\
\vdots&\vdots&&\vdots&\vdots\\
a_{n1}&a_{n2}&\dots&a_{n\,n-1}&a_{nn}\end{bmatrix}
\quad\Longrightarrow\quad
SAS=SAS^T=\begin{bmatrix} a_{nn}&a_{n\,n-1}&\dots&a_{n2}&a_{n1}\\a_{n-1\,n}&a_{n-1\,n-1}&\dots&a_{n-1\,2}&a_{n-1\,1}\\
\vdots&\vdots&&\vdots&\vdots\\
a_{2n}&a_{2\,n-1}&\dots&a_{22}&a_{21}\\a_{1n}&a_{1\,n-1}&\dots&a_{12}&a_{11}\end{bmatrix}.
$$

Оваква трансформација се постиже једноставно индексирањем.

In [39]:
A=np.arange(9).reshape(3,3)
print(A)
print(A[::-1,::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[8 7 6]
 [5 4 3]
 [2 1 0]]


**Задатак 10.** Доказати да је детерминанта ортогоналне матрице једнака $\pm 1.$

**Решење :**

$QQ^T=I\quad\Longrightarrow\quad \det(QQ^T)=\det(Q)\det(Q)=\det(Q)^2=\det(I)=1\quad\Longrightarrow\quad \det(Q)=\pm1.$

**Задатак 11.** Нека су $Q\in\mathcal{M}_{n\times n}$ и $U\in\mathcal{M}_{m\times m}$ ортогоналне матрице. Доказати да је тада ортогонална и матрица  $\begin{bmatrix} Q&O_{n\times m}\\
	O_{m\times n}&U\end{bmatrix},$ где су $O$ нула-матрице одговарајућих димензија. 

**Решење :**

\begin{align}
A&=\begin{bmatrix} Q&O_{n\times m}\\O_{m\times n}&U\end{bmatrix},\qquad QQ^T=Q^TQ=I,\ UU^T=U^TU=I\\
AA^T&=\begin{bmatrix} Q&O_{n\times m}\\O_{m\times n}&U\end{bmatrix}\begin{bmatrix} Q^T&O_{n\times m}\\O_{m\times n}&U^T\end{bmatrix}
=\begin{bmatrix} QQ^T&O_{n\times m}\\O_{m\times n}&UU^T\end{bmatrix}=I,\\
A^TA&=\begin{bmatrix} Q^T&O_{n\times m}\\O_{m\times n}&U^T\end{bmatrix}\begin{bmatrix} Q&O_{n\times m}\\O_{m\times n}&U\end{bmatrix}=\begin{bmatrix} Q^TQ&O_{n\times m}\\O_{m\times n}&U^TU\end{bmatrix}=I.
\end{align}

**Задатак 12.** Нека је $A(a)=\begin{bmatrix}\cos a&-\sin a\\ \sin a&\cos a\end{bmatrix}.$ Одредити инверзну матрицу матрице $M=\begin{bmatrix}A(a)&A(b)\\O_{2\times2}&A(c)\end{bmatrix}.$

**Решење :**

Одредићемо прво инверзну матрицу блока $A(a)=\begin{bmatrix}\cos a&-\sin a\\ \sin a&\cos a\end{bmatrix}.$
\begin{align}
\det A(a)&=\cos^2a+\sin^2a=1,\\
A(a)^{-1}&=\begin{bmatrix}\cos a&\sin a\\ -\sin a&\cos a\end{bmatrix}=\begin{bmatrix}\cos(-a)&-\sin(-a)\\ \sin(-a)&\cos (-a)\end{bmatrix}=A(-a),\\
A(a)A(-a)&=\begin{bmatrix}\cos a&-\sin a\\ \sin a&\cos a\end{bmatrix}\begin{bmatrix}\cos a&\sin a\\ -\sin a&\cos a\end{bmatrix}
=\begin{bmatrix}\cos^2a+\sin^2a&\cos a\sin a-\cos a\sin a\\ \cos a\sin a-\cos a\sin a&\cos^2a+\sin^2a\end{bmatrix}=I.
\end{align}

За одређивање инверзне матрице блок матрице $M=\begin{bmatrix}A(a)&A(b)\\ O_{2\times2}&A(c)\end{bmatrix}$ искористићемо троугаону блок форму. Потражићемо инверзну матрицу у истом блок облику $M^{-1}=\begin{bmatrix}X&Y\\ O_{2\times2}&Z\end{bmatrix}.$
\begin{align}
MM^{-1}&=\begin{bmatrix}A(a)&A(b)\\ O_{2\times2}&A(c)\end{bmatrix}
\begin{bmatrix}X&Y\\ O_{2\times2}&Z\end{bmatrix}
=\begin{bmatrix}A(a)X&A(a)Y+A(b)Z\\ O_{2\times2}&A(c)Z\end{bmatrix}=I_{4\times4}\\
\Longleftrightarrow&\quad \begin{cases}A(a)X=I_{2\times2},\\ A(a)Y+A(b)Z=O_{2\times2},\\A(c)Z=I_{2\times2}\end{cases}\\
\Longrightarrow&\quad \begin{cases}X=A(a)^{-1},\\Z=A(c)^{-1},\\ A(a)Y+A(b)A(c)^{-1}=O_{2\times2}\end{cases}\\
\Longrightarrow&\quad X=A(a)^{-1},\quad Z=A(c)^{-1},\quad Y=-A(a)^{-1}A(b)A(c)^{-1},\\
M^{-1}&=\begin{bmatrix}A(a)^{-1}&-A(a)^{-1}A(b)A(c)^{-1}\\ O_{2\times2}&A(c)^{-1}\end{bmatrix}
\end{align}

Ključno je razumevanje dejstva ortogonalnih matrica na jediničnu sferu. Naime, ortogonalne transformacije čuvaju rastojanja i uglove. Zbog toga je slika ortonormirane baze ponovo ortonormirana baza. Ortogonalna matrica vrši samo promenu koordinatnog sistema u vektorskom prostoru. Zbog toga je slika ortogonalnom transformacijom jedinične sfere ponovo jedinična sfera.