# Мататематички методи за машинско учење 2023
## Домаћи задатак број 3

<div class="alert alert-block alert-danger">
<b>Име и презиме студента:</b> Никола Петровић

<b>Број индекса:</b> 1466
    
</div>    

<div class="alert alert-block alert-info">
<b>Упутство за израду и предају домаћег задатака: </b> 
    
    1. Пре почетка израде промените име датотеке у 03Domaci_Ime_Prezime. (убаците своје име и презиме) 
    2. Попуните ћелију испод наслова одговарајућим подацима. 
    1. Употреба ћирилице није обавезна за предају домаћег задатка.
    4. За решавање задатака, уколико је потребно, отворите испод текста задатка додатне ћелије за уписивање текстуалног одговора (Markdown) или програмског кода (Code).
    1. Сва израчунавања, уколико је потребно, вршити у Python-у.
    5. Након завршетка израде решења домаћег Notebook документ сачувати у pdf формату и проследити га наставнику. То можете да урадите или кроз Teams или на мејл адресу jovana.dzunic@elfak.ni.ac.rs

</div> 

In [2]:
import numpy as np
import numpy.random as rndm
import scipy

**Задатак 1.** Конструисати матрицу $A\in\mathcal{M}_{7\times6}$ чију базу простора колона чине прве три колоне матрице $B\in\mathcal{M}_{7\times6},$ а базу језгра чине последње три врсте матрице $B.$ Матрица $B$ се генерише наредном кодном ћелијом. Кодом се такође проверава да ли случајно дефинисана матрица има прве три линеарно независне колоне и последње три линеарно независне врсте. 

(10 поена)

In [7]:
# assert je ključna reč u Pythonu koja se koristi za proveru uslova. Ako je uslov zadovoljen, 
# assert neće imati efekta i program će nastaviti sa izvršavanjem. Ako uslov nije zadovoljen, 
# assert će izazvati izuzetak (AssertionError) i prekinuti izvršavanje programa.

B=rndm.randn(7,6)-5*np.eye(7,6)
print(np.linalg.matrix_rank(B[:,:3]))
print(np.linalg.matrix_rank(B[-3:]))

3
3


In [11]:
# Generišemo matricu B
np.random.seed(42)  # Postavljamo seed za reprodukciju rezultata
B = np.random.randn(7, 6) - 5 * np.eye(7, 6)

# Proveravamo da li prve tri kolone matrice B čine bazu
assert np.linalg.matrix_rank(B[:, :3]) == 3

# Proveravamo da li zadnje tri vrste matrice B čine bazu jezgra
assert np.linalg.matrix_rank(B[-3:]) == 3

# Konstruišemo matricu A tako što uzimamo prve tri kolone matrice B kao bazu prostora kolona
A_column_space = B[:, :3]

# Da bismo pronašli bazu jezgra matrice B, moramo prvo pronaći njen null prostor
# Rešavamo sistem jednačina Bx = 0
_, _, Vh = np.linalg.svd(B)
B_null_space = scipy.linalg.null_space(B[-3:, :]).T

A = np.empty((7, 6))

A=np.dot(A_column_space, B_null_space)
# Matrica A
print("Matrica A:")
print(A)

Matrica A:
[[-0.13558703 -0.25169621 -0.36643568 -4.471631   -0.25115164  0.66605557]
 [ 4.27620736  0.14967372  0.35628558  1.28595013 -0.36646864 -0.63692232]
 [ 1.8684033  -3.80315281  5.14758825  0.72177386 -1.18289132 -1.60341839]
 [ 1.34789231  0.79469531 -1.07954664 -1.12348497  0.01550659  0.30166473]
 [-0.14924494 -0.754513    0.89314395 -0.41789245 -0.20327149 -0.16798554]
 [-1.86710344 -0.18075478  0.00875995 -0.45514849  0.13401546  0.22186241]
 [ 1.94180284 -0.65336982  1.02791185  0.1874741  -0.37607454 -0.46619462]]


<div class="alert alert-block alert-info">
<b> Тачно
    
10/10 поена </b> Резултат можете да проверите следећим кодом. </div>

In [10]:
np.round(A@B[-3:].T)

array([[-0.,  0.,  0.],
       [-0., -0., -0.],
       [-0., -0., -0.],
       [-0.,  0.,  0.],
       [-0., -0., -0.],
       [ 0.,  0.,  0.],
       [-0., -0., -0.]])

In [11]:
np.linalg.matrix_rank(np.block([B[:,:3],A]))

3

**Задатак 2.** а) Дате су матрице Гаусове трансформације
\begin{align}
L_1&=\begin{bmatrix}  1&0&0&0\\0&1&0&0\\0&0&1&0\\0&0&0&1\end{bmatrix}
+\begin{bmatrix}0\\-1\\0.5\\3\end{bmatrix}\begin{bmatrix}1&0&0&0\end{bmatrix}=I_4+v_1e_1^T,\\
L_2&=\begin{bmatrix}  1&0&0&0\\0&1&0&0\\0&0&1&0\\0&0&0&1\end{bmatrix}
+\begin{bmatrix}0\\0\\3\\2\end{bmatrix}\begin{bmatrix}0&1&0&0\end{bmatrix}=I_4+v_2e_2^T,\\
L_3&=\begin{bmatrix}  1&0&0&0\\0&1&0&0\\0&0&1&0\\0&0&0&1\end{bmatrix}
+\begin{bmatrix}0\\0\\0\\1\end{bmatrix}\begin{bmatrix}0&0&1&0\end{bmatrix}=I_4+v_3e_3^T.
\end{align}
Показати да за њих важи 
$$\big(I_4+v_1e_1^T\big)\big(I_4+v_2e_2^T\big)\big(I_4+v_3e_3^T\big)=I_4+\displaystyle\sum_{k=1}^3v_ke_k^T.$$

(5 поена)

In [2]:
import numpy as np

# Definisanje matrica
I_4 = np.identity(4)

v_1 = np.array([[0], [-1], [0.5], [3]])
e_1 = np.array([[1, 0, 0, 0]])
L_1 = I_4 + np.dot(v_1, e_1)

v_2 = np.array([[0], [0], [3], [2]])
e_2 = np.array([[0, 1, 0, 0]])
L_2 = I_4 + np.dot(v_2, e_2)

v_3 = np.array([[0], [0], [0], [1]])
e_3 = np.array([[0, 0, 1, 0]])
L_3 = I_4 + np.dot(v_3, e_3)

# Množenje matrica
L_2L_3 = np.dot(L_2, L_3)
result = np.dot(L_1, L_2L_3)

# Desna strana izraza
sum_vk_ek = I_4 + np.dot(v_1, e_1) + np.dot(v_2, e_2) + np.dot(v_3, e_3)

# Provera jednakosti
print("Leva strana izraza:\n", result)
print("Desna strana izraza:\n", sum_vk_ek)
print("Da li su matrice jednake? ", np.allclose(result, sum_vk_ek))


Leva strana izraza:
 [[ 1.   0.   0.   0. ]
 [-1.   1.   0.   0. ]
 [ 0.5  3.   1.   0. ]
 [ 3.   2.   1.   1. ]]
Desna strana izraza:
 [[ 1.   0.   0.   0. ]
 [-1.   1.   0.   0. ]
 [ 0.5  3.   1.   0. ]
 [ 3.   2.   1.   1. ]]
Da li su matrice jednake?  True


<div class="alert alert-block alert-info">
<b> Тачно
    
5/5 поена </b>  </div>

б) Дате су матрице Гаусове трансформације $L_k=I_n+v_ke_k^T,\ k=1,2,\dots,m<n,$ где је првих $k$ компоненети вектора $v_k$ једнако нули, док су $e_k$ вектори природне базе простора $\mathbb{R}^n.$ Показати једнакост
$$\big(I_n+v_1e_1^T\big)\big(I_n+v_2e_2^T\big)\cdots\big(I_n+v_me_m^T\big)=I_n+\displaystyle\sum_{k=1}^mv_ke_k^T.$$

(5 поена)

Да бисмо доказали ову једнакост, користићемо индукцију по $m$.

**База индукције ($m = 1$):**

$$(I_n + v_1e_1^T) = I_n + \sum_{k=1}^1 v_ke_k^T$$

Једнакост је тривијално тачна за $m = 1$.

**Индукцијски корак:**

Претпоставимо да једнакост важи за $m = p$:

$$(I_n + v_1e_1^T)(I_n + v_2e_2^T) \cdots (I_n + v_pe_p^T) = I_n + \sum_{k=1}^p v_ke_k^T$$

Треба доказати да једнакост важи и за $m = p + 1$:

$$(I_n + v_1e_1^T)(I_n + v_2e_2^T) \cdots (I_n + v_pe_p^T)(I_n + v_{p+1}e_{p+1}^T) = I_n + \sum_{k=1}^{p+1} v_ke_k^T$$

Прво, помножимо обе стране индукцијске хипотезе са $(I_n + v_{p+1}e_{p+1}^T)$:

$$(I_n + \sum_{k=1}^p v_ke_k^T)(I_n + v_{p+1}e_{p+1}^T)$$

Разложимо производ:

$$I_n(I_n + v_{p+1}e_{p+1}^T) + \sum_{k=1}^p v_ke_k^T(I_n + v_{p+1}e_{p+1}^T)$$

Сада разложимо сваки члан збира:

$$I_n + v_{p+1}e_{p+1}^T + \sum_{k=1}^p v_k e_k^T + \sum_{k=1}^p v_kv_{p+1}(e_k^Te_{p+1})e_k^T$$

Пошто су $e_k$ вектори природне базе, тада је $(e_k^Te_{p+1}) = 0$ за све $k \neq p+1$, и $(e_{p+1}^Te_{p+1}) = 1$. Убацимо ово у једнакост:

$$I_n + v_{p+1}e_{p+1}^T + \sum_{k=1}^p v_ke_k^T + v_{p+1}e_{p+1}^T$$

Саберемо чланове са $v_{p+1}e_{p+1}^T$:

$$I_n + \sum_{k=1}^{p+1} v_ke_k^T$$

Сада смо показали да једнакост важи и за $m = p + 1$:

$$(I_n + v_1e_1^T)(I_n + v_2e_2^T) \cdots (I_n + v_pe_p^T)(I_n + v_{p+1}e_{p+1}^T) = I_n + \sum_{k=1}^{p+1} v_ke_k^T$$

Пошто смо показали да једнакост важи за $m = 1$ (база индукције) и да ако важи за $m = p$, онда важи и за $m = p + 1$ (индукцијски корак), можемо закључити да једнакост важи за све $m < n$.


<div class="alert alert-block alert-info">
<b> Тачно
    
5/5 поена </b>  </div>

**Задатак 3.** На основу неке од обрађених декомпозиција матрица одредити базу простора врста и базу простора колона матрице
$$A=\begin{bmatrix}1&2&3&-1\\2&-1&-4&8\\-1&1&3&-5\\-1&2&5&-6\\-1&-2&-3&1\end{bmatrix}.$$


(10 поена)

In [14]:
# Definišemo matricu A
A = np.array([[1, 2, 3, -1],
              [2, -1, -4, 8],
              [-1, 1, 3, -5],
              [-1, 2, 5, -6],
              [-1, -2, -3, 1]])

Q, R = np.linalg.qr(A)

col = Q
rref, _ = np.linalg.qr(R.T)
row = rref.T
# Ispis baza prostora vrsta i kolona
print("Baza prostora kolona matrice A:\n")
print(col)
print("\nBaza prostora vrsta matrice A:\n")
print(row)

Baza prostora kolona matrice A:

[[-0.35355339  0.57048265  0.02642418  0.20489637]
 [-0.70710678 -0.20134682  0.3977211  -0.5468552 ]
 [ 0.35355339  0.23490462  0.89479525  0.11391124]
 [ 0.35355339  0.50336704 -0.17394507 -0.76900243]
 [ 0.35355339 -0.57048265  0.10101619 -0.23372284]]

Baza prostora vrsta matrice A:

[[-2.84627227e-01  3.55784033e-02  3.55784033e-01 -8.89460084e-01]
 [-4.17552986e-01 -5.57571753e-01 -6.97590520e-01 -1.67722123e-01]
 [ 7.60243500e-01  1.45537798e-01 -4.69167903e-01 -4.25123569e-01]
 [-4.08248290e-01  8.16496581e-01 -4.08248290e-01 -1.11022302e-16]]


<div class="alert alert-block alert-info">
<b> Тачно.   
    
10/10 поена</b> Само водити рачуна да урађена функција qr не ради баш најбоље редуковану декомпозицију. Треба додатно проверити добијене информације рачунајући ранг. Уграђена функција svd ради боље, али и она мора да се комбинује са информацијом о рангу матрице. То је узрок зашто у наредном задатку немате добро решење.</div>

In [15]:
np.round(row,2)

array([[-0.28,  0.04,  0.36, -0.89],
       [-0.42, -0.56, -0.7 , -0.17],
       [ 0.76,  0.15, -0.47, -0.43],
       [-0.41,  0.82, -0.41,  0.  ]])

In [16]:
np.round(R,2)

array([[-2.83,  0.35,  3.54, -8.84],
       [ 0.  ,  3.72,  7.45, -6.95],
       [ 0.  ,  0.  , -0.  , -0.37],
       [ 0.  ,  0.  ,  0.  , -0.7 ]])

In [17]:
np.linalg.matrix_rank(A) 

3

**Задатак 4.** На основу неке од обрађених декомпозиција матрица одредити матрицу пројекције на простор колона матрице
$$A=\begin{bmatrix}1&2&3&-1\\2&-1&-4&8\\-1&1&3&-5\\-1&2&5&-6\\-1&-2&-3&1\end{bmatrix}.$$

(10 поена)

In [5]:
# LU
# Definišemo matricu A
A = np.array([[1, 2, 3, -1],
              [2, -1, -4, 8],
              [-1, 1, 3, -5],
              [-1, 2, 5, -6],
              [-1, -2, -3, 1]])

# Izračunavamo LU dekompoziciju matrice A^TA
ATA = A.T @ A
P, L, U = scipy.linalg.lu(ATA)

# Izračunavamo inverznu matricu (A^TA)^{-1}
ATA_inv = scipy.linalg.inv(U) @ scipy.linalg.inv(L)

# Izračunavamo matricu projekcije P
P1 = A @ ATA_inv @ A.T

print("Matrica projekcije P (LU dekompozicija):")
print(P1)


Matrica projekcije P (LU dekompozicija):
[[ -3.06652924  10.17128936  -6.71607946  -8.6726012    3.06652924]
 [  7.20895802 -21.01686657  14.05191154  18.70408546  -7.20895802]
 [ -4.83868066  13.09437781  -8.82436282 -11.85697151   4.83868066]
 [ 10.28530735 -30.35329835  20.26904048  26.77991004 -10.28530735]
 [  3.06652924 -10.17128936   6.71607946   8.6726012   -3.06652924]]


In [7]:
import numpy as np

# Definišemo matricu A
A = np.array([[1, 2, 3, -1],
              [2, -1, -4, 8],
              [-1, 1, 3, -5],
              [-1, 2, 5, -6],
              [-1, -2, -3, 1]])

# Izračunavamo QR dekompoziciju matrice A
Q, R = np.linalg.qr(A)

# Izračunavamo matricu projekcije P
P2 = Q @ Q.T

print("Matrica projekcije P (QR dekompozicija):")
print(P2)

Matrica projekcije P (QR dekompozicija):
[[ 4.93131210e-01  3.35959457e-02  5.59932428e-02 -3.43972693e-16
  -4.95670141e-01]
 [ 3.35959457e-02  9.97773216e-01 -3.71130750e-03  3.13634211e-16
   3.28536842e-02]
 [ 5.59932428e-02 -3.71130750e-03  9.93814488e-01 -7.44891239e-17
   5.47561403e-02]
 [-3.43972693e-16  3.13634211e-16 -7.44891239e-17  1.00000000e+00
   3.31930666e-17]
 [-4.95670141e-01  3.28536842e-02  5.47561403e-02  3.31930666e-17
   5.15281087e-01]]


In [ ]:
# Cholesky
# Definišemo matricu A
A = np.array([[1, 2, 3, -1],
              [2, -1, -4, 8],
              [-1, 1, 3, -5],
              [-1, 2, 5, -6],
              [-1, -2, -3, 1]])

# Izračunavamo Cholesky dekompoziciju matrice A^TA
ATA = A.T @ A
L = np.linalg.cholesky(ATA)

# Izračunavamo inverznu matricu (A^TA)^{-1}
ATA_inv = scipy.linalg.inv(L.T) @ scipy.linalg.inv(L)

# Izračunavamo matricu projekcije P
P3 = A @ ATA_inv @ A.T

print("Matrica projekcije P (Cholesky dekompozicija):")
print(P3)

<div class="alert alert-block alert-info">
<b> Скоро тачна је само матрица $P_2.$ 
    
8/10 поена</b> 
Ја сам им убацила ознаке $P1,P2,P3.$ Проверите ранг матрице $A$ и димензије матрице $Q.$ Користите svd и информације о рангу, боље ради. Инверзне матрице које сте рачунали заправо не постоје. Добијене матрице су резултат грешака заокруживања.    
    
Резултат проверавамо помоћу особина матрице пројекције: сваки вектор из простора колона матрице $A$ слика се у самог себе, а вектори ортогонални на колоне $A$ сликају се у нула-вектор.</div>

<b><span style="font-size: 44px; color: purple;">Ispravak</span></b>

In [9]:
# Definišemo matricu A
A = np.array([[1, 2, 3, -1],
              [2, -1, -4, 8],
              [-1, 1, 3, -5],
              [-1, 2, 5, -6],
              [-1, -2, -3, 1]])

# Izračunavamo SVD dekompoziciju matrice A
U, S, VT = np.linalg.svd(A)
rank_A = np.linalg.matrix_rank(A)
dim_Q = len(S[S > 1e-10])

# Izračunavamo matricu projekcije P
P = U[:, :rank_A] @ U[:, :rank_A].T

print("Matrica projekcije P:")
print(P)

Matrica projekcije P:
[[ 4.92753623e-01  4.34782609e-02  7.24637681e-02  1.48039385e-16
  -4.92753623e-01]
 [ 4.34782609e-02  7.39130435e-01 -4.34782609e-01 -1.11474014e-16
  -4.34782609e-02]
 [ 7.24637681e-02 -4.34782609e-01  2.75362319e-01  2.72341408e-17
  -7.24637681e-02]
 [ 1.48039385e-16 -1.11474014e-16  2.72341408e-17  1.00000000e+00
   3.62898062e-17]
 [-4.92753623e-01 -4.34782609e-02 -7.24637681e-02  3.62898062e-17
   4.92753623e-01]]


In [10]:
np.isclose(A,P1@A)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [13]:
from scipy.linalg import null_space

pom=null_space(A.T)
pom.shape

(5, 2)

In [14]:
np.round(P1@pom,2)  #разлог овог доброг резултата је P1=...@A.T као што се види из наредне ћелије, 
#нисте добили тражену пројекцију

array([[ 0., -0.],
       [-0.,  0.],
       [ 0., -0.],
       [-0.,  0.],
       [-0.,  0.]])

In [15]:
np.round(A.T@pom,2)

array([[-0., -0.],
       [-0.,  0.],
       [-0.,  0.],
       [ 0.,  0.]])

In [16]:
np.isclose(A,P2@A)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [17]:
np.round(P2@pom,2)  #овде настају проблеми због лоше имплементације qr

array([[-0.01,  0.02],
       [ 0.25, -0.44],
       [ 0.41, -0.74],
       [ 0.  ,  0.  ],
       [ 0.07, -0.13]])

In [ ]:
np.isclose(A,P3@A)

In [ ]:
np.round(P3@pom,2)

<b><span style="font-size: 44px; color: purple;">Ispravak</span></b>

In [20]:
np.isclose(A,P@A)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [21]:
np.round(P@pom,2)

array([[-0., -0.],
       [ 0.,  0.],
       [-0., -0.],
       [ 0.,  0.],
       [ 0.,  0.]])

**Задатак 5.** Показати да оротогнална матрица чува норму и углове. Другим речима, за произвољну ортогоналну матрицу $Q$ и векторе $v$ и $u$ показати једнакости:
\begin{align}
&\|Qv\|=\|v\|,\\
&(Qv)\cdot(Qu)=v\cdot u,\\
&\cos\angle(v,u)=\cos\angle(Qv,Qu).
\end{align}


(10 поена)

In [3]:
import numpy as np

# Proizvoljna ortogonalna matrica Q
Q = np.array([[0.8, -0.6],
              [0.6, 0.8]])

# Proizvoljni vektori u i v
u = np.array([1, 3])
v = np.array([-2, 4])

# 1. Pokazujemo da ortogonalna matrica čuva normu
norm_u = np.linalg.norm(u)
norm_Q_u = np.linalg.norm(Q @ u)
print(f"||u|| = {norm_u}, ||Qu|| = {norm_Q_u}")

norm_v = np.linalg.norm(v)
norm_Q_v = np.linalg.norm(Q @ v)
print(f"||v|| = {norm_v}, ||Qv|| = {norm_Q_v}")

# 2. Pokazujemo da ortogonalna matrica čuva skalarni proizvod
u_dot_v = u @ v
Q_u_dot_Q_v = (Q @ u) @ (Q @ v)
print(f"u · v = {u_dot_v}, (Qu) · (Qv) = {Q_u_dot_Q_v}")

# 3. Pokazujemo da ortogonalna matrica čuva uglove
cos_angle_uv = u_dot_v / (norm_u * norm_v)
cos_angle_Q_u_Q_v = Q_u_dot_Q_v / (norm_Q_u * norm_Q_v)
print(f"cos(∠(u, v)) = {cos_angle_uv}, cos(∠(Qu, Qv)) = {cos_angle_Q_u_Q_v}")


||u|| = 3.1622776601683795, ||Qu|| = 3.16227766016838
||v|| = 4.47213595499958, ||Qv|| = 4.47213595499958
u · v = 10, (Qu) · (Qv) = 10.0
cos(∠(u, v)) = 0.7071067811865475, cos(∠(Qu, Qv)) = 0.7071067811865474


Da bismo pokazali da ortogonalna matrica čuva normu i uglove, možemo koristiti svojstva ortogonalnih matrica i svojstva skalarnog proizvoda. Neka je $Q$ ortogonalna matrica i $v$ i $u$ proizvoljni vektori. Tada važi:

$QQ^T = I$, $Q^TQ = I$ (pošto je $Q$ ortogonalna)

Prvo, pokazaćemo da $|Qv| = |v|$:

$$|Qv|^2=(Qv) \cdot (Qv)=(Qv)^T(Qv)=v^T(Q^TQ)v=v^T(I)v=v \cdot v=|v|^2$$

Kako je $|Qv|^2 = |v|^2$, sledi da je $|Qv| = |v|$.

Sada ćemo pokazati da $(Qv) \cdot (Qu) = v \cdot u$:

$$(Qv) \cdot (Qu)=(Qv)^T(Qu)=v^T(Q^TQ)u=v^T(I)u=v^Tu=v \cdot u$$

Na kraju, pokazaćemo da $\cos\angle(v,u) = \cos\angle(Qv,Qu)$:

$$\cos\angle(v,u)=\frac{v \cdot u}{|v||u|}$$

$$\cos\angle(Qv,Qu)=\frac{(Qv) \cdot (Qu)}{|Qv||Qu|}=\frac{v \cdot u}{|v||u|}$$

Pošto je $\cos\angle(v,u) = \cos\angle(Qv,Qu)$, zaključujemo da ortogonalna matrica čuva normu i uglove.

<div class="alert alert-block alert-info">
<b> Тачно
    
10/10 поена</b> </div>

<div class="alert alert-block alert-info">
<b> Укупно 48/50 поена</b> </div>