# Мататематички методи за машинско учење 2023
## Домаћи задатак број 5

<div class="alert alert-block alert-danger">
<b>Име и презиме студента:</b> Никола Петровић

<b>Број индекса:</b> 1466
    
</div>    

<div class="alert alert-block alert-info">
<b>Упутство за израду и предају домаћег задатака: </b> 
    
    1. Пре почетка израде промените име датотеке у 05Domaci_Ime_Prezime. (убаците своје име и презиме) 
    2. Попуните ћелију испод наслова одговарајућим подацима. 
    1. Употреба ћирилице није обавезна за предају домаћег задатка.
    4. За решавање задатака, уколико је потребно, отворите испод текста задатка додатне ћелије за уписивање текстуалног одговора (Markdown) или програмског кода (Code).
    1. Сва израчунавања, уколико је потребно, вршити у Python-у.
    5. Након завршетка израде решења домаћег Notebook документ сачувати у pdf формату и проследити га наставнику. То можете да урадите или кроз Teams или на мејл адресу jovana.dzunic@elfak.ni.ac.rs

</div> 

In [1]:
import numpy as np
import numpy.random as rndm

**Задатак 1.** Ако је позната SVD матрице $A=U\Sigma V^T.$
a)  Одредити SVD матрице $A^T.$ 

(5 поена)

In [2]:
# Generisanje SVD matrice A
A = np.random.randn(3, 4)
U, s, Vt = np.linalg.svd(A)

# Određivanje SVD matrica za A^T
V = U
Sigma = np.diag(s)
Ut = Vt

# Ispisivanje matrica U, Sigma i V^T za A^T
print("\nU za A^T:\n", U)
print("\nSigma za A^T:\n", Sigma)
print("\nV^T za A^T:\n", Vt)



U za A^T:
 [[-0.05201447  0.5058578  -0.86104726]
 [ 0.01014763 -0.86190217 -0.50697305]
 [ 0.99859477  0.03510753 -0.03969813]]

Sigma za A^T:
 [[2.77098267 0.         0.        ]
 [0.         1.80682408 0.        ]
 [0.         0.         0.85148452]]

V^T za A^T:
 [[-0.40805837  0.85313861 -0.1067895  -0.30698352]
 [ 0.69321775  0.28950001 -0.65088137  0.10950954]
 [-0.50071141 -0.01757556 -0.41315312  0.76044966]
 [ 0.31972738  0.43363043  0.62789645  0.5616806 ]]


<div class="alert alert-block alert-info">
<b> Тачно. Идеја је била да напишете формуле, али може и овако.
    
5/5 поена</b> </div>

In [7]:
Ut.shape, Sigma.shape, V.shape

((4, 4), (3, 3), (3, 3))

In [9]:
Sigma=np.block([[Sigma],[np.zeros(3)]])
Sigma

array([[2.77098267, 0.        , 0.        ],
       [0.        , 1.80682408, 0.        ],
       [0.        , 0.        , 0.85148452],
       [0.        , 0.        , 0.        ]])

In [11]:
np.isclose(A.T,Ut.T@Sigma@V.T)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

б) Ако је матрица $A$ регуларна, како гласи SVD матрице $A^{-1}?$

(5 поена)

<b><span style="font-size: 44px; color: purple;">Ispravak</span></b>

Ako je matrica $A$ regularna, tada postoji njena inverzna matrica $A^{-1}$. Singularna dekompozicija (SVD) matrice $A$ može se predstaviti kao:

$$A = U\Sigma V^T$$

gde je $U$ ortogonalna matrica, $\Sigma$ je dijagonalna matrica sa singularnim vrednostima matrice $A$, a $V^T$ predstavlja transponovanu matricu $V$.

Sada želimo da izrazimo $A^{-1}$ kroz SVD dekompoziciju. Neka je $A^{-1} = U' \Sigma' V'^T$, gde su $U'$, $\Sigma'$ i $V'^T$ analogni matricama $U$, $\Sigma$ i $V^T$. Da bismo pronašli ove matrice, umnožimo $A^{-1}$ sa $A$:

$$A^{-1}A = (U'\Sigma'V'^T)(U\Sigma V^T) = I$$

Prema svojstvima ortogonalnih matrica, $U'U = I$ i $VV^T = I$. Tada možemo nastaviti sa:

$$U'\Sigma'V'^TU\Sigma V^T = U'(U'^TU')\Sigma'\Sigma V^T = U'U'^TU\Sigma'\Sigma V^T = \Sigma'\Sigma$$

Poslednji korak je da pronađemo izraz za $\Sigma'$, znajući da je $\Sigma'\Sigma = I$. Za dijagonalne matrice, inverz je dijagonalna matrica sa elementima koji su recipročne vrednosti dijagonalnih elemenata originalne matrice. Dakle, $\Sigma'$ će imati formu:

$$\Sigma' = \begin{bmatrix}
\frac{1}{\sigma_1} & 0 & \cdots & 0 \\
0 & \frac{1}{\sigma_2} & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & \frac{1}{\sigma_n} 
\end{bmatrix}$$

Sada znajući $\Sigma'$, možemo izraziti $A^{-1}$ kroz SVD dekompoziciju:

$$A^{-1} = U' \Sigma' V'^T$$

Tako je SVD matrice $A^{-1}$ jednaka $U' \Sigma' V'^T$, gde je $U'=U^T$, $\Sigma'$ je dijagonalna matrica sa elementima koji su recipročne vrednosti singularnih vrednosti matrice $A$, i $V'^T=V$.


<div class="alert alert-block alert-info">
<b> Мало сте помешали матрице у конструкцији инверзне.
    
2/5 поена</b> </div>

In [14]:
np.round(A@A_inv)

array([[ 0.,  0., -1., -1.],
       [-1., -0., -0.,  0.],
       [-0., -0., -1.,  0.],
       [-1.,  1., -0., -1.]])

в) Како гласи SVD произвољне ортогоналне матрице?

(5 поена)

<b><span style="font-size: 44px; color: purple;">Ispravak</span></b>

Za ortogonalnu matricu $A$, važi $AA^T = A^TA = I$. 

SVD dekompozicija ortogonalne matrice $A$ može se izraziti kao:

$$A = U \Sigma V^T$$

gde su $U$ i $V$ ortogonalne matrice, a $\Sigma$ je dijagonalna matrica.

Za ortogonalnu matricu $A$, možemo koristiti činjenicu da je $A^TA = I$, pa možemo pisati:

$$A^TA = (U \Sigma V^T)^T (U \Sigma V^T) = V \Sigma^T U^T U \Sigma V^T = V \Sigma^2 V^T = I$$

Kako je $V \Sigma^2 V^T = I$, zaključujemo da su elementi matrice $\Sigma$ ili $1$ ili $-1$. U ovom slučaju, $\Sigma$ je dijagonalna matrica sa elementima $\pm 1$ na dijagonali, što znači da su sve singularne vrednosti ortogonalne matrice $A$ jednake $1$ ili $-1$. 

Dakle, SVD dekompozicija ortogonalne matrice $A$ ima formu:

$$A = U \Sigma V^T$$

gde su $U$ i $V$ ortogonalne matrice, a $\Sigma$ je dijagonalna matrica sa elementima koji su jednaki $\pm 1$.


<div class="alert alert-block alert-info">
<b> Мало конкретније шта су $U,V,\Sigma$ када је $A$ ортогонална. 
    
2/5 поена</b> </div>

**Задатак 2.** а) Ако су сингуларне вредности матрице $A,$ $\sigma_1,\dots,\sigma_r,$ шта су сингуларне вредности матрице $AA^TA?$

(5 поена)

Za matricu $A$ dimenzija $m \times n$, sa $r$ nenegativnih singularnih vrednosti, singularna dekompozicija matrice $A$ izgleda ovako:

$$A = U \Sigma V^T$$

gde su $U$ i $V$ matrice dimenzija $m \times r$ i $n \times r$, redom, čije su kolone ortonormirane, a $\Sigma$ je dijagonalna matrica dimenzija $r \times r$ sa nenegativnim vrednostima dijagonalnih elemenata, redom $\sigma_1, \sigma_2, \ldots, \sigma_r$.

Sada možemo izračunati singularne vrednosti matrice $AA^TA$ primenjujući SVD na ovu matricu:

$$AA^TA = U \Sigma V^T (U \Sigma V^T)^T U \Sigma V^T = U \Sigma^3 U^T$$

Ovo znači da su singularne vrednosti matrice $AA^TA$ kvadrati singularnih vrednosti matrice $A$. Dakle, singularne vrednosti matrice $AA^TA$ su $\sigma_1^3, \sigma_2^3, \ldots, \sigma_r^3$.

Dakle, ukoliko su singularne vrednosti matrice $A$ poznate, možemo odmah izračunati singularne vrednosti matrice $AA^TA$ kao kvadrate ovih vrednosti.

<div class="alert alert-block alert-info">
<b> Тачно. 
    
5/5 поена</b> </div>

б) Ако је $A=\begin{bmatrix}2&3&0&1&-1\\ 4&7&-1&2&-2 \\ -2&-4&1&-1&1\end{bmatrix}$ одредити њену пуну и редуковану SVD. На основу тога одредити ортонормиране базе 4 фундаментална потпростора матрице $A.$

(5 поена)

In [15]:
# Definisanje matrice A
A = np.array([[2., 3, 0, 1, -1], [4, 7, -1, 2, -2], [-2, -4, 1, -1, 1]])

# Izračunavanje pune SVD matrice za A
U, s, Vt = np.linalg.svd(A, full_matrices=True)

# Ispisivanje pune SVD matrice za A
print("U =\n", U, "\nS =\n", np.diag(s), "\nV^T =\n", Vt)
# Određivanje redukovane SVD matrice za A
k = np.linalg.matrix_rank(A)
U_k = U[:, :k]
s_k = s[:k]
Vt_k = Vt[:k, :]

# Ispisivanje redukovane SVD matrice za A
print("U_k =\n", U_k, "\ns_k =\n", np.diag(s_k), "\nVt_k =\n", Vt_k)

# Izdvajanje baza za 4 fundamentalna potprostora
r = np.linalg.matrix_rank(A)
basis_col_space = U_k[:, :r]
basis_row_space = Vt_k[:r, :].T
basis_null_space = np.linalg.qr(A)[0][:, r:]
basis_left_null_space = np.linalg.qr(A.T)[0][:, r:]

# Ispisivanje baza za 4 fundamentalna potprostora
print("\nBaza za R(A) =\n", basis_col_space)
print("\nBaza za R(A^T) =\n", basis_row_space)
print("\nBaza za N(A) =\n", basis_null_space)
print("\nBaza za N(A^T) =\n", basis_left_null_space)


U =
 [[-0.36317341 -0.73128089 -0.57735027]
 [-0.81489453 -0.05112304  0.57735027]
 [ 0.45172112 -0.68015785  0.57735027]] 
S =
 [[1.05562610e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 7.51900122e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 7.29127970e-16]] 
V^T =
 [[-0.46317225 -0.81474553  0.11998715 -0.23158613  0.23158613]
 [-0.40795079  0.22466739 -0.83659357 -0.20397539  0.20397539]
 [ 0.78512972 -0.38787958 -0.38787958 -0.20331035  0.20331035]
 [-0.03618666 -0.26006126 -0.26006126  0.92627855  0.07372145]
 [ 0.03618666  0.26006126  0.26006126  0.07372145  0.92627855]]
U_k =
 [[-0.36317341 -0.73128089]
 [-0.81489453 -0.05112304]
 [ 0.45172112 -0.68015785]] 
s_k =
 [[10.556261    0.        ]
 [ 0.          0.75190012]] 
Vt_k =
 [[-0.46317225 -0.81474553  0.11998715 -0.23158613  0.23158613]
 [-0.40795079  0.22466739 -0.83659357 -0.20397539  0.20397539]]

Baza za R(A) =
 [[-0.36317341 -0.73128089]
 [-0.81489453 -0.05112304]
 [ 0.45172112 -0.68015785]]

Baza za R(A^T)

<div class="alert alert-block alert-info">
<b> Тачно 
    
5/5 поена</b> </div>

**Задатак 3.** а) За матрицу $A=\begin{bmatrix}1&2\end{bmatrix}$ показати да важи $A^+=\begin{bmatrix}1/5\\2/5\end{bmatrix}$


(5 поена)

In [1]:
# Definisanje matrice A
A = np.array([[1, 2]])

# Izračunavanje pseudoinverza matrice A pomoću funkcije numpy.linalg.pinv
Ap = np.linalg.pinv(A)

# Ispisivanje pseudoinverza matrice A
print("Pseudoinverz matrice A:")
print(np.around(Ap, decimals=5))

# Ručno definisanje pseudoinverza matrice A
Ap_pseudoinverz = np.array([[1/5], [2/5]])

# Provera da li su matrice Ap i Ap_manual jednake
print("Provera da li su matrice Ap i Ap_pseudoinverz jednake:")
print(np.allclose(Ap, Ap_pseudoinverz, rtol=1e-5, atol=1e-5))



Pseudoinverz matrice A:
[[0.2]
 [0.4]]
Provera da li su matrice Ap i Ap_pseudoinverz jednake:
True


<div class="alert alert-block alert-info">
<b> Тачно 
    
5/5 поена</b> </div>

б) За произвољан вектор $v\in\mathbb{R}^n,\quad v=\begin{bmatrix}x_1\\x_2\\\vdots
\\x_n\end{bmatrix},\quad$ одредити $v^+.$

(5 поена)

<b><span style="font-size: 44px; color: purple;">Ispravak</span></b>

Da bismo pronašli opšti slučaj za pseudoinverz vektora $v \in \mathbb{R}^n$, možemo koristiti definiciju pseudoinverza preko singularne vrednosti dekompozicije (SVD). Pseudoinverz vektora (ili matrice) $v$ označavamo sa $v^+$.

Prvo, pretvorimo vektor $v$ u matricu dimenzija $n \times 1$. Tada, SVD dekompozicija matrice $v$ izgleda ovako:

$$v = U \Sigma V^T$$

gde je $U$ ortogonalna matrica dimenzija $n \times n$, $\Sigma$ je dijagonalna matrica dimenzija $n \times 1$ sa singularnim vrednostima matrice $v$ i $V$ je ortogonalna matrica dimenzija $1 \times 1$. 

Pseudoinverz $v^+$ možemo izračunati kao:

$$v^+ = V \Sigma^+ U^T$$

gde je $\Sigma^+$ dijagonalna matrica sa recipročnim vrednostima singularnih vrednosti matrice $v$ (osim nula) i $U^T$ je transponovana matrica $U$. Budući da $V$ ima dimenzije $1 \times 1$, ono je zapravo skalar i $V^T = V$. Takođe, $\Sigma^+$ će imati dimenzije $1 \times n$.

U ovom slučaju, možemo pojednostaviti izraz za $v^+$ kao:

$$v^+ = \frac{1}{\sigma_1} V U^T$$

gde je $\sigma_1$ prva singularna vrednost matrice $v$, a $U^T$ je transponovana matrica ortogonalne matrice $U$.

Kada radimo sa vektorima, pseudoinverz možemo interpretirati kao projekciju vektora $v$ na prostor kolone matrice $v$. Ovde je opšti izraz za pseudoinverz vektora $v$ u $\mathbb{R}^n$:

$$v^+ = \frac{1}{\sigma_1} V U^T$$


<div class="alert alert-block alert-info">
<b> Није добро. Општи сличај! 
    
0/5 поена</b> </div>

в) За векторе $u,v\in\mathbb{R}^n$ показати 
$$(uv^T)^+=\dfrac{1}{(u^Tu)(v^Tv)}\,vu^T.$$

(5 поена)

<div class="alert alert-block alert-info">
<b> Није добра поставка задатка, исправила сам грешку у куцању.</b> </div>

За векторе $u,v\in\mathbb{R}^n$ показујемо:

$$(uv^T)^+=(u^Tu)(v^Tv)vu^T.$$

Користимо дефиницију Мур-Пенроузовог псеудоинверза $A^+$ да изразимо $(uv^T)^+$:

$$(uv^T)^+ = (v^T)^+u^+ = \frac{v}{v^Tv} \frac{u^T}{u^Tu} = \frac{vu^T}{u^Tu} \frac{1}{v^Tv} = \frac{1}{u^Tu v^Tv} vu^Tv^T$$

<div class="alert alert-block alert-info">
<b> Ово важи само у веома специјалном случају, под који потпада матрица $uv^T.$ Наставак доле не треба. </b> </div>

<div class="alert alert-block alert-info">
<b> Тачно 
    
5/5 поена</b> </div>

**Задатак 4.** а) Ако је $A\in\mathcal{M}_{m\times n}$ произвољна правоугаона матрица, и $U\in\mathcal{M}_{m\times m},$ $V\in\mathcal{M}_{n\times n}$ произвољне ортогоналне матрице, показати да је
$$(UAV)^+=V^TA^+U^T.$$

(5 поена)

а) Да бисмо показали да је $(UAV)^+ = V^TA^+U^T$, можемо користити својства Мур-Пенроузовог псеудоинверза и ортогоналних матрица. Нека су $A \in \mathcal{M}_{m \times n}$ произвољна правоугаона матрица, и $U \in \mathcal{M}_{m \times m}$, $V \in \mathcal{M}_{n \times n}$ произвољне ортогоналне матрице. Онда важи:

1. $UU^T = I_m$, $U^TU = I_m$ (пошто је $U$ ортогонална)
2. $VV^T = I_n$, $V^TV = I_n$ (пошто је $V$ ортогонална)

Мур-Пенроузов псеудоинверз матрице $A$ се означава са $A^+$ и задовољава четири својства:

1. $AA^+A = A$
2. $A^+AA^+ = A^+$
3. $(AA^+)^T = AA^+$
4. $(A^+A)^T = A^+A$

Проверавамо да ли $(UAV)^+$ задовољава сва четири својства:

1. $(UAV)(V^TA^+U^T)(UAV) = U(AV)(V^TA^+)(VU^T)(UAV) = U(AV)(I_nA^+)(IU^T)(UAV) = U(AA^+)AV = UAV$
2. $(V^TA^+U^T)(UAV)(V^TA^+U^T) = (V^TA^+U^T)(UAA^+V) = V^TA^+(A^+A)V^TA^+U^T = V^TA^+A^+V^TA^+U^T = V^TA^+U^T$
3. $((UAV)(V^TA^+U^T))^T = (V^TA^+U^T)^T(UAV)^T = (U^T)^T(A^+)^T(V^T)^T(VA^T) = UAVV^TA^+U^T = UAV(V^TA^+U^T)$
4. $((V^TA^+U^T)(UAV))^T = (UAV)^T(V^TA^+U^T)^T = (V^TA^T)(A^+)^T(U^T)^T = V^TA^+A^T = (V^TA^+U^T)(UAV)$

Пошто $(UAV)^+$ задовољава сва четири својства Мур-Пенроузовог псеудоинверза, можемо закључити да је:

$$(UAV)^+ = V^TA^+U^T$$


<div class="alert alert-block alert-info">
<b> Тачно 
    
5/5 поена</b> </div>

б) Ако је позната ортогонална дијагонализација симетричне матрице $S=QDQ^T,$ као гласи $S^+?$

(5 поена)

Ако је позната ортогонална дијагонализација симетричне матрице $S = QDQ^T$, где је $Q$ ортогонална матрица, и $D$ дијагонална матрица, тада можемо наћи Мур-Пенроузов псеудоинверз $S^+$ следећим корацима:

1. Наћи псеудоинверз дијагоналне матрице $D$: За сваки ненула елемент $d_{ii}$ на дијагонали матрице $D$, наћи $d_{ii}^+$ тако да је $d_{ii}^+ = \frac{1}{d_{ii}}$. Ако је $d_{ii} = 0$, онда је $d_{ii}^+ = 0$. Резултат је дијагонална матрица $D^+$.

2. Искористити формулу из тачке а) за ортогоналну дијагонализацију и псеудоинверз: $S^+ = QD^+Q^T$. Заменимо $A$ са $S$, $U$ и $V$ са $Q$, и $A^+$ са $S^+$ у формули из тачке а): $(QDQ^T)^+ = QD^+Q^T$.

Тако добијамо да је псеудоинверз симетричне матрице $S$:

$$S^+ = QD^+Q^T$$


<div class="alert alert-block alert-info">
<b> Тачно 
    
5/5 поена</b> </div>

<div class="alert alert-block alert-info">
<b> Укупно 39/50 поена</b> </div>